### ISSUE TITLE
Compiler optimisations

### ISSUE THREAD

**Issue by fuzzie360** [gpujs/gpu.js#10]
Some basic compile-time optimisations would be nice.

Already implemented:

- Inlining constant uniform variables

Possible optimisations:

- [x] Compiler may generate something like `decode32(encode32(x))`, can easily be replaced as `x`
- [ ] Rewrite control structures to prevent branch. e.g. `if (x == 1) y += 1;` to `y += x*1;`

**Comment by picoCreator** [comment]
Control structure rewrite methodology is covered in greater detail at : http://theorangeduck.com/page/avoiding-shader-conditionals

Issue recreated as : https://github.com/gpujs/gpu.js/issues/30
