### ISSUE TITLE
Human friendly compiler errors

### ISSUE THREAD

**Issue by fuzzie360** [gpujs/gpu.js#11]
We should strive to achieve human friendly compiler errors like the ones produced by clang llvm

**Comment by mobiusEnd** [comment]
The function to extend inside functionNode_webgl.js, for this would be

ast_errorOutput

**Comment by robertleeplummerjr** [comment]
Considerable work has gone into this, in particular the `FunctionNode` errors being thrown.  I'm going to go ahead and say this is done to a reasonable degree in v2 rc 13.
