### ISSUE TITLE
Documentation theme selection

### ISSUE THREAD

**Issue by abhisheksoni27** [gpujs/gpu.js#110]
This is how [docdash](https://github.com/clenemt/docdash) looks:

![gpu js](https://user-images.githubusercontent.com/4340071/27803974-f69c2398-6049-11e7-97d6-401922ac1326.png)

And this is [minami](https://github.com/Nijikokun/minami):

![gpu js-minami](https://user-images.githubusercontent.com/4340071/27803977-ffa1b520-6049-11e7-8e54-5b3f1f9c3abb.png)

I think **docdash** is cool. We can change the theme color, and the nested sidebar output is great.

@robertleeplummerjr and @PicoCreator What do you think?

**Comment by robertleeplummerjr** [comment]
I believe docdash has my vote.

**Comment by robertleeplummerjr** [comment]
Maybe in the "official" color scheme here: ![](https://camo.githubusercontent.com/f48abdd17dfd3a682a55b5f3a9be83bba06e5c7d/687474703a2f2f6770752e726f636b732f696d672f6f67696d6167652e706e67)

**Comment by abhisheksoni27** [comment]
@robertleeplummerjr Good Point, Sir. :tada: 

How can we inject custom `CSS` to auto-generated docs? 

`docdash` doesn't currently have an option to adjust colors using options.

**Comment by abhisheksoni27** [comment]
[Ability to add custom styles](https://github.com/clenemt/docdash/issues/19#issuecomment-254195869)

That's a hack! But it works for us. We just need to fork it to `gpujs`, and change the colors.

**Comment by PicoCreator** [comment]
I think CSS / JS injection can pretty much let us get away with anything.... even crazy changes haha

As long as the core data formatting is valid, and there

**Comment by abhisheksoni27** [comment]
We can write a gulp task to write a new **CSS** file in the generated docs folder, right after `jsdoc` finishes. And in the `build.xml` file, we can add that gulp task. 

I think that would work. What do you think?

**Comment by abhisheksoni27** [comment]
This is complete.
