### ISSUE TITLE
_isWebGlSupported not defined: utils-core.js has a cyclic dependency call

### ISSUE THREAD

**Issue by abhisheksoni27** [gpujs/gpu.js#113]
I tried importing gpu.js and I get the following error:

`Uncaught ReferenceError: _isWebGlSupported is not defined`

It is because of this line, which references `_isWebGlSupported` while its still undefined:[Line 182 utils-core.js](https://github.com/gpujs/gpu.js/blob/develop/src/core/utils-core.js#L182)

At the bottom of the file, it is quite clear that `_isWebGlSupported` is defined after `_testingWebGl`, which is where the error occurs:

```js
const _isCanvasSupported = typeof document !== 'undefined' ? UtilsCore.isCanvas(document.createElement('canvas')) : false;
const _testingWebGl = UtilsCore.initWebGl(UtilsCore.initCanvas());
const _isWebGlSupported = UtilsCore.isWebGl(_testingWebGl);
const _isWebGlDrawBuffersSupported = Boolean(_testingWebGl.getExtension('WEBGL_draw_buffers'));
```

I think we can safely remove the `_isWebGlSupported` checks inside the `if` statement because we are technically trying to find out whether webGl is supported or not, so we have to take a chance and assume that it is there(by not checking for it). 

Then, if our assumption was wrong, `_testingWebGl` will be null, and it will safely be checked here: [Line 121 : utils-core.js](https://github.com/gpujs/gpu.js/blob/develop/src/core/utils-core.js#L121)

@robertleeplummerjr Thoughts?

**Comment by robertleeplummerjr** [comment]
Sounds good to me.

**Comment by abhisheksoni27** [comment]
PR on the way.
