### ISSUE TITLE
Userland function name safety

### ISSUE THREAD

**Issue by picoCreator** [gpujs/gpu.js#13]
Two options

1) Prefix all the function with a "user_" voodoo

2) Have a blacklist of function names. Throw an exception on GPU.addFunction call if function name is illegal.

Personally i vote for 2. Makes the shader code have less voodoo

**Comment by sawman** [comment]
Can you explain what this issue means? I was under the impression that there are no reserved function names in JS-land. If we need to add a function into the kernel we can do that in the code generation portion automatically anyway (we have issue #37 for that), so we can hide GPU.addFunction from the user.

**Comment by fuzzie360** [comment]
There are reserved names in gpu-land (and the user shouldn't have to know about them existing). Should just mangle the function name from myfunc to be user_myfunc, its much easier.

**Comment by sawman** [comment]
I personally also vote for mangling. It's just one line of voodoo so should be okay.

**Comment by sawman** [comment]
Merged into #37
