### ISSUE TITLE
Confused, Undefined, Errors..

### ISSUE THREAD

**Issue by LegitSoulja** [gpujs/gpu.js#130]
So, I am not using NodeJS, but developing for browser (JavaScript es6).

In the readme, there's a minified version of gpu, but can't find it. So, I obtained it here. http://gpu.rocks/

I am trying to do some mathematical, algorithm working with canvas/graphical option, however I can't figure out how to properly use it. I have no WebGL GLSL knowledge.

So, Trial and error
> Options
```javascript
const opt = {
    dimensions: [512,512],
    graphical: true
};
```
> Kernel
```javascript
const decode = gpu.createKernel(function(image, x, y, sx, sy) {
    // todo
},opt);
```

Now, To import canvas I read that you do this
```javascript
var gpu = new GPU({canvas: canvas});
```

However, I don't know how to use that canvas. I tried to console.log inside the kernel, but console.log isn't a function.

This section > https://github.com/gpujs/gpu.js#graphical-output explains the usage of setDimensions, and setGraphical, which is undefined in context.

I tried ignoring it, and just using canvas as the example
```javascript
this.color(0, 0, 0, 1);
```

but got the error

> An error occurred compiling the shaders: ERROR: 0:139: 'this' : Illegal use of reserved word
ERROR: 0:139: 'this' : syntax error

Can someone explain what im doing wrong, and how this works? Because I have no idea. Thanks.

I am hoping this will solve my issues with canvas, as I tried using a worker, but you can't use DOM, and you can't clone a canvas. I have an issue with canvas assets that I am trying to obtain, and decode and draw into a canvas object, which I want done kindof in a multi-thread process because doing it without, the page will take about 10-20 seconds to finish loading entirely, and I want things dynamic. I don't know if this repo is a solution to that, but I thought it wouldn't hurt to try. Is there a solution, or an alternative answer to my problem?

**Comment by LegitSoulja** [comment]
Wait, is it only per pixel drawing? I can't just draw to the canvas?

**Comment by robertleeplummerjr** [comment]
Can you post all your code or a link to it?

**Comment by LegitSoulja** [comment]
@robertleeplummerjr sorry, there's not much I could post due to me protecting my algorithm for decoding assets I'm drawing into a canvas object. 

I just need a better understanding of how drawing to the canvas is done using this library. Thanks.

**Comment by robertleeplummerjr** [comment]
Here are a couple examples: http://raytracer.crypt.sg/ & http://staceytay.com/raytracer/
As you have pointed out, the api has changed a bit since these examples were written.  I'll try and iron out a bit more detail momentarily.

**Comment by robertleeplummerjr** [comment]
The thing that must be understood with gpu.js is that the kernel in a sense _is_ the image.  Whatever comes out out of your kernel will be used on a single pixel of a texture of the context (canvas or webgl).  So setting up your kernel using the above details, we can do something like:

```javascript
const gpu = new GPU({ canvas });
const decode = gpu.createKernel(function(myArray) {
  //use this here
  this.color(0, 0, 0, 1);
  //you have access to this.thread.x and this.thread.y
  //use them like this: myArray[this.thread.y][this.thread.x]
  //if you ever want to do something like console.log (which doesn't exist on the kernel, and cannot) simply return a value you'd like to log from the kernel, and booya you have a means of logging
}, {
    dimensions: [512,512],
    graphical: true
});

//then use it
decode(myArray);
```

Does this help?

**Comment by LegitSoulja** [comment]
@robertleeplummerjr Ok im still confused. Here's what I'm trying to do.

I have encrypted images. Say for example in an image you divide width/height by 5. You have these blocks. Those blocks are moved to another location on the image (just swapped with left-right blocks).

So, decoding these images bring page drawback which makes things unresponsive before the images fully load, and when it's decoded back into its original image. 

You say single pixel, but I'm literally cropping sections out of an image and drawing them in place. So, what I'm understanding is that I can't directly do that? I'll have to draw everything per pixel, even though I'm not working with them to that full extinct?

I don't understand the thread.x and .y, nor the use of that array you provided.

**Comment by LegitSoulja** [comment]
@robertleeplummerjr this is what I'm doing to decode our assets 

```javascript
        function descramble(ctx, img, bx, by, nw, nh) {
            const lenX = Math.ceil(img.width / 30);
            const lenY = Math.ceil(img.height / 30);
            const bufX = img.width % 30;
            const bufY = img.height % 30;
            const bufXI = 30 - bufX;
            const bufYI = 30 - bufY;
            let scaleX = nw / img.width;
            let scaleY = nh / img.height;
            if (!nw && !nh) {
                scaleX = 1;
                scaleY = 1;
            }

            function drawWP(x, y, x2, y2, w, h) {

                ctx.drawImage(img, x, y, w, h, Math.ceil(bx + x2 * scaleX), Math.ceil(by + y2 * scaleY), Math.ceil(w * scaleX), Math.ceil(h * scaleY));
            }
            drawWP(0, 0, (lenX - 1) * 30, (lenY - 1) * 30, bufX, bufY);
            for (let j = 1; j < lenY; j++) {
                drawWP(0, j * 30 - bufYI, (lenX - 1) * 30, (lenY - j - 1) * 30, bufX, 30);
            }
            for (let i = 1; i < lenX; i++) {
                drawWP(i * 30 - bufXI, 0, (lenX - i - 1) * 30, (lenY - 1) * 30, 30, bufY);
                for (let j = 1; j < lenY; j++) {
                    drawWP(i * 30 - bufXI, j * 30 - bufYI, (lenX - i - 1) * 30, (lenY - j - 1) * 30, 30, 30);
                }
            }
        }
```

As you can see, I'm trying to do this, as this is making the page unresponsive.

**Comment by LegitSoulja** [comment]
How can I do this, in another thread (GPU)?

**Comment by robertleeplummerjr** [comment]
Your assumption is correct, that you'd need to draw pixel by pixel, but that is too what is happening behind the scenes with the `drawImage` method on the cpu, in a single thread, which is why you are experiencing the page being unresponsive.  I'm honestly not sure that gpu.js is the best tool for this application, because you'd likely need the images as rbga data (hence the `myArray` variable) and instructional arrays to shift data around.  You'd need to put all the instructions in arrays as well (I think, or at least that is what comes to mind as one approach) and then the gpu would iterate and create what you need as an output.

All that aside: consider if the image is decoded back onto the browser, what would be preventing someone from copying the image from the canvas, and stealing the descrambled image?

**Comment by LegitSoulja** [comment]
@robertleeplummerjr long story short it's a game, and I have it fully protected to where it cannot be obtained that easily from the canvas itself, and ontop of that I converted all the images to a texture atlas.. This is our only way to protect images, as encrypting the data itself for example using a custom encryption on top of base64 is worser to process. 

Hm, guess I'll have to re-think & re-write this encryption/decryption to work with gpu.js. It's my only last option to be able to use another thread, since I cannot do this with a worker, and I never knew JavaScript to shader language existed. I'm new to this, just curious, still looking for solutions to my problem.

**Comment by LegitSoulja** [comment]
And I can easily apply the encrypted image to a canvas, then get the rgb data, then work from there. I think I might just be satisfied knowing exactly what to do now. Thanks.
