### ISSUE TITLE
Update the website design

### ISSUE THREAD

**Issue by fuzzie360** [gpujs/gpu.js#131]
I think its about time for a front page redesign in preparation for v1.0 release.

If you have any ideas, please share them here!

Tentatively:
-Flexible benchmark (choose dimensions, tick, GPU, CPU and native and maybe include alternatives like weblas, turbo.js and etc.)
-Verifiable benchmark output (show output samples for inspection, especially on mobile devices)
-More demo links (currently I have ray tracers, image processing demos)
-A kind of REPL where you can type in code directly (potentially not useful at the moment, because the compiler errors are still not very helpful, but still would be nice to have)

I shall commit to work on this over the weekend (July 15-16).

**Comment by robertleeplummerjr** [comment]
sounds good, if you have time

**Comment by robertleeplummerjr** [comment]
In addition, I like much of the existing site, it'd be nice to say that it was built in a short time, but the ideas it encapsulates:
Simplicity and performance first
Reliability that can be trusted (tested)

**Comment by jefffriesen** [comment]
What I think would be very useful is to let people know where this can be expected to run. This will help people decide if it's worth investing a lot of time building a solution out that utilizes the GPU. I posted a related ticket to `weblas` yesterday: https://github.com/waylonflinn/weblas/issues/42

> I'm doing very computationally-heavy calculations in the browser for data visualizations. Fortunately, I'm using Electron (Chrome) so the browser features are a known entity. However, people will be installing this on lots of different desktop machines. If those machines don't have the right GPU support and/or slow GPUs, the interactions will fail because CPU fallback computations will be too slow.

> Does Weblas run or run quickly on a majority of desktop computers? Or is there a lot of variability? Are there guidelines or checks to see if a GPU on a machine is capable of running Weblas fast?

> I'm wondering if I should be thinking of this like the old days of wondering if browsers support a certain feature. Now we've got pretty good browser feature parity (especially with build tools) but as we push computation to the GPU how do we evaluation GPU support?

Thanks everyone for all of your work on this library

**Comment by robertleeplummerjr** [comment]
How does https://doxdox.org/gpujs/gpu.js/1.2.0 look for this?

**Comment by robertleeplummerjr** [comment]
Going to go ahead and close here, and handle in https://github.com/gpujs/gpu.rocks/pull/10
