### ISSUE TITLE
Fixing github linguist

### ISSUE THREAD

**Issue by PicoCreator** [gpujs/gpu.js#134]
![screen shot 2017-07-13 at 9 12 42 am](https://user-images.githubusercontent.com/17175484/28147369-8c0b2e82-67b2-11e7-8eac-213533da87f6.png)

Woohoo! guys.

However, we ain't actually HTML, its lop-sided due to all the HTML for JS unit testing.
So yea, github linguist fix requried.

https://github.com/github/linguist

**Comment by abhisheksoni27** [comment]
Dibs.

**Comment by abhisheksoni27** [comment]
#135
