### ISSUE TITLE
Npm broken I think?

### ISSUE THREAD

**Issue by KiransHub** [gpujs/gpu.js#141]
So when I pulled NPM version, I could not find a dist folder. I looked at your example and it seems to suggest that there should be a gpu.js file in the bin directory: 

<script src="../bin/gpu.js"></script>

but the file is missing when I pull it from npm.

**Comment by abhisheksoni27** [comment]
We're sorry for the inconvenience, but the npm version of the module has not been updated yet. We are trying our best to get to v1 release, and when we do, the npm module will be updated.

Meanwhile, you can try to clone the repo and run `gulp build` to get a browser build.

**Comment by KiransHub** [comment]
okay I'll give it a go. I need this lib for a neural network experiment.

*Kind Regards, *
*Kiran Randhawa - *Prime By Design Consulting Ltd

[image: View Kiran Randhawa's profile on LinkedIn]
<http://uk.linkedin.com/pub/kiran-randhawa/25/91a/2b>
*"Let's exchange ideas" *

**Comment by abhisheksoni27** [comment]
Great choice!
If you are interested, @robertleeplummerjr and I have been working on integrating `gpu.js` with [brain.js](https://github.com/harthur-org/brain.js/), which is a Neural Network library written in JavaScript.

**Comment by KiransHub** [comment]
I was trying to built the neural network library myself initially to learn how everything works on an algorithmic scale. Later I'll start looking into using libraries but not until I've understood the internals. Thank you though I will have a peek anyway. 👍
