### ISSUE TITLE
Server Side?

### ISSUE THREAD

**Issue by colin-riddell** [gpujs/gpu.js#142]
Hi. Since you are using WebGL, does that mean this will not work on server side only JS like node.js?
Thanks

**Comment by robertleeplummerjr** [comment]
That is correct, but we are planning opencl, to use https://github.com/unbornchikken/NOOOCL for v2.  Some of the glsl and connectivity to webgl will likely be reusable.

**Comment by robertleeplummerjr** [comment]
I started playing around with opencl yesterday, we may have something very soon, fyi.

**Comment by robertleeplummerjr** [comment]
To clarify, gpu.js runs on server via node fine, it just falls back to cpu.  But soon we will ahbbe acceleration in both cpu and gpu.

**Comment by loretoparisi** [comment]
💯 to use `opencl` as backend. Another option could be to use other BLAS libraries like OpenBLAS and IntelMKL, but I guess it would be a node native module to wrap C++ headers of those libs...

**Comment by robertleeplummerjr** [comment]
Follow progress on #52

**Comment by robertleeplummerjr** [comment]
This has been a while since mentioned, but we have full HeadlessGL support now since v2.

**Comment by loretoparisi** [comment]
@robertleeplummerjr so to be clear, you support WebGL windowless within node? [headless-gl](https://github.com/stackgl/headless-gl) or [node-webgl](https://github.com/mikeseven/node-webgl). Why the forked?

Thank you!

**Comment by robertleeplummerjr** [comment]
>you support WebGL windowless within node?

>headless-gl or node-webgl. Why the forked?

`headless-gl`, specifically the `gl` npm package.  

>Why the forked?

No fork, it is built in.  We have support currently for WebGL, WebGL2, HeadlessGL, and CPU.
