### ISSUE TITLE
Interactive documentation

### ISSUE THREAD

**Issue by viebel** [gpujs/gpu.js#144]
Great lib!!!!

Would you like to write interactive documentation of `gpu.js` or a blog post that explains the syntax of `gpu.js`?
It's super easy with [Klipse](https://github.com/viebel/klipse) (I'm the author of Klipse).

Take a look for instance at [this article](http://read.klipse.tech/symbolic-calculation-in-javacript/) about math.js.

**Comment by fuzzie360** [comment]
@viebel nice, will consider using this for #131 !

Is there an API to get timing information or change the evaluation delay? Is it possible to have a run button instead of live results? I'm afraid it might be a little too easy to type tab-destroying code in gpu.js's case.

**Comment by viebel** [comment]
@fuzzie360 you can control the evaluation delay with `data-eval-idle-msec` as explained [here](https://github.com/viebel/klipse#snippet-level-configuration).

No run button for the moment. 
(Pull request is welcome!)

**Comment by robertleeplummerjr** [comment]
Updated the link to point here for the time being: https://doxdox.org/gpujs/gpu.js/1.2.0
