### ISSUE TITLE
Minification issues

### ISSUE THREAD

**Issue by acailly** [gpujs/gpu.js#152]
I'm developing an app created with [create-react-app](https://github.com/facebookincubator/create-react-app) and the build phase apply some minifications that mess with GPU.js.

Here are the ones I found.

### Issue 

Consider the folowing piece of code:

```
const render = gpu.createKernel(function() {
    var sum=0
    for (var i=0; i<2; i++) {
	sum += this.thread.y * this.thread.x;
    }
    return sum;
}).setDimensions([200, 200])
```

It works well 👍 .

Then I build my app and the minification phase edit the code like this:

```
const render = gpu.createKernel(function() {
    for (var sum=0, i=0; i<2; i++) {
	sum += this.thread.y * this.thread.x;
    }
    return sum;
}).setDimensions([200, 200])
```

Which doesn't work well 👎 because the generated GLSL kernel is:

```
void kernel() {
for (float user_sum=0.0user_i=0.0;(user_i<2.0);user_i++){
user_sum+=(threadId.y*threadId.x);
}

kernelResult = user_sum;return;
}
```

You can see a comma is missing in the for loop statement.

### Hotfix

If I want it to work with production build I have to insert a noop statement between the var declaration and the for loop:

```
const render = gpu.createKernel(function() {
    var sum=0
    sum+=0 // UGLY HOTFIX
    for (var i=0; i<2; i++) {
	sum += this.thread.y * this.thread.x;
    }
    return sum;
}).setDimensions([200, 200])
```

This way the minification phase will not automatically put the var declaration in the for loop. 

### Issue with &&

If I have this code in my app:

```
if(a > 0){
    i++
}
```

then the minification will change it to:

```
a>0 && i++
```

but then it will fail because `no operation '&&' exists that takes a left-hand operand of type 'bool' and a right operand of type 'highp float'`

### Issue with conditional operator

If I have this code in my app:

```
if(a > 0){
    i++
} else {
  i = 0
}
```

then the minification will change it to:

```
a>0 ? i++ : i=0
```

and that will fail because there is an `Unknown ast type : ConditionalExpression`

### Hotfix

Both issues can be fixed by adding an else statement that can't be put in a conditionnal operator:

```
if(a > 0){
    i++
} else {
  i = 0
  for(var t=0;t<0;t++){ break }
}
```

**Comment by robertleeplummerjr** [comment]
on it

**Comment by robertleeplummerjr** [comment]
In the meantime: can you just wrap your functions in: back-ticks? "`"  That _should_ resolve it for the time being.

**Comment by acailly** [comment]
Have you an example? Is it documented somewhere?

**Comment by abhisheksoni27** [comment]
Here's what @robertleeplummerjr is suggesting:

In your kernel declaration, you can use Template Strings to wrap the anonymous function, like so:

```js
const render = gpu.createKernel(`function() {
    var sum=0
    for (var i=0; i<2; i++) {
	sum += this.thread.y * this.thread.x;
    }
    return sum;
}`).setDimensions([200, 200])
```

**Comment by acailly** [comment]
I tried that but I get an error `Uncaught fn parameter not a function (gpu.min.js:17)`
Maybe this feature is not in the version available on the website?

**Comment by robertleeplummerjr** [comment]
Likely that is a bug.  Would that solve your problems though if we did accept a string properly?

**Comment by acailly** [comment]
Passing a string instead of a function would be a nice fallback if there are some interference from build tools like in my app.
But that means losing syntax highlighting, autocompletion and linting, which is sad 😢 

The perfect solution would be to support output syntax from minifiers 😉

**Comment by robertleeplummerjr** [comment]
Great points.  I will fix it as soon as a I have a moment.

**Comment by robertleeplummerjr** [comment]
I do have a solution in mind, fyi.  Shouldn't take long to get into.  Will aim for later today.

**Comment by robertleeplummerjr** [comment]
Solution for for loops should be resolved.
I'll have to look at the other after my work day.

**Comment by robertleeplummerjr** [comment]
On the latter, could you do this?:
```js
var noop = a > 0 ? i++ : 0;
```

**Comment by acailly** [comment]
I have the same issue: `Uncaught Unknown ast type : ConditionalExpression (gpu.min.js:15)`

**Comment by robertleeplummerjr** [comment]
Did the loop fix work for you?

**Comment by acailly** [comment]
I don't think so.

I tested that kernel: 

```
var res = 0
for(var t=0, i=0;i<10000;i++){
	res += i
}
return res
```

and it outputs: 

```
float user_res=0.0;

for (float user_t=0.0user_i=0.0;(user_i<10000.0);user_i++){
user_res+=user_i;
}

kernelResult = user_res;return;
```

There is still a missing comma

**Comment by robertleeplummerjr** [comment]
What does the intermediate state look like, the minified part?

**Comment by acailly** [comment]
I didn't activate minification on this one since it already contains the problematic code: multiple instanciations in for loop

**Comment by robertleeplummerjr** [comment]
If I go here: http://gpu.rocks/
Open console and put this in the console:
```js
var gpu = new GPU();
var kernel = gpu.createKernel(function() {
    var res = 0
    for(var t=0, i=0;i<10000;i++){
        res += i
    }
    return res
}).setDimensions([200, 200]);
kernel.build();
```

I get the error, but the resulting code is as follows:
```glsl
float user_res=0.0;
for (float user_t=0.0,user_i=0.0;(user_i<10000.0);user_i++){
user_res+=user_i;
}

kernelResult = user_res;return;
```
Which doesn't line up with yours.  What browser are you using?

**Comment by robertleeplummerjr** [comment]
Note: the website isn't up to date with what is in develop branch.

**Comment by acailly** [comment]
I am on windows 10 and chrome 59

I tested your snippet on http://gpu.rocks/ and I have the same result as you

My errors occurs with a version built from sources of develop branch that contains your last commit (92d25fc9)

**Comment by acailly** [comment]
I just tried with the npm version and I don't reproduce these bugs, nice!

**Comment by robertleeplummerjr** [comment]
Nice!

**Comment by acailly** [comment]
Oops I forgot I had disabled the minification 😢 this issue is still here

**Comment by robertleeplummerjr** [comment]
This problem has since been handled, but forgot to close.  I did however revisit, and in v2, which will land this week, migrates to use const and let rather than var, which handles this issue much more gracefully.  Going to go ahead and close because handled on both accounts.
