### ISSUE TITLE
Failed to execute 'uniform3fv' on 'WebGLRenderingContext'

### ISSUE THREAD

**Issue by wagenaartje** [gpujs/gpu.js#158]
When I create a valid kernel (e.g. one of your examples), I get the following error:

> gpu.js:2226 Uncaught TypeError: Failed to execute 'uniform3fv' on 'WebGLRenderingContext': No function was found that matched the signature provided.
    at WebGLKernel.run (gpu.js:2226)
    at shortcut (gpu.js:926)
    at debug.js:88

How can fix this?

**Comment by robertleeplummerjr** [comment]
Can you post which example you are running this on?  Also, if you have any glsl source output, that'd be helpful as well.

**Comment by wagenaartje** [comment]
Nevermind, my mistake - when I called:

```js
const myFunc = gpu.createKernel(function() {
    return this.thread.x;
}).setDimensions(100);
```

it threw an error, but when I called the following:

```js
const myFunc = gpu.createKernel(function() {
    return this.thread.x;
}).setDimensions([100]);
```

it worked fine. So my bad :+1:
