### ISSUE TITLE
Typo on website saying maltrix multiplication, and 4x4 matrices multiplication question

### ISSUE THREAD

**Issue by PawelAP** [gpujs/gpu.js#160]
At the bottom of the website it says "512x512 maltrix multiplication" where maltrix should be matrix

How would you optimize this function to use simd in gpu.js?
https://github.com/mrdoob/three.js/blob/cd4cbc3b6b3378acc71381cf260de7b52c93c0b6/src/math/Matrix4.js#L392

**Comment by robertleeplummerjr** [comment]
>where maltrix should be matrix

fixed


>How would you optimize this function

```js
const gpu = new GPU();
const multiply4By4Matrix = gpu.createKernel(function(a, b) {
    var sum = 0;
    for (var i = 0; i < 4; i++) {
        sum += a[this.thread.y][i] * b[i][this.thread.x];
    }
    return sum;
}).setOutput([4, 4]);

const c = multiply4By4Matrix(a, b);
```

A 4 by 4 array will probably not see much of any performance gain.  However, the larger, the better.
