### ISSUE TITLE
Should no argument kernel be supported?

### ISSUE THREAD

**Issue by mobiusEnd** [gpujs/gpu.js#17]
Referencing an old (commented out) failing test case inside if_else.js

```
function booleanBranch( mode ) {
	var f = GPU(function() {
		var ret = 0.0;
		if(true) {
			ret = 4.0;
		} else {
			ret = 2.0;
		}
		return ret;
	}, {
		thread : [1],
		block : [1],
		mode : mode
	});
	
	QUnit.ok( f !== null, "function generated test");
	QUnit.close(f(), 42.0, 0.01, "basic return function test");
}

QUnit.test( "booleanBranch (auto)", function() {
	booleanBranch(null);
});

QUnit.test( "booleanBranch (GPU)", function() {
	booleanBranch("gpu");
});

QUnit.test( "booleanBranch (CPU)", function() {
	booleanBranch("cpu");
});
```

Which currently fails, presumingly cause our entire system expects an argument for data input.

Soooo..... should this be fixed?

To replicate: just comment back in those test case, its inside test/src/features/if_else.js

**Comment by fuzzie360** [comment]
This test is using the old API, should use gpu.createKernel instead

**Comment by mobiusEnd** [comment]
Oooppss... missed that lol.

We definitely need more informative errors haha.

Fixed and merged.
https://github.com/gpujs/gpu.js/pull/18
