### ISSUE TITLE
math functions

### ISSUE THREAD

**Issue by loldrup** [gpujs/gpu.js#170]
can I access math functions such as sinus and cosinus from my kernel function?

**Comment by robertleeplummerjr** [comment]
are they defined in js or in glsl?

**Comment by loldrup** [comment]
My function is just a few lines of code, so I can write it in whatever language you recommend. The faster the better :)  As long as I can access sinus and cosinus :)))

**Comment by Ameobea** [comment]
@loldrup You can use both `sin` and `cos` through `Math.sin()` and `Math.cos()` from within your kernel code.

Like this:
```js
var kernel = gpu.createKernel(function(x) {
  var result = Math.cos(x);
  ...
});
```

**Comment by robertleeplummerjr** [comment]
Beat me to it.

**Comment by robertleeplummerjr** [comment]
that is what makes open source so cool, people helping people.  Love it.

**Comment by loldrup** [comment]
Thanks! :D

Den 24/08/2017 4.01 AM skrev "Casey Primozic" <notifications@github.com>:
