### ISSUE TITLE
Add support to load textures (and save them)

### ISSUE THREAD

**Issue by VitaliKaiser** [gpujs/gpu.js#172]
Hi,

in my case I want to do some calculations and in the end fuse it with an image via bilinear interpolation. Therefore it would be perfect if there was an option to create input from an image-url.

Binding a image to an opengl texture is pretty easy:
```javascript
gl.enable(gl.TEXTURE_2D);
let texture = gl.createTexture();

let image = new Image();
image.onload = function() {
    gl.bindTexture(gl.TEXTURE_2D, texture);
}
image.src = "kitten.jpg";

```

Could you add a method to the `GPU` class (something like `createTexture(url)`) to create a GPU.js compatible `texture object` from an image url?

That would be awesome. 

Best,
Vitali

**Comment by robertleeplummerjr** [comment]
Handling urls can get a little hairy, and it really muddies up the api, but if we allowed for just handling the type we could just have it as duck type detection.  Example:
```js
const run = gpu.createKernel(myFunction);
run(kittenBlob);
```


And out of curiosity, this is a result of a random "kitten blob": ![](https://media1.giphy.com/media/VIPdgcooFJHtC/giphy.gif)
