### ISSUE TITLE
WebGL warning: Exceeded 16 live WebGL contexts for this principal, losing the least recently used one.

### ISSUE THREAD

**Issue by Drulac** [gpujs/gpu.js#174]
Hello, thanks for you good job :-)

I have this warning when I use gpu.js. I have this warning under firefox(v56) but not under chromium(v57) with the same code.

**Comment by robertleeplummerjr** [comment]
Do you have any sample code for reproduction?

**Comment by hjondi** [comment]
I managed to reproduce. simply do a loop and render more than 16 kernel

**Comment by robertleeplummerjr** [comment]
I believe you just need to share canvas and contexts: `const gpu = GPU({ canvas, webGl })`

**Comment by nickhingston** [comment]
i think the only way of fixing this is to have an explicit destroy method on the kernel and gpu classes...

looks like we do gl.createBuffer for instance, but no code to destroy them

https://stackoverflow.com/questions/23598471/how-do-i-clean-up-and-unload-a-webgl-canvas-context-from-gpu-after-use
