### ISSUE TITLE
Is there any way to pass the function to `createKernel` as string ?

### ISSUE THREAD

**Issue by Drulac** [gpujs/gpu.js#175]
All is in the title, is there any way to pass the function to `createKernel` as string ?

**Comment by RationalCoding** [comment]
You could use the 'Function' object.

```javascript
gpu.createKernel(new Function('function foo () { return 1 }'))
```

**Comment by Drulac** [comment]
that's really bad for performances
I have made a PR here : https://github.com/gpujs/gpu.js/pull/176

**Comment by Drulac** [comment]
https://github.com/gpujs/gpu.js/pull/176 have solve the issue :-)

**Comment by robertleeplummerjr** [comment]
@RationalCoding that is a nice suggestion, but the internals already process via `fn.toString()` so to protect scope, so this was a natural progression for the library.
