### ISSUE TITLE
I got error 'gpu.min.js:16 Uncaught Auto dimensions only supported for kernels with only one input'

### ISSUE THREAD

**Issue by TrsNium** [gpujs/gpu.js#177]
I got an error when multiplying matrices.

matrix shape are [4194304, 1] and [1, 4194304].

And I wrote code as following... 

```js
function matMult(a, b, x_dim, y_dim) {
    console.log(typeof(a), typeof(b), a, b)
    const opt = {
        output: {
            x: x_dim,
            y: y_dim
        }
    };

    func = gpu.createKernel(function() {
        var sum = 0;
        for (var i = 0; i < x_dim; i++) {
            sum += a[this.thread.y][i] * b[i][this.thread.y];
        }
        return sum;
    }, opt);
    return func(a, b)
}

var r = math.sqrt(matMult(x.valueOf(), math.transpose(y).valueOf(), 1, n_point))
```

sorry, Im begginer, so I cannot solve myself.

**Comment by abhisheksoni27** [comment]
What is the error? Is it: **Uncaught Auto dimensions only supported for kernels with only one input** ?

**Comment by abhisheksoni27** [comment]
What is the error? Is it: **Uncaught Auto dimensions only supported for kernels with only one input**?

**Comment by RationalCoding** [comment]
The opts kernel constructor doesn't seem to be unrolling the `output` object.

Use '.setOutput` for now. I'll PR the fix in a moment.

**Comment by TrsNium** [comment]
thanks!

**Comment by TrsNium** [comment]
When I just remake my function , I got this error...

Uncaught TypeError: gpu.createKernel(...).setOutput is not a function
