### ISSUE TITLE
Return isn't typedArray

### ISSUE THREAD

**Issue by Drulac** [gpujs/gpu.js#184]
The return isn't typedArray, while i use `.setFloatOutput(true)`, it's just Array.

I'm using chrome 57 on debian 9 if it can help.

**Comment by codingCasually** [comment]
I was actually looking for a way to return a normal array from a gpu.js function as many of the normal array methods don't work with typed arrays.

I tried adding .setFloatOutput(true) but still returned false for Array.isArray(arrayName) indicating a typedArray.

You could try the Array.isArray(arrayName) and see if it returns true or false to confirm this.

Source: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Typed_arrays

**Comment by robertleeplummerjr** [comment]
Now `Float32Array` is always favored in v2.
