### ISSUE TITLE
Any examples?

### ISSUE THREAD

**Issue by ccorcos** [gpujs/gpu.js#186]
I'm hoping to just do some basic matrix math... are there any examples using this library? I'm not sure what the expected inputs and outputs are for this example:

```
const gpu = new GPU();
// Create the GPU accelerated function from a kernel
// function that computes a single element in the
// 512 x 512 matrix (2D array). The kernel function
// is run in a parallel manner in the GPU resulting
// in very fast computations! (...sometimes)
const multiplyMatrix = gpu.createKernel(function(a, b) {
  var sum = 0;
  for (var i = 0; i < 512; i++) {
    sum += a[this.thread.y][i] * b[i][this.thread.x];
  }
  return sum;
}).setDimensions([512, 512]);

// Perform matrix multiplication on 2 matrices of size 512 x 512
const c = multiplyMatrix(a, b);
```

Is `a` 512 arrays of length 512?

**Comment by robertleeplummerjr** [comment]
a and b are both 512 x 512.  The output (dimensions has been renamed to output) is 512 x 512. Here is a neural net that uses gpu.js: https://github.com/BrainJS/brain.js/blob/nn-gpu/src/neural-network-gpu.js#L196

search for "createKernel" for the various examples.

**Comment by ccorcos** [comment]
I see. So its not linearized into an array...
