### ISSUE TITLE
What is the limit of the input array size?

### ISSUE THREAD

**Issue by rjamesnw** [gpujs/gpu.js#196]
Just wanted to know the longest array I can send as numerical input to be processed.  I'm trying to try it to calculate gravitational forces of thousands of particles by passing in an array of various values.

Also, what performance impact is there for me to update this array each time?  Does it get re-uploaded, or is the memory mapped to the GPU somehow?

**Comment by robertleeplummerjr** [comment]
I'm currently working out a streaming method for input values which will greatly speed up transfer to GPU, it should easily make it into v1.  But long story short, maximum input size is going to be dependant on your GPU.  Once your values are on the GPU, use the `outputToTexture` option on the kernel, and your values stay on the GPU, so there isn't a penalty for reuse.

**Comment by rjamesnw** [comment]
But if my values stay on the GPU can I still access the output with the texture option? I still need the results. ;)

**Comment by robertleeplummerjr** [comment]
Say you have 15 different kernels, and they depend on values from previous kernels: this is where the texture option shines.  Otherwise, there isn't a real reason to use it.

**Comment by rjamesnw** [comment]
But can I still read the results from JS using the texture option? Or is that only for rendering textures?

**Comment by Richard-Mathie** [comment]
check these out to see your webgl browser limitations:
https://alteredqualia.com/tmp/webgl-maxparams-test/
https://browserleaks.com/webgl
http://webglreport.com
