### ISSUE TITLE
What GLSL functions are supported?

### ISSUE THREAD

**Issue by rjamesnw** [gpujs/gpu.js#199]
Can I used functions like "distance", etc.?  If so I'm not sure how to pass in the two points.  Do I just create a vec2 and GPU.JS will pick it up?  I'm guessing when you "compile" the functions you might be erring out on non-recognized functions...?

(BTW: Full API Reference is 404! ;))

**Comment by robertleeplummerjr** [comment]
I believe the full list is anything that is in glsl that lines up with javascript's naming convention minus "Math.", but this should be added before v1.

**Comment by robertleeplummerjr** [comment]
@dannycalleri, care to take this one?

**Comment by dannycalleri** [comment]
This should be the complete list of the Math functions supported by GLSL:

```
abs
acos
asin
atan
atan2
ceil
cos
exp
floor
log
log2
max
min
sign 
sin
sqrt
tan
```

hope that helps :)

**Comment by robertleeplummerjr** [comment]
Could you add it to the readme.md?

**Comment by robertleeplummerjr** [comment]
too: `round` is injected, so that works as well

**Comment by dannycalleri** [comment]
Ok, missed that, I'm modifying the README.md 👍

**Comment by robertleeplummerjr** [comment]
ty @dannycalleri!
