### ISSUE TITLE
OpenGL code generation support

### ISSUE THREAD

**Issue by PicoCreator** [gpujs/gpu.js#2]
Long term practical application, that may have commercial usage.

1) Upload "big data" set
2) Get sample of data set in browser
3) Experiment with local scripts, in webgl
4) Run it on scale / grid in opengl

**Comment by fuzzie360** [comment]
If this would be implemented it would most likely be a Node package to generate C code. Something like:

```
var gpu = require('gpu');
gpu.createKernel(function() {
    return 42;
})
.dimensions([512, 512])
.generateBindings({
    name: "test",
    language: "c"
}, function(err) {
    console.log("Files written successfully");
});
```

**Comment by mobiusEnd** [comment]
Then we shall wait a very long time then haha. Priority to webgl first.

**Comment by robertleeplummerjr** [comment]
Priority give, now time to plan.  I vote:
```js
const GPU = require('gpu');
const gpu = GPU({ mode: 'opencl' });
gpu.createKernel(function() {
    return 42;
}).dimensions([512, 512]);
```

**Comment by robertleeplummerjr** [comment]
probably v2 though

**Comment by abhisheksoni27** [comment]
@robertleeplummerjr Brilliant. We should make the API as similar as possible so that in the end, it's just about which mode you choose/have access to.

**Comment by robertleeplummerjr** [comment]
I think I'd like to close this in favor of: https://github.com/gpujs/gpu.js/issues/52 or related effort for opencl.
