### ISSUE TITLE
Particle Physics Simulation in the GPU using GPU.JS

### ISSUE THREAD

**Issue by rjamesnw** [gpujs/gpu.js#203]
If interested you can see it here:
https://www.youtube.com/watch?v=ujzXyK4Ffo0
8)

**Comment by robertleeplummerjr** [comment]
I don't like this.

I love it.  Fantastic work!  I bet we can make it way faster....

**Comment by robertleeplummerjr** [comment]
Is this on a public repo?  If so, post a link?

**Comment by robertleeplummerjr** [comment]
If we put all the data on the gpu, and just had the visual output, we could prevent the buffer transfer.

**Comment by robertleeplummerjr** [comment]
I see you found that Firefox is superior for glsl.  It really is a fantastic browser!

**Comment by robertleeplummerjr** [comment]
Regarding: https://www.youtube.com/watch?v=7I8YqmBO6Nc
I think you are giving up too quickly on gpu, I see a bunch of things that could be done to enhance the performance here.  You mention that reading the pixels is slow, it is, but if you keep most of the math on the gpu, you can substantially gain in performance.  I bet you could easily get this to run 1000 particles on gpu at at least 40 if not 60 fps.

**Comment by rjamesnw** [comment]
In order to turn this into a game I need the data 6 times (each physics frame) per render frame (60 FPS). That’s calling readPixels 360x a second, and only for 1024 objects, and the grid (2000x2000) that stores the objects (using x,y as a fast lookup) has to be filled by the CPU and fed back in (didn’t even get that far). Then I have to also include large sprite bodies (particle groups) and I may have to use a physics library. I even tried once per render frame and got it closer to 40/50, but that was also by removing the calculations (this is no good as 60 FPS means a fastest speed of 60 pixel movements a second, but I wanted faster - I’m not using predictions).  I decided to build the shaders myself to custom tailor and squeeze out every ounce of speed I can, and in the end ‘readPixel()’ was the bottleneck.  I even tried to use a pixel pack buffer instead (GPU copy texture to the buffer then read the buffer) which was worse. ‘ReadPixels()’ is just bad: there’s no getting around it.  I’m using WebGL 2 and multiple frame buffer color attachments so I can process lot of data in a single fragement. If I limit calculations to periodic ones (like gravity calculated between 2000x2000 objects - which still is fast!), and other periodic stuff, it works best - seems better suited for that. ;)

**Comment by rjamesnw** [comment]
BTW: The particles have to be added to the grid as well to bounce off each other, as well as detect collision with sprite objects, so that is starting to go way over the flexibility of what I can do shader wise; However, I might be able to use multiple shaders, but to get the data back 2-3 times per physics update would be major lag. So far my test with web workers shows much faster processing batching the data streams to multiple web workers because of the readPixels lag, but I’m still testing to make sure it’s working correctly. I’m not abandoning anything, I’m finding the best places to use things. I have a wrapper that can switch between processing math per threads or the GPU for the simulator.

**Comment by robertleeplummerjr** [comment]
Because of how the GPU works, you may be able to do all the computation on the GPU rather than offset it to CPU, but understanding (and I've really only just begun) is a bit tricky.  The idea is you can go much deeper with the math on GPU and raycast what you need out of input buffers to achieve your output buffer.  Would you be open to adding me as a private contributor to your project, and I could identify some of these areas if I can find them?

**Comment by rjamesnw** [comment]
Perhaps a bit later, the code is in great flux with lots of testing and refactoring (and it's quite huge and complicated lol [it's buried into my working game engine, of sorts]).  I needed maximum control over the processing of multiple input/output layers on a single frame buffer, which I was not able to do with GPU.JS. Each fragment invocation can process ALL calculations for a single object, effectively allowing many outputs and not just one (i.e. `out0 = vec4(x,y,velx,vely); out1 = vec4(gridx,gridy,gridPixelX,gridPixelY); out2 = vec4(mass,global var1,gloval var 2, etc);`). I can easily process millions quickly (and someone else has done it [without collision, which is easy]) but only if I never read the pixels, lol.  Somehow I'd need to execute another shader program to take the output textures from the previous framebuffer, then scan EVERY object for EVERY pixel to output grid data (and I tested I can loop 10000x10000 fairly fast [which is not bad, and I may go there to test next]). If only I could modify an indexable buffer! ;)

**Comment by robertleeplummerjr** [comment]
Just modify it using output of the next program using textures.  Like so:

```js
const kernelUpdatePosition = gpu.createKernel(function(hugeArray1, hugeArray2) {
  //does HUGE work here
})
  .setOutputToTexture(true);

const kernelDetectCollosion =  = gpu.createKernel(function(hugeArray) {
  //does HUGE work here
})
  .setGraphical(true);

const texture = kernelUpdatePosition(hugeArray1, hugeArray2);
kernelUpdatePosition(texture);
```


`setOutputToTexture` is where the real magic happens.  It keeps the memory on the GPU, as much as you want.  That coupled with `setGraphical` you could potentially have no readback to CPU.

**Comment by rjamesnw** [comment]
I’m sure it would be great - but now I have shaders rendering calculations to multiple buffers in one pass instead of multiple calls (less round trip overhead). ;) Just trying to reduce the overhead as much possible by getting to the bones of it (and I can better tailor the speed). Perhaps I’ll try a separate project with the above just for the fun of it and post the project for anyone else to play with. ;)

I’m also almost finished testing with web workers. Batch processing to workers gets me close to 50,000 particles at high FPS in Firefox. ;) At least I can also do more in the code level.  Still, GPU calculations are much higher. Even if I did try the code you have above, I would need near instant collision feedback for other people to hook JS into, and checking on the calculations from the GPU once each frame at the most causes it to drop way too much. It’s only good for periodic calculations only - like calculating gravitational forces.

**Comment by robertleeplummerjr** [comment]
Ty for sharing this.  Be sure to share more info if you'd like to utilize GPU.js more.
