### ISSUE TITLE
Other operations in the super kernel allowed?

### ISSUE THREAD

**Issue by rjamesnw** [gpujs/gpu.js#204]
Regarding this in your docs:

> const add = gpu.createKernel(function(a, b) {
> 	return a[this.thread.x] + b[this.thread.x];
> }).setOutput([20]);
> 
> const multiply = gpu.createKernel(function(a, b) {
> 	return a[this.thread.x] * b[this.thread.x];
> }).setOutput([20]);
> 
> const superKernel = gpu.combineKernels(add, multiply, function(a, b, c) {
> 	return multiply(add(a, b), c);
> });
> 
> superKernel(a, b, c);

Is `return multiply(add(a, b), c);` all I can do in there?  I'm guessing this is a nested shader situation where the buffer from one is passed into another by the GPU so I can't do much. ;)

**Comment by robertleeplummerjr** [comment]
Combine kernels still runs in js.  It simply configures the functions so that they talk to each other using  textures, and the last output performs `toArray()`
