### ISSUE TITLE
Error calling super kernel

### ISSUE THREAD

**Issue by rjamesnw** [gpujs/gpu.js#205]
> Unhandled exception at line 661, column 8 in http://localhost:64094/lib/gpu.js/gpu.js
> 0x800a138f - JavaScript runtime error: Unable to get property '2' of undefined or null reference
> 

_(I'm using TypeScript so I left in the types so you can see what I'm passing in)_

'paramTypes' is undefined:

```
	if (argument.type === 'Identifier') {
				var paramIndex = funcParam.paramNames.indexOf(argument.name);
				if (paramIndex === -1) {
					functionArguments.push(null);
				} else {
					functionArguments.push({
						name: argument.name,
						type: funcParam.paramTypes[paramIndex] <= undefined
					});
				}
			} else {
				functionArguments.push(null);
			}

```

Called like this:

```
                this._CalcDistanceAndForces = this.gpu.createKernelMap({
                    CalcDist: calcDist,
                    CalcGravForce: calcGravForce
                }, function (
                    unitBlockSize: number, metersPerBlockSize: number, worldMass: number, gravitationalScale: number, maxGravitationalForce: number, // (globals)
                    x: number[], y: number[], mass: number[] // (object data)
                ): any {
                        return calcGravForce(worldMass, gravitationalScale, maxGravitationalForce, calcDist(unitBlockSize, metersPerBlockSize, x, y), mass);
                    }, { output: [this.maxObjects] });
```

The two functions are like this:

        export function calcDist(
            unitBlockSize: number, metersPerBlockSize: number, // global world params
            x: number[], y: number[] // (per object params)
        ) {
        ...
        }

        export function calcGravForce(
            worldMass: number, gravitationalScale: number, maxGravitationalForce: number, // global world params
            distances: number[], mass: number[] // (per object params)
        ) {
        ...
        }

**Comment by robertleeplummerjr** [comment]
I believe what is happening here is type detection is getting a null or undefined value, and so gpu.js cannot trace the type for when compiling the shader.

**Comment by robertleeplummerjr** [comment]
Can you confirm?

**Comment by rjamesnw** [comment]
I don’t have the code anymore, but that could be - perhaps a value was undefined and the type couldn’t be detected. I was sure I double and triple checked I was passing valid values. Perhaps it was the why I was calling them? I just figured I’d post my issue here as an FYI in case it helped at all. Perhaps I can try to integrate it again soon and then you can grab the code. I have to complete some other changes first.

**Comment by robertleeplummerjr** [comment]
Going to go ahead and close for the time being, until this may come up again.
