### ISSUE TITLE
Could not call same function from different places

### ISSUE THREAD

**Issue by Renha** [gpujs/gpu.js#207]
Weird behavior, try to execute this:

```
function demo3( assert, mode ) {
	var gpu = new GPU({ mode: mode });
	
	var f = gpu.createKernel(function(a, b) {
		function custom_adder(a,b) {
			return a+b;
		}
		function some_fun_1(a,b) {
			return custom_adder(a,b);
		}
		function some_fun_2(a,b) {
			return custom_adder(a,b);
		}
		return some_fun_1(1,2)+some_fun_2(a[this.thread.x], b[this.thread.x]);
	}, {
		dimensions : [6]
	}).setDebug(true).setOutput([6]);
	
	var a = [1, 2, 3, 5, 6, 7];
	var b = [4, 5, 6, 1, 2, 3];
	
	var res = f(a,b);
	return res;
}
console.log(demo3() );
```

there is error
```
An error occurred compiling the shaders: ERROR: 0:129: 'custom_adder' : no matching overloaded function found
```

**Comment by Renha** [comment]
I can't even imagine why there is error

**Comment by robertleeplummerjr** [comment]
creating a unit test to expose failure...

**Comment by robertleeplummerjr** [comment]
reproduced here: https://github.com/gpujs/gpu.js/compare/207-same-function-reuse?expand=1

**Comment by robertleeplummerjr** [comment]
glsl:
```glsl
float some_fun_2(float user_a, float user_b) {
return custom_adder(user_a, user_b);
}
float custom_adder(float user_a, float user_b) {
return (user_a+user_b);
}
float some_fun_1(float user_a, float user_b) {
return custom_adder(user_a, user_b);
}
```

The issue is order of writing the kernel.  We need to get the value of `custom_adder` before that of `some_fun_2`.

**Comment by robertleeplummerjr** [comment]
Should be solid now.  Care to try again?

**Comment by Renha** [comment]
looks like it works now, thanks!

**Comment by robertleeplummerjr** [comment]
![](https://media3.giphy.com/media/tIeCLkB8geYtW/giphy.gif)

**Comment by Renha** [comment]
well, it's ok to keep that closed, and i don't want to open another issue (yet), but how are functions sorted? I've got another situation where needed function is placed in GLSL after it was called, while in JS i've placed it above. Tried renaming, didn't help. Why aren't functions ordered in given order?

**Comment by robertleeplummerjr** [comment]
Functions are sorted in the order they are required.  just open another issue, we'll get it sorted.

**Comment by Renha** [comment]
Thanks! It’ll take some time to get simplest reproduction code, this case is somewhat more complicated than precious one.
