### ISSUE TITLE
Link to API document is broken

### ISSUE THREAD

**Issue by hktonylee** [gpujs/gpu.js#208]
The link to the API document [http://gpu.rocks/api/](http://gpu.rocks/api/) in the bottom of home page is broken. It shows 404 Page not found. Please check.

**Comment by robertleeplummerjr** [comment]
For the time being, use [Readme Documentation](https://github.com/gpujs/gpu.js/blob/develop/README.md), till we get it sorted

**Comment by stq** [comment]
Seems like it's a placeholder for API docs.

**Comment by robertleeplummerjr** [comment]
If we redirected to something like: https://doxdox.org/gpujs/gpu.js/1.2.0 would that be satisfactory?

**Comment by hktonylee** [comment]
That link is ok as long as the Readme document is also there. Both documents are necessary for different people.
