### ISSUE TITLE
The `ast` variable is undefined before use

### ISSUE THREAD

**Issue by hktonylee** [gpujs/gpu.js#209]
Here are several examples. Similar code snippet exists in many places in the library.

https://github.com/gpujs/gpu.js/blob/1f8de19561b5426ebcc040695511485379a2c5de/src/backend/cpu/function-node.js#L356

https://github.com/gpujs/gpu.js/blob/1f8de19561b5426ebcc040695511485379a2c5de/src/backend/cpu/function-node.js#L412

https://github.com/gpujs/gpu.js/blob/1f8de19561b5426ebcc040695511485379a2c5de/src/backend/cpu/function-node.js#L520

**Comment by robertleeplummerjr** [comment]
wish granted.  Ty!

**Comment by hktonylee** [comment]
Yeah!! Thanks & Merry Christmas!
