### ISSUE TITLE
Is this supposed to be Node compatible? it doesnt currently work. 

### ISSUE THREAD

**Issue by viziionary** [gpujs/gpu.js#215]
Installing as per the instructions does not work. 

    const GPU = require('./node_modules/gpu.js/src/index'); // Error: Cannot find module 'gpu.js'

**Comment by robertleeplummerjr** [comment]
Main was pointing to the wrong location.  I bumped, tested locally, and was able to run through a test.  Eventually we will have both client and server side testing, ty for bringing this to our attention!
