### ISSUE TITLE
v1 needs a release name

### ISSUE THREAD

**Issue by robertleeplummerjr** [gpujs/gpu.js#219]
Help us find a name for v1 release.
![](https://media0.giphy.com/media/ULhy3hP2EqRDa/giphy.gif)

**Comment by fuzzie360** [comment]
Hi @robertleeplummerjr!

What do you think of naming releases after great mathematicians?

- Newton
- Archimedes
- Gauss
- Euler
- Riemann
- Poincare
- Lagrange
- Euclid
- Hilbert
- Leibniz
- Grothendieck
- Fermat
- ...

I like it as an analogue to Nvidia's GPU architecture named after great scientists 

- Tesla
- Fermi
- Kelper
- Maxwell
- Pascal
- Volta
- ....

**Comment by robertleeplummerjr** [comment]
I like it!  Who should we start with?

**Comment by robertleeplummerjr** [comment]
Some other random suggestions:
* Foods
* Cloud formations
* Oceanic phenomenon
* Skateboard tricks
* Chemical reactions
* Paradoxes
* Normalities
* Emoji's
* Power generators
* Rockets
* Rocket Scientists
* Childhood science experiments
* Woodworking tools
* Mechanical components used for transportation (piston, tire, impeller, propeller, warp drive)
* Measurement tools
* Math tools

**Comment by robertleeplummerjr** [comment]
It just hit me.... _jellyfish types_.

v1 "man-of-war"

Thoughts?

**Comment by robertleeplummerjr** [comment]
![](http://gpu.rocks/img/jelly.png)

**Comment by leeoniya** [comment]
> It just hit me.... jellyfish types.

https://en.wikipedia.org/wiki/Irukandji_jellyfish

**Comment by robertleeplummerjr** [comment]
I am both awed and terrified.

"Irukandji" is also really fun to say.

**Comment by abhisheksoni27** [comment]
What about disease names?

v1 "melanoma"

v2 "transverse myelitis"

:laughing:

**Comment by abhisheksoni27** [comment]
Or. Or. Meds?

v1 "Advair Diskus"

v2 "Amoxicillin"

**Comment by robertleeplummerjr** [comment]
I don't favor the disease names, because... it negative in its connotation, or medication because of its connection with big pharma, trademarks, and .  So far the winners (that are tieing) are:

* skateboard tricks
  * ? (none yet suggested), open to suggestions!
* jellyfish names
  * man of war
  * Irukandji

Could we start voting etc.

**Comment by fuzzie360** [comment]
@robertleeplummerjr lets go the jellyfish route, common name only?

**Comment by robertleeplummerjr** [comment]
"man of war" then?

**Comment by robertleeplummerjr** [comment]
I'm really going to try and get everything buttoned up for a 2017 release, fyi.

**Comment by jefffriesen** [comment]
I like jelly fish names. "man of war" sounds good. Save Irukandji for a smaller, but powerful release!

**Comment by robertleeplummerjr** [comment]
https://github.com/gpujs/gpu.js/releases/tag/1.0.0

"man of war" it is
