### ISSUE TITLE
extracting or graphing results takes time proprtional to the number of previous kernel applications (possible memory leak in gpu.js?)

### ISSUE THREAD

**Issue by vincenzoml** [gpujs/gpu.js#225]
I'm running an algorithm that requires to repeat a kernel several times on its output (cellular-automata-alike).  It would be great if that could be done without re-allocating a new output texture for each invocation. However, I found that deleting textures and objects is enough to get reasonable computing times. Here is my main loop:

  var state = compute(i.data)
  for (let i = 0; i < k; i++) {
    let state2 = compute(state)
    state.webGl.deleteTexture(state.texture)
    delete(state)
    state = state2
  }

"compute" is a kernel, with outputToTexture = true. The above loop repeats a kernel for k steps (is it possible to do this entirely in gpu code?). I then want to either get the results in CPU land, or visualize them in a gl texture for performance. But in both cases, this last step takes an insane amount of time, which is proportional to the "k" of the *previous* loop! For example, with k= 3000 and input size 4096 * 4096, I get 279 milliseconds for computation (which is great!) and more than 3000 milliseconds for visualization! With k=1000, I get 184 milliseconds for computation, and 1302 milliseconds for visualization. Why the difference between "1302" and "3000"? There may be a memory leak in gpu.js.

*** BIG FAT NOTE 1: for "visualization" above I actually mean *only* the time to prepare the graphical texture, not the time for actually drawing the canvas, which is very fast. 

*** BIG FAT NOTE 2: I wouldn't mind paying 3 seconds for gpu->cpu transfer of a 16mpixels image. But (I can show code), here the problem is that those 3 seconds become larger and larger with k growing! Wich is strange, since what on earth should the second kernel know about that?

For completeness, here is how I get back results to cpu land: 
compute.setOutputToTexture(false)
let retval = compute(state)

and here is how I visualize the results (note that I don't do both, either one or the other)

  const visualize = gpu.createKernel(function (a, palette) {
    let x = this.thread.x
    let y = this.thread.y
    let id = a[x][y]
    this.color(palette[id][0], palette[id][1], palette[id][2], 1.0)
  },
    { output: [canvas.width, canvas.height],
      outputToTexture: true,
      graphical: true
    })

  visualize(state, i.palette)
  const canvas2 = visualize.getCanvas()
  document.getElementsByTagName('body')[0].appendChild(canvas2)

**Comment by vincenzoml** [comment]
I created a minimal (non-)working example here:

https://gist.github.com/vincenzoml/80c195916ae8f5de75a0ecc628b36a01

**Comment by robertleeplummerjr** [comment]
I believe this to be resolved.
