### ISSUE TITLE
run npm install and then has error:"Error: Cannot resolve module 'fs' in \node_modules\gpu.js\dist\backend\web-gl  @ ./~/gpu.js/dist/backend/web-gl/kernel.js 11:9-22",before I install fs module

### ISSUE THREAD

**Issue by yubeixin** [gpujs/gpu.js#227]

**Comment by robertleeplummerjr** [comment]
interesting, `fs` is a module that comes with node.  What version of node are you on?

**Comment by merttoka** [comment]
Same here.  `npm 5.5.1`

**Comment by yubeixin** [comment]
the version of node is 8.5.0 that I used,is it ok?

**Comment by robertleeplummerjr** [comment]
I'll need to investigate this, seems like something changed in node.

**Comment by robertleeplummerjr** [comment]
This should be resolved, we were including a module for no good reason.  Remove, bumped version number, and published.
