### ISSUE TITLE
Support for ClojureScript (support for aliasing `this`)

### ISSUE THREAD

**Issue by blueridanus** [gpujs/gpu.js#228]
As it currently stands, the library cannot be used from ClojureScript, because javascript interop is not playing nice with `gpu.createKernel()`.

Specifically, to acess `this` inside a function(as is a necessity inside the function passed to `createKernel()`), ClojureScript requires you to use the form [`this-as`](https://cljs.github.io/api/cljs.core/this-as), which, for the scope of the form you passed as the second argument, binds javascript's `this` to the name passed in the first argument.

Well, looking at code generated by ClojureScript, we can see the specifics of how that happens:
```clojure
(def f (.setOutput
        (.createKernel gpu
         (fn [] (this-as t
                         (.-x (.-thread t)))))
        [100]))
```
generates:
```javascript
fnString: "function (){\n var t= this;\n return t.thread.x;\n}"
```
Trying to call this function first generates the error `TypeError: n.clone(...) is undefined`, which I'm clueless on. But trying to call again will keep yielding the following error:
```
An error occurred compiling the shaders: ERROR: 0:124: 'this' : Illegal use of reserved word 
ERROR: 0:124: 'this' : syntax error
```
Which tells us GPU.js complains because it can't handle a variable being used as an alias for `this`.

**Comment by robertleeplummerjr** [comment]
Can you throw together a js fiddle or something that reproduces this error?  As I read the code above, I see there isn't a closing brace, which seems incomplete.

**Comment by blueridanus** [comment]
The braces are correctly closed. I had to copy by typing manually and forgot to close the braces, apologies.

**Comment by blueridanus** [comment]
Here's a fiddle:
https://jsfiddle.net/becyrwf4/1/

**Comment by robertleeplummerjr** [comment]
We ended up solving this by using `gpu_threadX` to reference threads rather than the conventional `this.thread.x`, other than that is was compiler issues.  We got it sorted!
