### ISSUE TITLE
Use OES_texture_float to avoid encode32/decode32 when possible

### ISSUE THREAD

**Issue by loyd** [gpujs/gpu.js#230]
What do you think?

**Comment by loyd** [comment]
Sorry, it's `floatTextures` option.

**Comment by robertleeplummerjr** [comment]
Always a pleasure when someone does their homework.  We try our best with documentation, but we are always improving.  Ty for the idea, great minds...

**Comment by robertleeplummerjr** [comment]
To assist, I've opened  #231
