### ISSUE TITLE
How come the functions are synchronous? Is ther ean async API?

### ISSUE THREAD

**Issue by Darker** [gpujs/gpu.js#232]
So since the GPU calculations are running not just in another thread but in another device completely, how come they are synchronous?

Is there an async api? Eg.:
```
const gpu = new GPU();

const matMult = gpu.createKernel(function(a, b) {
    var sum = 0;
    for (var i = 0; i < 512; i++) {
        sum += a[this.thread.y][i] * b[i][this.thread.x];
    }
    return sum;
}).setOutput([512, 512]);

// matMult returns Promise and once the GPU calculation completes
// promise is resolved. Another operations can be done in the mean time.
const c = await matMult(a, b);
```

**Comment by robertleeplummerjr** [comment]
The original concept was to support both.  The limitation is/was that WebGL's bindings are synchronous in javascript.  Look for more async in v2.

**Comment by fuzzie360** [comment]
Unfortunately WebGL is a completely synchronous API even though it is asynchronous behind the scenes. There is no way to make the API asynchronous, not even using WebWorkers. Async API may come in the future, but at the moment, we have decided that we would rather have no async API than a fake async API which might confuse users.

**Comment by Darker** [comment]
Uh, that's a big flaw in the WebGL API specification I guess. But thank you for those quick answers, that's rare on github! :)

**Comment by robertleeplummerjr** [comment]
The devs that manage this project... are rare.

**Comment by RationalCoding** [comment]
Do WebGL calls within an iFrame block the parent thread?

**Comment by robertleeplummerjr** [comment]
good question!

Does this get us close?:
```
const gpuIframe = document.createElement('iframe');
gpuIframe.src = 'https://gpu.rocks';
document.body.appendChild(gpuIframe);
gpuIframe.width = 300;
gpuIframe.height = 300;
gpuIframe.style.position = 'absolute';
```
click "Run Benchmark"

**Comment by RationalCoding** [comment]
Tried this:

```javascript
const gpuIframe = document.createElement('iframe');
gpuIframe.src = 'https://gpu.rocks';
document.body.appendChild(gpuIframe);
gpuIframe.width = 1000;
gpuIframe.height = 1000;
gpuIframe.style.position = 'absolute';

var t0 = performance.now()
window.setInterval(() => {
  console.log('running', performance.now() - t0)
}, 100)
```

And the main thread's interval drops from 100ms to 1-2 seconds. But I can't tell if it's just a slowdown, or it's only firing between GPU.js calls.

**Comment by robertleeplummerjr** [comment]
You could throw a brain.js unit test into a file, and fore sure you'd be testing if multithreading works.  Here is the class that uses GPU.js: https://github.com/BrainJS/brain.js/blob/master/src/neural-network-gpu.js

and a unit test could be: https://github.com/BrainJS/brain.js/blob/master/test/base/likely.js

**Comment by RationalCoding** [comment]
If it is blocking the parent thread, I'd warrant that cross-origin iFrames would do the same, which seems to violate same-origin policy, although in a relatively harmless way.

**Comment by RationalCoding** [comment]
Long WebGL calls block the parent thread:

```html
<html>
    <body></body>
    <script>
        const gpuIframe = document.createElement('iframe');
        gpuIframe.src = 'test-blocking-child.html';
        document.body.appendChild(gpuIframe);
        gpuIframe.width = 1000;
        gpuIframe.height = 1000;
        gpuIframe.style.position = 'absolute';

        var t0 = performance.now()
        window.setInterval(() => {
        console.log('running', performance.now() - t0)
        }, 100)
    
    </script>
</html>
```

```html
<html>
    <body>
    <p>Running...</p>
</body>
    <script src="browser.js"></script>
    <script>
        const gpu = new GPU();

        const stuckInLoop = gpu.createKernel(function() {
            var sum = 0;
            for (var i = 0; i < 100000000000; i++) {
                sum++;
            }
            return sum;
        }).setOutput([512, 512]);

        stuckInLoop()
        console.log('child done')
    </script>
</html>
```

**Comment by RationalCoding** [comment]
I couldn't figure out how to get brain.js to run long enough to notice a block.

**Comment by robertleeplummerjr** [comment]
>I couldn't figure out how to get brain.js to run long enough to notice a block.

Which training set did you use it on?


Music to my ears.

**Comment by robertleeplummerjr** [comment]
@RationalCoding I went ahead and threw this together to prove it to myself: https://jsfiddle.net/robertleeplummerjr/b3f91f2h/

It learns.... almost instantly.


nuts!

Validation, anyone?  GPU.js really does rock!

**Comment by bthj** [comment]
deeplearn.js seems to be using empty queries to get "a callback when the GPU command queue has executed":
https://github.com/PAIR-code/deeplearnjs/blob/master/src/kernels/backend_webgl.ts#L197
-> 
https://github.com/PAIR-code/deeplearnjs/blob/master/src/kernels/webgl/gpgpu_context.ts#L350

Are you considering a similar approach for v2 ?

**Comment by Darker** [comment]
@bthj  That sounds like a workaround that does not introduce asynchronous behavior, just fakes it. As long as the GPU API is synchronous, events make no difference.

**Comment by robertleeplummerjr** [comment]
Could we utilize web workers with webgl in them?

**Comment by robertleeplummerjr** [comment]
For the record: I hate tricking anything, but we did add a synthetic asynchronous means in brain.js simply to make it able to manage long running threads obey.  But I don't condone trickery for the very sugar of it.

**Comment by Darker** [comment]
@fuzzie360  said 
> There is no way to make the API asynchronous, not even using WebWorkers.

But I don't think that's the case, Workers can't halt the main thread as far as I know. However the last time I read the issues here, running GPU.js in web worker was not supported.
