### ISSUE TITLE
Specifically requested settings vs. undefined (auto) settings behavior

### ISSUE THREAD

**Issue by fuzzie360** [gpujs/gpu.js#236]
Hi guys, after taking a closer look at #235 I noticed that a lot of my config logic has already changed drastically. Specifically, the way the mode and the floatTextures and floatOutput options are selected.

For example, these lines for selecting the mode for the user:

https://github.com/gpujs/gpu.js/blob/85316fd8525f70fc57b2775010ab1ffd7133da91/src/core/gpu.js#L26-L53

The original version of gpu.js supported 3 explicit settings for mode:

- Auto
- GPU
- CPU

Since auto is the same as not setting anything, auto was removed as a configuration option.

The special difference between GPU mode and auto mode is that auto mode automatically downgrades to CPU mode if GPU mode fails, but GPU mode will throw immediately if GPU mode fails.

Use case example:

- Auto: for actual end user usage
- GPU: for the benchmark in our front page.... we want to show a red error to the user because we need to inform that the operation has failed.

I feel that the same logic should be used for floatTextures and floatOutput, because the developer should not need to mess around with these settings and there is also no way for the developer to force a specific mode and prevent execution. And if we use a specific mode, the developer should know the operation has failed.

Because there's currently no way to express the settings, I consider it a bug and I want to revert the logic back to its original state. Preferably before v1.0 is released because I believe this a dangerously subtle difference.

Would like hear some feedback regarding this issue soon. Its quite a small code change.

**Comment by robertleeplummerjr** [comment]
I love this feedback, and will be offering up a pr tomorrow at the earliest.

**Comment by robertleeplummerjr** [comment]
Take a look at https://github.com/gpujs/gpu.js/pull/237, may be rough, but with your insight, we can get there.

**Comment by robertleeplummerjr** [comment]
Ok, this is partly correct, there are currently four values, soon to be five (open-cl).  Externally, the user's will only need to know about falsey, 'gpu', and 'cpu'.

BUT _internally_ we need to distinguish `web-gl` from other techniques, like `open-cl` (maybe `cudas`, or `arrayfire` later?) as well as other internal commands, such as `webgl-validator` for _testing purposes_.  So I believe this is ok, but we may want to ensure that documentation is up to date.  Does that work for you?
