### ISSUE TITLE
Wrong Number of Primes 

### ISSUE THREAD

**Issue by DaveBben** [gpujs/gpu.js#239]
Awesome library. I was testing it with a primes calculator using a simple loop. It seems to work fine from 1 to 10,000. However, anything over than that throws a wrong number. Does this require an input array or different data type? Thanks

    const gpu = new GPU();

```
function isPrime(n) {
  if (n > 1) {
    for (let i = 2; i < n; i += 1) {
      if (n % i === 0) {
        return 0;
      }
    }
    return 1;
  }

  return 0;
}


gpu.addFunction(isPrime);

const matMult = gpu.createKernel(function() {
    var counter = 0;
    for (let i = 1; i < 100; i += 1) {
        if (isPrime(i) == 1) {
        counter +=1;
        }
      }
      return counter
}).setOutput([1]);

//1 to 100 - 25 primes is right
//1 to 10,000 - 1229 primes is right
//1 to  100,000 9772 primtes...not right




document.write(matMult());


```

**Comment by fuzzie360** [comment]
Hi @DaveBben. You should have received a warning for attempting to try ‘for (let i = 2; i < n; i += 1)’ . If it doesn’t then that will need fixing.

WebGL does not support unbounded for loops, so you need to set ‘maxLoopIterations’ settings to emulate unbounded for loops.

**Comment by robertleeplummerjr** [comment]
The other thing you can do is use a constant:
```js
for (let i = 2; i < this.constants.n; i += 1)
```

Which is the same thing as hardcoding it, but is syntactic sugar for composability using the underlying compiler.

**Comment by DaveBben** [comment]
Oh that makes sense now. Thank you!

**Comment by robertleeplummerjr** [comment]
Did you actually get the warning, or no?
