### ISSUE TITLE
Should Promise polyfill be part of the build?

### ISSUE THREAD

**Issue by picoCreator** [gpujs/gpu.js#24]
While I yet to test it,
I managed to reduce down the whole polyfill to 884 bytes.

https://github.com/picoded/small_promise.js/blob/master/bin/small_promise.polyfill.min.js

So we could actually squeeze it in.

**Comment by RangerMauve** [comment]
Usually, you'd advise users to include polyfills instead of bundling them. One of the reasons is that there may be multiple libraries in a given project that rely on the same polyfillable API, having each of them bring the polyfill with them doesn't make much sense.

**Comment by picoCreator** [comment]
@TODO: throw an exception for lack of "promises" if doing an async execution then
