### ISSUE TITLE
CPU vs. GPU test maps output differently.

### ISSUE THREAD

**Issue by BryanGrezeszak** [gpujs/gpu.js#241]
I came across this issue while basically just familiarizing myself with the library (checking out how inputs get mapped to outputs via `this.thread.x` and `this.thread.y` and such..._yah, I know it's December 29th, but I had some spare time...don't judge me!_).

I was having a really hard time figuring out the scheme of it until I tried it with `{mode:'cpu'}` where suddenly everything acted exactly as I had expected all along (which it previously had not been). So I set up a side-by-side test and sure enough it mapped completely different in cpu vs gpu modes (with the gpu mode definitely being the non-expected output).

-------------

Live fiddle of the issue (writes to console, so open dev tools): https://jsfiddle.net/39ztrpvs/

Code:
```javascript
var cpu = new GPU({mode:'cpu'});
var gpu = new GPU({mode:'gpu'});

function testFunc(inp) {
	return inp[this.thread.y][this.thread.x];
}

const cpuKernel = cpu.createKernel(testFunc).setOutput([3, 3]);
const gpuKernel = gpu.createKernel(testFunc).setOutput([3, 3]);

console.log('cpu:', cpuKernel( [[0,1,2], [3,4,5], [6,7,8]] ) );
console.log('gpu:', gpuKernel( [[0,1,2], [3,4,5], [6,7,8]] ) );
```

My Output (on my machine at least: Windows, Chrome):
```javascript
// matches expectation
cpu: [[0, 1, 2],
      [3, 4, 5],
      [6, 7, 8]]

// notice the left column is all messed up
gpu: [[0, 1, 2],
      [0, 4, 5],
      [3, 7, 8]]
```

Specifically (in gpu mode):
Position (0,0) in the input for some reason gets mapped to _both_ (0,0) and (0,1) in the output.
Position (0,1) in the input gets mapped to (0,2) in the output.
Position (0,2) doesn't get mapped to the output at all.

This same pattern of the 1st column doing 0 twice, then continuing normally (then, of course, never getting to the last index) seems to continue regardless of how long I make that y-axis.

**Comment by fuzzie360** [comment]
Interesting! Thanks for the bug report, its very helpful for ensuring compatibility.

The output is correct on my computer. What GPU hardware are you currently using? If you have dual graphics, please list both of them.

**Comment by BryanGrezeszak** [comment]
I was afraid that might be the case. Best case scenario, of course, was just a flub somewhere in the JS which is easily found and fixed...but I guess it must be some specific weirdness to specific GPUs. I'm no GPU expert, but I'm guessing that's a lot harder to deal with :)

AMD Radeon R5 is what I'm testing on. Pretty basic graphics on an everyday laptop.

**Comment by fuzzie360** [comment]
High chance the error can be pin pointed to here:

https://github.com/gpujs/gpu.js/blob/4173dd9610b9c04fa064e7e2e12b5f066d7eeac7/src/backend/web-gl/shader-frag.js#L36-L39

Probably need to do some rearrangement of ops and typecasting and etc. You might want to fool around and tinker with it if you want. I'll get some AMD cards out of storage.

The good news is the numeric encoding doesn't look faulty on this platform.... on the surface at least. There might be flaws we haven't yet noticed.

**Comment by BryanGrezeszak** [comment]
Cool. It might take me a day or two to get on it, but I'll fiddle with that a bit on my machine. I'll see what happens and let you know.

**Comment by robertleeplummerjr** [comment]
With @fuzzie360 on the case, it is as good as done.

![](https://media1.giphy.com/media/B8LMeYAvA4Dtu/giphy.gif)

**Comment by robertleeplummerjr** [comment]
It'd be nice if we had special case fallbacks, rather than handling this stuff in the same script for everyone.  Like the feature detection we are currently doing.

**Comment by fuzzie360** [comment]
Actually yes @robertleeplummerjr. If you can test if the GPU is IEEE floating point compliant, you can actually make encode32 and decode32 much faster than it currently is for non-floating point textures. No need for expensive slow integer divisions and typecasting.

**Comment by robertleeplummerjr** [comment]
Where do we begin?

**Comment by samreid** [comment]
I reproduced the problem on my machine as described in https://github.com/gpujs/gpu.js/issues/241#issue-285186484

I'm running a 2016 MacBook Pro with Radeon Pro 460 4GB

**Comment by nickhingston** [comment]
Same issue on my late 2017 mac - 
Radeon Pro 560 4096 MB
Intel HD Graphics 630 1536 MB

Works on my iPhone8, though some floating point weirdness only on the number 7 returns 6.999999523.

I think this might be breaking my use case, I'm attempting to decode and render DICOM images.

I am inputing a large Uint8Array and after a certain number of rows, the image starts getting corrupted.  OK on cpu mode.

I have tried inputting a 2D array instead, and it changes the behaviour, the image seems to corrupt later on.  Some memory alignment issue?

for iPhone, slightly different i can only get a completely blank image on GPU mode, and fine on CPU...

**Comment by robertleeplummerjr** [comment]
I believe this may have been resolved in https://github.com/gpujs/gpu.js/releases/tag/1.4.8

Can you check the latest?

**Comment by robertleeplummerjr** [comment]
Closing, will reopen if issue persists.

**Comment by samreid** [comment]
I tested on 2016 MacBook Pro with Radeon Pro 460 4GB which previously exhibited the problem, as noted in https://github.com/gpujs/gpu.js/issues/241#issuecomment-372029167

I used gpu.js-1.4.8 and the results were:

![image](https://user-images.githubusercontent.com/679486/42186417-d73571ec-7e09-11e8-8581-1410c4771ecc.png)

So this appears to be fixed.

**Comment by robertleeplummerjr** [comment]
Huzzah!!!!

**Comment by robertleeplummerjr** [comment]
![](https://media3.giphy.com/media/ffoUuIn1qRz7G/giphy.gif)
