### ISSUE TITLE
Passing objects to GPU code

### ISSUE THREAD

**Issue by yalcinmelihyasin** [gpujs/gpu.js#245]
Hi, 

I am trying to port my pet project about ray-tracing with GPU computation to the JavaScript. But it requires passing object information to GPU(e.g center, radius, color etc.). 

I couldn't figure out how to pass the information as objects to the GPU side. Is it possible ? Or is it just that I am confused.

**Comment by robertleeplummerjr** [comment]
Can you just pass the objects, arrays to the kernel?  Object passing isn't currently supported, but sounds like an interesting feature for sugar.

**Comment by kolserdav** [comment]
I'm trying to multiply two matrices.
`const gpuKernel = gpu.createKernel(function(array, weight) {
                if (this.thread.x !== 3){
                    return array[this.thread.z][this.thread.y][this.thread.x] * weight[this.thread.z][this.thread.y][this.thread.x];
                }
                else {
                    return array[this.thread.z][this.thread.y][this.thread.x];
                }
            })
                .setOutput([4, width, heigth]);
            list = gpuKernel(list, this.weights[classWeight]);`
If the scale matrix after the initial random generation is a three-dimensional array, then everything goes well. But after saving the matrix of weights to the base of MongoDB, it becomes an object of the form `{"1": 0.432432, "2": 0.4546546, ...}`. And then every value inside Kernel is null. Although in theory the process of extracting values from an array and from an object with numbered fields should not differ.

**Comment by robertleeplummerjr** [comment]
The problem you speak of is a deserialization from json to node.  I played around with https://gist.github.com/jonathanlurie/04fa6343e64f750d03072ac92584b5df, maybe it is applicable here? It would be nice to handle this in GPU.js, but GPU.js would be solving a problem that originated elsewhere.

**Comment by kolserdav** [comment]
Hello! Thanks for the quick response.
I already thought about what you say. But I was afraid that additional deserialization operations would take up a lot of resources. Now I have done such a function, and I see that everything works fine, without a visible increase in resource costs.
`this.weights[classWeight] = this.weights[classWeight].map(item => {
                const it = Object.values(item);
                return it.map(item2 => {
                    return Object.values(item2);
                });
            })`

**Comment by robertleeplummerjr** [comment]
Going to go ahead and close as it is not an existing feature.  An issue that perhaps proposes this would possibly come about, but not here.
