### ISSUE TITLE
Cleaning up the memory

### ISSUE THREAD

**Issue by elessarperm** [gpujs/gpu.js#246]
Hey guys. I'm trying to make continuous grid calculation using gpu.js and I need to repeat kernel function thousands of times. Every output becomes input for the next iteration.

I've set `outputToTexture` to `true` and just executing the kernel in the loop, getting the result and passing it as an input again.

`for(let i = 0; i < iterations; i++) {
            res = kernel(size, res);
        }`

Unfortunately, if I set a texture size bit enough (1024) I eventually ran out of graphical memory (or solemthing like this. Every browser produces different error). The bigger texture - the faster I get the error.

I think the problem is there because every texture I use continue to exist in GPU memory so I want to know the way to deallocate all textures I don't want or something. 

As an example of error; Chrome 63.0.3239.132 (win10) produces the following when I'm trying to use `texture.toArray()`

> An error occurred compiling the shaders: 
precision highp float;
kernel.js:196
precision highp int;
precision highp sampler2D;
attribute highp vec2 aPos;
attribute highp vec2 aTexCoord;
varying highp vec2 vTexCoord;
uniform vec2 ratio;
void main(void) {
  gl_Position = vec4((aPos + vec2(1)) * ratio + vec2(-1), 0, 1);
  vTexCoord = aTexCoord;
}

Firefox just giving `Ran out of memory` to me.

**Comment by elessarperm** [comment]
UPD. I found a way to clean up my memory using `texture.delete()`. You should update the documentation about the issue.
And could one of you approve the way I use your library for this kind of task. Maybe I'm using the wrong way?

**Comment by robertleeplummerjr** [comment]
Would you be able to show us some of the output that reproduces this issue?

**Comment by elessarperm** [comment]
Nothing special actually. I reproduced it by making an array of random values 0-1 and just wrote the kernel that moves it by 1 pixel like `return input[(this.thread.x + 1) % size][(this.thread.y + 1) % size]`, then runned it in the cycle passing previous result as an input until it crashes.
I managed to reproduce it in latest Chrome and Firefox Developer at Windows 10, GeForce GTX 970

**Comment by robertleeplummerjr** [comment]
Can you make a simple jsfiddle that reproduces it instantly?  I just want to make sure we attack this correctly.

**Comment by robertleeplummerjr** [comment]
A way to handle this is to have an intermediate function that copies the output from the first function to it, and have both have their `immutable: false` (or default).  That way you will only ever have 2 sets of values, and never input the output into itself.
