### ISSUE TITLE
Is there a way to track GPUs perforamance?

### ISSUE THREAD

**Issue by Andriy-Kulak** [gpujs/gpu.js#248]
This isn't directly an issue for gpu.js library, but I figured it might be a good place to ask some knowledgeable people. What is the best way to track gpu performance/availability/temperature with a javascript/node js based package or something similar? I want to remotely track performance of GPUs and get notifications if something goes wrong.

**Comment by lukas2005** [comment]
for performance you can create a function that does some kind of a expensive GPU operation like matrix multiplication and then just get the start time and end time get the diffrence between them end send that to some kind of a web app

**Comment by robertleeplummerjr** [comment]
The simplest way would be to use [https://developer.mozilla.org/en-US/docs/Web/API/Console/time](console.time), but there is as well a more complex example [here](https://github.com/gpujs/gpu.js/blob/develop/test/benchmark.js).
