### ISSUE TITLE
Profiling curve of GPU.JS performance

### ISSUE THREAD

**Issue by picoCreator** [gpujs/gpu.js#25]
Cause seriously, for small data sets CPU is just better.

Need to "objectively" show the data speed up as the data set gets larger (lol)

**Comment by picoCreator** [comment]
Current prototype in commit e1bb4571258fbeaf5b3fb02af0ea4bd527efddad

Now with pretty graphing (to be improved on) of the benchmark timing, and performance gain (or loss)

Go to demo/playground.html click "run the benchmark!"

**Comment by picoCreator** [comment]
Benchmarking playground DONE!

http://gpu.rocks/playground/playground.html

**Comment by 5chdn** [comment]
pretty cool! thanks
