### ISSUE TITLE
[Bug?] this.thread.z can be off by 1 with small 3d arrays

### ISSUE THREAD

**Issue by saadtazi** [gpujs/gpu.js#251]
While writing some tests, I found the following:

```const gpu = new GPU();

const k = gpu.createKernel(function () {
  return this.thread.z;
}).setOutput([5, 25, 4]);

console.log(k());
```
Notice that the first number in the 2nd row is `0` instead of `1`.

This seems to happen with small array, and making the `x` dimension a even number "fixes" the issue.

I am pretty new to GPU calculation, so I probably missed some important rule ("dimensions should match this criteria..."), so feel free to close if it is expected behaviour.

http://jsbin.com/diwemoq/edit

Note: I am using gpu.js to run calculation on small arrays... I found this issue while writing some simple tests...

**Comment by robertleeplummerjr** [comment]
@fuzzie360 we are going to need your help here bud

**Comment by saadtazi** [comment]
Looks like it is related to https://github.com/gpujs/gpu.js/issues/241

**Comment by robertleeplummerjr** [comment]
I believe this may have been resolved in https://github.com/gpujs/gpu.js/releases/tag/1.4.8

Can you check the latest?

**Comment by robertleeplummerjr** [comment]
Closing, will reopen if issue persists.
