### ISSUE TITLE
Trying to use a MD5 hash function impl with this to hash large arrays of strings (just as a Hello World project for this lib)

### ISSUE THREAD

**Issue by lukas2005** [gpujs/gpu.js#253]
Hello i am trying to use this lib with this md5 implementation: http://pajhome.org.uk/crypt/md5/md5.html
but i'm getting this error: `Non-numeric literal not supported : 0123456789ABCDEF`
How would i get around this and why are non-numeric literals not supported?

EDIT:

Code:
```js
let gpu = new GPU();

function md5Array(array) {
	return hex_md5(array[this.thread.x]);
}

function arrayHash(toHash, algo) {
	let kernel;
	if (algo == "MD5") {
		gpu.addFunction(hex_md5);
		gpu.addFunction(str2rstr_utf8);
		gpu.addFunction(rstr_md5);
		gpu.addFunction(rstr2hex);
		kernel = gpu.createKernel(md5Array);
	}
	
	kernel.setOutput([toHash.length]);
	
	return kernel(toHash);
}
console.log(arrayHash(["hello"], "MD5"));
```

EDIT2:
Also tried this instead:
```js
let gpu = new GPU();

function md5Array(array) {
	return rstr_md5(str2rstr_utf8(array[this.thread.x]));
}

function arrayHash(toHash, algo) {
	let kernel;
	if (algo == "MD5") {
		//gpu.addFunction(hex_md5);
		gpu.addFunction(str2rstr_utf8);
		gpu.addFunction(rstr_md5);
		//gpu.addFunction(rstr2hex);
		kernel = gpu.createKernel(md5Array);
	}
	
	kernel.setOutput([toHash.length]);
	
	return kernel(toHash);
}
console.log(arrayHash(["hello"], "MD5"));
```
but it gives me `An error occurred compiling the shaders: Shader compilation errors (126, 19): syntax error, unexpected SEMICOLON`

NOTE: i have modified the impl slightly to try to remove the errors
Here is the modified version
https://gist.github.com/lukas2005/e44e4c4fe46663f0de89cc2575a5e0e1

**Comment by lukas2005** [comment]
I have a idea how to fix this: Just go ahead and transfer data from gpu to cpu do this hex converting and then back to gpu if needed

**Comment by perkyguy** [comment]
What are you running? Does it work if you call `rstr_md5(s)` on your string?

**Comment by lukas2005** [comment]
yes

**Comment by cuperus** [comment]
Did you ever get this working? Would be appreciated
