### ISSUE TITLE
Possible to return a normal array?

### ISSUE THREAD

**Issue by codingCasually** [gpujs/gpu.js#257]
Many of the regular array methods don't work with typed arrays, here's my list of tests so far:

.unshift() - type error
.shift() - type error
.pop() - type error
.push() - type error
.splice() - type error
.concat() - type error
.reduce() - type error
.toString() - works
.slice() - works
.sort() - works
.indexOf(x) - works
.lastIndexOf(x) - works
.length - works
arrayName[x] - works
.join('*') - works
Array.isArray(arrayName) - returns false

These are just the ones I've tested. More array methods can be found here:
https://www.w3schools.com/jsref/jsref_obj_array.asp

Is it possible to return a normal array using gpu.js as it is currently, or if not, to add a .setArrayTypeNormal(true) or similar? In my current tests I'm only working with integers, as do several of the docs examples so it may be a common problem.

#184 mentions .setFloatOutput(true) doesn't return a typed array so I tried that but for me it seems to.

#36 may also be partially related to this (depending on application)?

Source: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Typed_arrays

Quoted from above source: "However, typed arrays are not to be confused with normal arrays, as calling Array.isArray() on a typed array returns false. Moreover, not all methods available for normal arrays are supported by typed arrays (e.g. push and pop)."

**Comment by codingCasually** [comment]
I was looking more at the array methods list mentioned above at:
https://www.w3schools.com/jsref/jsref_obj_array.asp

I noticed the Array.from() method

"The Array.from() method returns an Array object from any object with a length property or an iterable object."

I tried that on the gpu.js returned array. This creates a normal array from the returned typed array which the previous methods mentioned above that gave type errors now work with :)

**Comment by robertleeplummerjr** [comment]
nice find, ty for both the suggestion and the feedback
