### ISSUE TITLE
Cannot compile kernelMap example - 'get' : no matching overloaded function found

### ISSUE THREAD

**Issue by bartosz-m** [gpujs/gpu.js#258]
Hi, I'm trying kerneMap feature based on example provided in [docs](https://github.com/gpujs/gpu.js#object-outputs) but without success. On both my machines I'm getting same error:  
 `An error occurred compiling the shaders: ERROR: 0:138: 'get' : no matching overloaded function found`  

Single kernels and combined kernels (`gpu.combineKernels`) run without problems. 

I've tested on:
* `gpu.js` version 1.0.0
* browsers: firefox, chrome
* os: Ubuntu 16.04
* gpu: radeons R9 270 and R7 M265

Minimal code to reproduce:

```javascript
const assert = require('assert')
const GPU = require('gpu.js')

const gpu = new GPU()

const size = 4; // keeping it small for testing
const a = new Float32Array(size)
const b = new Float32Array(size)
const c = new Float32Array(size)

for (let i = 0; i < size; ++i) {
    a[i] = 0
    b[i] = i
    c[i] = 2
}

const megaKernel = gpu.createKernelMap([
  function add(a, b) {
    return a[this.thread.x] + b[this.thread.x];
  },
  function multiply(a, b) {
    return a[this.thread.x] * b[this.thread.x];
  }
], function(a, b, c) {
	return multiply(add(a, b), c);
});
megaKernel.setOutput([size])
megaKernel(a, b, c);

assert.deepEqual([0,2,4,6])
```

stack trace:
```
Uncaught Error: Error compiling fragment shader
    at WebGLKernel.build (kernel.js:203)
    at WebGLKernel.run (kernel.js:285)
    at shortcut (kernel-run-shortcut.js:7)
    at Object.<anonymous> (kernel-test.js:28)
```
**Update**
After further investigation I've found what causes problem:
main function of generated kernel looks like this
```glsl
void kernel() {
    kernelResult = multiply(add(user_a, user_b), user_c);return;
}
```

`add` function looks ok to me but `multiply` does not, because its threating result of `add` as user provided input:
```glsl
float multiply(float user_a, sampler2D user_b) {
    multiplyResult = (
        /* --> this line generates error */ get(user_a, vec2(user_aSize[0],user_aSize[1]), vec3(user_aDim[0],user_aDim[1],user_aDim[2]), threadId.x)
        * get(user_c, vec2(user_cSize[0],user_cSize[1]), vec3(user_cDim[0],user_cDim[1],user_cDim[2]), threadId.x)
    );
    return multiplyResult;
}
```

I'm new to gpu.js but I suspect that it should look like this

```glsl
float multiply(float user_a, sampler2D user_b) {
    multiplyResult = (
        user_a  * get(user_c, vec2(user_cSize[0],user_cSize[1]), vec3(user_cDim[0],user_cDim[1],user_cDim[2]), threadId.x)
    );
    return multiplyResult;
}
```

**Comment by robertleeplummerjr** [comment]
If you run this  using `new GPU({ mode: 'cpu' })` you'll get this:
```
[
  NaN,
  NaN,
  NaN,
  NaN
]
```

The reason is twofold:
first (which looks innocent enough), note `add` returns a float/number:
```
return multiply(add(a, b), c);`
```

second multiply is expecting two array, yet will only ever be given a float and an array:
```
function multiply(a, b) {
    return a[this.thread.x] * b[this.thread.x];
  }
```

In short: You are telling mutliply's `a` argument to be two different things.


Try this:
```
const gpu = new GPU({ mode });
const megaKernel = gpu.createKernelMap([
  function add(a, b) {
    return a + b;
  },
  function multiply(a, b) {
    return a * b;
  }
], function(a, b, c) {
  return multiply(add(a[this.thread.x], b[this.thread.x]), c[this.thread.x]);
});
```

**Comment by robertleeplummerjr** [comment]
also @bartosz-m ty for such a detailed issue, helped me reproduce in very short proximity!

**Comment by bartosz-m** [comment]
Ok, I understand what you are saying, and why that didn't worked, but that examples I took **directly** from  gpu.js documentation [here](https://github.com/gpujs/gpu.js#create-kernel-map). So any new person like me who don't know yet how gpu.js works will made that same mistake.

**Comment by robertleeplummerjr** [comment]
@bartosz-m, you rock.  Corrected: https://github.com/gpujs/gpu.js/commit/26479a161002bc23e6ddc1457038b3297d696754
