### ISSUE TITLE
Math.atan2 is not woking

### ISSUE THREAD

**Issue by rveciana** [gpujs/gpu.js#259]
The function appears in the list of *Supported Math functions*, but it seems to fail, returning NaN values. The Math.atan function works properly.

There is a working example here: https://beta.observablehq.com/@rveciana/math-atan2-function-bug-in-gpu-js

**Comment by rveciana** [comment]
Just add that the NaN appears only when using CPU. If GPU is used, an error message appears:
`Error: Error compiling fragment shader`

**Comment by rveciana** [comment]
Solved. glsl atan2 is spelled atan(x,y). So atan is with one argument and atan2 with two.
The only problem is that with the cpu mode the behaviour is as in regular JavaScript, so this ahs to be taken in account.

**Comment by robertleeplummerjr** [comment]
We should provide a compatibility layer for this.  Going to reopen and evaluate soon.

**Comment by robertleeplummerjr** [comment]
![](https://media.giphy.com/media/BnO97P2DFLPB6/giphy.gif)

**Comment by robertleeplummerjr** [comment]
ty for finding, you should find it has been resolved.
