### ISSUE TITLE
Canvas alpha value is not used whan running with GPU

### ISSUE THREAD

**Issue by rveciana** [gpujs/gpu.js#260]
The alpha values are not used, so there is no transparency when *useGraphical* is set to true. This code should return a semi-transparent image:

```
render = gpu.createKernel(function(x) {
    this.color(this.thread.x/500, this.thread.y/500, 0.5 0.5);
})
  .setOutput([500, 500])
  .setGraphical(true)
```
When using the CPU instead of GPU, everything works properly. An interactive example can be found here:

https://beta.observablehq.com/@rveciana/gpu-js-problems-with-alpha-values-when-using-gpu

**Comment by robertleeplummerjr** [comment]
those observables are so cool

I'll try and look at this later today.

**Comment by robertleeplummerjr** [comment]
Was reading here, it seems that webgl doesn't' directly handle alpha.  The workaround is to use:
```js
const canvas = document.getElementById('canvas');
  const gl =  canvas.getContext('webgl');
  const gpu = new GPU({
    canvas,
    webGl: gl
  });
  gl.enable(gl.BLEND);
  gl.blendFunc(gl.SRC_ALPHA, gl.ONE_MINUS_SRC_ALPHA);
  const render = gpu.createKernel(function() {
    this.color(this.thread.x / 500, this.thread.y / 500, 0.5, 0.5);
  })
    .setDebug(true)
    .setOutput([500, 500])
    .setGraphical(true);
```

**Comment by robertleeplummerjr** [comment]
We could probably detect if color is being called with four arguments, and add this into the compiler but seems a little heavy for a gpgpu.  Any other thoughts?

**Comment by rveciana** [comment]
The result is a bit weird!
https://beta.observablehq.com/@rveciana/gpu-js-problems-with-alpha-values-when-using-gpu-2

I'll take a look to understand everything better, I'm really new to this.
And yes, I love ObservableHQ too, it's really nice for many things, including reporting bugs.

**Comment by robertleeplummerjr** [comment]
I think possibly playing with: `gl.blendFunc(gl.SRC_ALPHA, gl.ONE_MINUS_SRC_ALPHA);` will give us the droids we are looking for

**Comment by rveciana** [comment]
Changing your code to 
```
const canvas = DOM.canvas(500, 500);
  const gl = canvas.getContext('webgl', {premultipliedAlpha: false});
  
  const gpu = new GPU({
    canvas,
    webGl: gl
  });
  //gl.enable(gl.BLEND);
  //gl.blendFunc(gl.SRC_ALPHA, gl.ONE_MINUS_SRC_ALPHA);
  const krender = gpu.createKernel(function(x) {
    this.color(this.thread.x / 500, this.thread.y / 500, x[0], x[1]);
  })
    .setDebug(true)
    .setOutput([500, 500])
    .setGraphical(true);
```
https://beta.observablehq.com/@rveciana/gpu-js-problems-with-alpha-values-when-using-gpu-3

About adding it into the compiler, I have no idea, but if the issue is well explained in the docs, people will be able to use it, no it's not really a need.

**Comment by robertleeplummerjr** [comment]
nice

**Comment by robertleeplummerjr** [comment]
adding

**Comment by rveciana** [comment]
Perfect, thank you
