### ISSUE TITLE
Pixel manipulations inverted vertically & Visual Demos Suggestion

### ISSUE THREAD

**Issue by codingCasually** [gpujs/gpu.js#265]
#260 Has solved one alpha problem for me where I was setting alpha: true in gpu.js as mentioned in #173.

When using:

`this.color(0, 1, 0, this.thread.x / 1280); `

The expected output was fully transparent (left) to fully opaque (right). The actual output was roughly half transparency to fully opaque. The output is now as expected, @robertleeplummerjr thanks heaps for the new alpha method! 👍 

But when using:

`this.color(0, 1, 0, this.thread.y / 720); `

The output I expected was to be fully transparent at the top (0) and be fully opaque at the bottom (1). While this is easily fixed with CSS transform: scaleY(-1); to flip the canvas vertically, perhaps there is a simple fix for gpu.js to save the extra style code?

It's not just the alpha that is flipped, all pixel manipulations are, as though this.thread.y is decremented instead of incremented as this.thread.x is. Just to clarify, this isn't a result of the new alpha code, the vertical inversion behavior was the same previous to that.

Example output (canvasContainer div background is gray):

![pixelyinversion](https://user-images.githubusercontent.com/6378088/36666206-9e2fbf60-1b35-11e8-9325-6b22b89581b3.png)

Maybe it has to be that way, I don't know, but it's a simple fix should someone else have the same problem, at least for now anyway. While it might seem like no big deal, gpu.js is awesome for pixel manipulations and I'd hazard a guess that when it catches on, a lot more people will use it in this way.

** The Demos Part **

The pixel manipulations are INCREDIBLY!!! fast, _way_ faster than 8 worker threads. I think a lot more people would be able to see the potential of gpu.js if we could create some visual demos with code examples. Most of what I've learned is from a lot of trial and error, not knowing if it was even possible as the documentation only shows how to set the canvas as a solid color. I mention it now as I've seen just how fast this is and it really blows me away :)

Just some examples I've been working on...

![mandelbrot_gpu](https://user-images.githubusercontent.com/6378088/36679986-4bcf809a-1b60-11e8-9b61-3de2a51272d7.png)

**Mandelbrot rendering in FullHD @ 60fps** allows you to explore (pan/zoom) in real-time, provided you keep max iterations fairly low and avoid large black areas. If you've written a Mandelbrot program using the CPU before, even using threads, you'll realize just how much faster this is :) My hardware is i7-2600 and a single GTX 980 Ti as a rough guide. You could do off-screen buffering and only update the new areas as they pan/scroll into view to greatly speed that up for slower hardware. I've not done that yet.

I've uploaded a very simple video demo of this here: https://www.youtube.com/watch?v=QX6Bfy0Lwyc

The video quality isn't the greatest at all but I will probably upload a better one if I have time to work more on that.

As it is currently, it redraws the whole canvas 60 times a second which also allows real-time palette cycling or hue rotating depending on the coloring method chosen. I've only done the palette cycling so far and it's a really neat effect. It just cycles away as you fly around exploring and it's so simple. This could also be drawn at higher frame rates only I don't have the hardware to test that.

**GPU Big Number Library.** The 32-bit precision does let the Mandelbrot rendering down a bit though as the CPU version can zoom twice as deep with 64-bit precision. That said, I've started work on a gpu.js big number library though progress is very slow as I've not written one before, but from what I've worked out so far, gpu.js seems perfect to greatly speed up these calculations. I only have adding big numbers working so far as I've limited time, but the basic concept is there. I started this as big numbers would be required to pass the 64-bit precision limit anyway and allow you to zoom _so_ much deeper. Zooming deeper requires more iterations to maintain details around the black areas so really deep zooms wouldn't be rendered at 60fps, but surely quicker than using the CPU. This Mandelbrot project is what I was working on when I searched for a way to maybe use the gpu and found gpu.js after implementing worker threads and I'd thought they were fast, not so much in comparison :)

**HTML 5 Video manipulations, e.g. gamma correction etc.** While this can already be done in a single thread, there's not much time left per frame for larger videos to do much else from having to copy the video frame to a canvas and then get the pixel data from that before you can start working with it. Gpu.js would allow a lot more to be done with that pixel data per frame and even allow larger videos to be manipulated at 60fps. I've written a simple gamma correction kernal function to test this and it works great on the GPU.

Programming is just a long-term interest for me, I've never done it professionally as my name here is intended to imply. I'm only coding for fun so feel free to do something similar if you wish, I'd love to see it. I'm likely going to be running out of time before I can complete these to the level I had planned any time soon anyway. I'm sharing it briefly here for those who haven't tried, or like myself, weren't aware of pixel manipulations with gpu.js, more just to let enthusiasts like myself know it's totally possible (not that obvious in the docs) and _so_ fast! 

These are just a few ideas and none of this is intended to show-off my projects at all. It's more intended to show just some of the capabilities of gpu.js and to share ideas as I'm sure others would write far better demos than I could.

As far as a demo would go, something like draw a frame using a single thread, using 8 worker threads, then just gpu.js really starts to show the potential. That's the process I went through and while I knew if I could get it to work on the GPU it would be faster, the speed increase was so far beyond any expectations I'd had :) It is only a suggestion, others may be more interested in the non-visual use cases but as a rough guide, visual demos I think would demonstrate the incredible speed increase and potential of JavaScript on the GPU vs CPU to a wider audience. Anyway, just putting it out there.

Thanks _so_ much to the creators and contributors of gpu.js for this awesome library!!!

**Comment by codingCasually** [comment]
Re the visual demos, I'm guessing the best way would be for me to learn how to use GitHub properly. As my name here suggests, I've never programmed professionally, it's just been a long-term interest so forgive my noob-ness :) The other simple option is to create a few YouTube videos though not sure how well the 60fps capture will work while maxing the GPU. Either way, I'll be sure to mention and link to the gpu.js project, but are there any other requirements I should be aware of?

**Comment by robertleeplummerjr** [comment]
Fantastic!  Do you have a link to the Mandelbrot set so we can link it and play around?

**Comment by codingCasually** [comment]
The gpu.js version was written from scratch for testing so it's not really presentable for an online version. I was planning to add it to my original CPU version which is far more presentable but wasn't written with incredible speed in mind :) It works more like a scan-line renderer as it's so much slower. There's a lot of design considerations in combining both versions, the coding is the easy part. So it will require far more time than I currently have to spend on it unfortunately.

I'll have a look at tidying up the GPU version, though it will be a far cry from what it could be. It may at least serve as a good starting point for someone to take it much further.

**Comment by SuperheroicCoding** [comment]
I used gpu.js for some parts of the application. 
Currently working on reaction diffusion with gpu.js. But I have some minification problems, that I hope to fix soon. It's some orders faster than CPU rendering.

Check this out:
https://superheroiccoding.github.io/AngularExamples/
https://github.com/SuperheroicCoding/AngularExamples

Thx for your incredible work.
Btw.: it was quite hard to make the the outputToTexture feature working. 
I hope for some more examples on that topic.

**Comment by SuperheroicCoding** [comment]
@codingCasually for webGl and CGI in general it's normal that the y direction is like in any mathematical coordinate system. 
I would not consider to make the inverse y direction as standard. Maybe an option would be better.

**Comment by viziionary** [comment]
I'm also getting this inversion and I had to add multiple operations that should be unnecessary and seem a waste. So it would be good to get to the bottom of this. Look at how I'm calculating the index to fix the inversion.

    var pixelateMatrix = gpu.createKernel(function(inputBuffer, width, height, size) {
            var index = size[0] - (((width[0] * 4) - (this.thread.x * 4)) + (this.thread.y * width[0] * 4));
            var rIndex = index;
            var gIndex = index + 1;
            var bIndex = index + 2;
            var r = inputBuffer[rIndex];
            var g = inputBuffer[gIndex];
            var b = inputBuffer[bIndex];
            this.color(r / 255, g / 255, b / 255);
        }).setOutput([width, height]).setGraphical(true);

**Comment by m314** [comment]
@SuperheroicCoding I think that the 2d context has the y-axis going downward: 

>The 2D context represents a flat Cartesian surface whose origin (0,0) is at the top left corner, with the coordinate space having x values increasing when going right, and y values increasing when going down.

https://www.w3.org/TR/2dcontext/

I also support having an option for y-axis direction.

**Comment by robertleeplummerjr** [comment]
Isn't there just a setting that allows for this in webgl?  What does the ideal code look like and what are you having to do to fix it?  @viziionary or @m314, could you assist in a sample?

**Comment by m314** [comment]
@robertleeplummerjr Thank you for your response.  I'm new to webgl.  If there's an easy setting to switch to change the canvas direction, that would be great.

Background: I'm trying to integrate gpu.js with [Leaflet](https://github.com/Leaflet/Leaflet), so I'm taking pixel coordinates from Leaflet's 2d context, shipping the arrays over to gpu.js and doing my calculations and drawings in gpu.js.  I then need to compose gpu.js's canvas with the original 2d context; I'm currently using [`drawImage`](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/drawImage).   I've tried some things in attempt to flip the canvas using `drawImage`, but have not had any luck.

I think the start of my problem is that the incoming y-coordinates are from the 2d context, which is mirrored in y from the webgl context; thus, my gpu.js canvas is rendered upside down (flipped in y).  To account for this, I flip my y-coordinates in gpu.js: ` var ynew = height - yold;` where `height` is the canvas size.  If instead there were some global flip canvas option, I would not have to mirror my y-coordinates.

**Comment by robertleeplummerjr** [comment]
Can you try using the new image input method, and see if this is still the case?

**Comment by m314** [comment]
@robertleeplummerjr I started to look into this, but I was receiving an error with the latest version.  See new ticket #357.

**Comment by robertleeplummerjr** [comment]
Looks like this has been resolved, based of of #357.

Good work everyone!
