### ISSUE TITLE
React/Preact + gpu.js

### ISSUE THREAD

**Issue by caio-ribeiro-pereira** [gpujs/gpu.js#277]
Hi,

Is it possible run React/Preact over gpu.js to improve the client-side render performance?

Thanks

**Comment by robertleeplummerjr** [comment]
This is a pretty open ended question, and the answer would absolutely be "yes", but the amount of work to get there...

some points to consider:
* You are talking about a paradigm change from using the dom and general logic to using gpu for rendering
* Gpu's really only speak math, so you'd have to convert everything to math
* The browsers do a great job dealing with rendering already

**Comment by caio-ribeiro-pereira** [comment]
@robertleeplummerjr so it's possible, but it'll requires a lot of work to convert dom process to math and maybe the performance vs hard working could be not so satisfactory.

I thought it would be a simple and fast job, like put the `render()` function into `gpu.createKernel()` to switch between cpu/gpu render, but it's not, anyway thank you for your answer.

**Comment by robertleeplummerjr** [comment]
I think it is simply more of including a few variables/properties.  There isn't anything truly special about gpu.js just that it is written well to take advantage of existing resources.

**Comment by robertleeplummerjr** [comment]
Node support now exists in v2 rc13, rc14 will be out shortly.  So if the question on this issue is to be replied in a yes or no, the short answer: Yes.

The long answer: Yes, as fallback, but yes as well if headlessgl can be compiled to your system (phone?).
