### ISSUE TITLE
Break and Continue statements are not implemented

### ISSUE THREAD

**Issue by exclamaforte** [gpujs/gpu.js#28]
for example:
```    
var y = gpu.createKernel(function() {
        for (i =0; i <10; i++) {
            break;
        }
    }, opt);
```
It seems the ast_BreakStatement and ast_ContinueStatement functions are not implemented in functionnode_webgl.js

**Comment by fuzzie360** [comment]
Thanks for the report! Our test coverage is simply not good enough presently.
