### ISSUE TITLE
Is complex vector maths even possible ?

### ISSUE THREAD

**Issue by ghost** [gpujs/gpu.js#282]
Hi, I am trying it like this :

		<script>
			const gpu = new GPU();
			
			const complexMultiply = gpu.createKernel(function(a,b) {
				if(this.thread.x == 0)
					return a[0] * b[0] - a[1] * b[1];
				else
					return a[0] * b[1] + a[1] * b[0];
			}).setOutput([2]);
			
			const complexAdd = gpu.createKernel(function(a,b) {
				return a[this.thread.x] + b[this.thread.x];
			}).setOutput([2]);

			const complexZero = gpu.createKernel(function() {
				return 0;
			}).setOutput([2]);

			const complexOne = gpu.createKernel(function() {
				if(this.thread.x == 0)
					return 1;
				else
					return 0;
			}).setOutput([2]);

			const scalarProduct = gpu.createKernel(function(a,b) {
				var sum = complexZero();
				
				for(var i = 0;i < 3;++i) {
					var sum = complexAdd(sum,complexMultiply(a[i],b[i]));
				}

				return sum[this.thread.x];
			}).setOutput([2]);
			
			const complexCreate = gpu.createKernel(function(a,b) {
				if(this.thread.x == 0)
					return a;
				else
					return b;
			}).setOutput([2]);
			
			function kernel(width,height) {
				var a = complexCreate(this.thread.x,this.thread.y);
				var b = complexCreate(1,-1);
				var ab = complexMultiply(a,b);
				
				this.color(1,a[0],b[0]);
			}
			
			const render = gpu.combineKernels(complexCreate,complexMultiply,kernel).setOutput([800,600]).setGraphical(true);
		</script>

**Comment by gammastorm** [comment]
const kernel = gpu.combineKernels(complexCreate,complexMultiply,function(width,height) {
				var a = complexCreate(this.thread.x,this.thread.y);
				var b = complexCreate(1,-1);
				var ab = complexMultiply(a,b);
				
				this.color(1,a[0],b[0]);
			});
			
			const render = gpu.createKernel(kernel).setOutput([800,600]).setGraphical(true);
			console.log(render);
		</script>
	</head>
	<body>
		<div class="xy" id="ab">
		</div>
		
		<script src="../js/jquery-3.2.1.slim.min.js"></script>
		<script src="../js/popper.min.js"></script>
		<script src="../js/bootstrap.min.js"></script>
		
		<script>
			document.getElementById("ab").innerHTML = "";
			document.getElementById("ab").appendChild(render.getCanvas());
			
			render();
		</script>
	</body>





new Float32Array(texSize[0] * texSize[1] * 4);
					result = new Float32Array(texSize[0] * texSize[1] * 4)
gpu.js:1484:4
Unknown ast type : NewExpression 
Object { type: "NewExpression", start: 259, end: 304, loc: {…}, callee: {…}, arguments: […] }
 
Object { calledFunctions: […], calledFunctionsArguments: {…}, initVariables: [], readVariables: [], writeVariables: [], addFunction: addFunction(), isRootKernel: true, isSubKernel: false, parent: null, debug: false, … }
gpu.js:1485:4
Error: WebGL warning: Exceeded 16 live WebGL contexts for this principal, losing the least recently used one.
gpu.js:4196:16
Error: WebGL warning: enableVertexAttribArray: -1 is not a valid `index`. This value probably comes from a getAttribLocation() call, where this return value -1 means that the passed name didn't correspond to an active attribute in the specified program.
gpu.js:2959:4
Error: WebGL warning: vertexAttribPointer: -1 is not a valid `index`. This value probably comes from a getAttribLocation() call, where this return value -1 means that the passed name didn't correspond to an active attribute in the specified program.
gpu.js:2960:4
uncaught exception: Unknown ast type : NewExpression

**Comment by robertleeplummerjr** [comment]
As of v2 rc13, they are, just use `[]` as your array declarator, not `new Float32Array()`.  Internally they are currently all `new Float32Array()` or unsigned, if single precision isn't available.
