### ISSUE TITLE
Implementing blur doesn't really enhance performance

### ISSUE THREAD

**Issue by McOmghall** [gpujs/gpu.js#285]
I'm trying to achieve a blur-like effect on my 2D data, where data in a point is an average of the surrounding points to a certain distance, but using this library doesn't seem to accelerate computing, can you offer some guidelines to achieve this?

Note I tried both using the loops you see below and unrolling the loop to some constants, but the result is the same.

```
// Aux function to load data in texture in GPU
  const texturify = gpu.createKernel(function texturify (map) {
    return map[this.thread.x][this.thread.y]
  }).setOutput(options.size)
    .setOutputToTexture(true)

// Actually apply blur
  const blurMap = gpu.createKernel(function blurMap (map) {
    var rval = 0
    let blur = this.constants.blur
    for (let i = -blur; i <= blur; i++) {
      for (let j = -blur; j <= blur; j++) {
        rval += map[this.thread.x + i][this.thread.y + j]
      }
    }
    return rval / this.constants.blurSquaresAmount
  }).setOutput(options.size)
    .setConstants({
      blur: Math.floor(Math.abs(options.softness)),
      blurSquaresAmount: (2 * Math.floor(Math.abs(options.softness)) + 1) * (2 * Math.floor(Math.abs(options.softness)) + 1)
    })

// And calling with
  this.heightMap =  blurMap(texturify(completeMatrix))
```

**Comment by robertleeplummerjr** [comment]
Did you try using `graphical`?  I think that will skip a bunch of work.  It sounds like you are going from cpu, to gpu, to cpu, to gpu.  Where we want to go from cpu to gpu, once.

**Comment by nickhingston** [comment]
Yep, thats exactly what is happening. please see https://github.com/gpujs/gpu.js#create-kernel-map

I have found the biggest bottleneck to be memory transfer time, so keeping it in the GPU RAM will have a huge boost in performance.

Closing issue...
