### ISSUE TITLE
Keeping kernel input in GPU memory?

### ISSUE THREAD

**Issue by sroboubi** [gpujs/gpu.js#288]
I'm trying to create a series of Kernels that takes a large input array plus some small parameters and calculate an output: (largeArrayInput, p1, p2..., pn) -> (largeArrayOutput)
The output will eventually need to become a canvas imageData object.
The largeArrayInput will not change often, but the parameters (p1, p2,...) will be changing. I was hoping to somehow leave largeArrayInput in GPU memory and only update the parameters instead of loading everything each time I need to recompute with updated parameters. I suspect I need to specify outputToTexture, but I'm not sure how to then use this texture in addition to other parameters in subsequent kernel calls? Is there a good way to do this? Any hints/example code that I could look at?

**Comment by sroboubi** [comment]
Also, when I use outputToTexture, how can I display this texture on a canvas and/or get the pixel values out of it?

**Comment by robertleeplummerjr** [comment]
For something you'd like to be transferred to the gpu once, simply use something like this:
```js
const importAsTexture = gpu.createKernel(function(value) {
    return value[this.thread.y][this.thread.x];
})
  .setOutput([512, 512])
  .setOutputToTexture(true);

const texture = importAsTexture(input);
```


Speaking off the cuff, this doesn't exist, but looks very attractive and useful: `const texture = GPU.Texture.from(value, x, y, z)`

**Comment by sroboubi** [comment]
OK, but after I have a texture loaded and then want to output some results to a canvas, it seems like the texture output size is affecting the canvas size (maybe this should be raised as a separate issue). You can see this with the following code:

        var size = 200;
        var reduce = 20;
        var input = new Uint16Array(size*size);
        for (var i = 0; i < input.length; i++) {input[i] = i;}

        var gpu = new GPU();

        var load = gpu.createKernel(function(input)
        {
            return input[this.thread.x];
        }).setOutput([input.length]).setOutputToTexture(true);

        var render = gpu.createKernel(function(input, max)
        {
            this.color(input[this.thread.x*this.thread.y]/max, 0, 0, 1);
        }).setOutput([size-reduce, size-reduce]).setGraphical(true);

        console.log(input);
        var tex = load(input);
        console.log(tex.toArray(gpu));
        render(tex, size*size);
        const canvas = render.getCanvas();
        document.body.appendChild(canvas);

If you change `reduce` to 0 you will get the expected result, but if it is a non-zero value you would expect the output canvas size to be `size-reduce`, however it seems to still be `size`.

**Comment by robertleeplummerjr** [comment]
Can you put together a jsfiddle with this showing your issue?

**Comment by sroboubi** [comment]
https://jsfiddle.net/2vgw9syx
vs 
https://jsfiddle.net/2vgw9syx/1

Note the difference is reduce = 0 vs 20.

**Comment by sroboubi** [comment]
Just confirming that this is still an issue with 1.8.1. Could you just confirm that you are seeing the behavior that I see and that you agree it is a bug? Perhaps it would be better if I create this as a separate issue? If it is something complicated or hard to fix then please let me know so I can consider workarounds or other options... Thanks.

**Comment by robertleeplummerjr** [comment]
This has been resolved now as of v2 rc13, bot more-so in https://github.com/gpujs/gpu.js/tree/rc-14-cleanup as well the name of the setting has changed from `outputToTexture: true` to `pipeline: true`.  You need to simply call `result.toArray()` from the texture result from calling your kernel to get the contents read back to the CPU.
