### ISSUE TITLE
precompiled GPU.JS code.

### ISSUE THREAD

**Issue by Steve--W** [gpujs/gpu.js#289]
In your src it says there is a minimalistic version of GPU.js used to run precompiled GPU.JS code. 

Do you have any examples of how to use this functionality?  I think that it is exactly what I need.

Also it says  For the kernel object format see : <kernelObj-format> Can you tell me where to find this?

Thanks for your help. Awesome project!

Steve

**Comment by robertleeplummerjr** [comment]
Fixed here: https://github.com/gpujs/gpu.js/commit/96db4023313ad59d85ec3d795a711f4ee685b3ae
