### ISSUE TITLE
Add support for image inputs

### ISSUE THREAD

**Issue by robertleeplummerjr** [gpujs/gpu.js#296]
Proposed api:

Specific use case:
```js
kernel(imageElement);
```

```js
const gpu = new GPU();
const kernel = gpu.createKernel(function(v) {
  return v[this.thread.y][this.thread.x];
}, {
  output: [512, 512]
});
const img = new Image();
img.src = 'stacks/axial1.jpg';
img.onload = function() {
  kernel(this);
};
```

Node side needs to be thought out.

**Comment by robertleeplummerjr** [comment]
Initial tests are promising: ![Uploading Screen Shot 2018-05-26 at 3.48.24 PM.png…]()

**Comment by robertleeplummerjr** [comment]
Here is the MVP: https://github.com/gpujs/gpu.js/blob/9a914e2e8552f0ebb861c1b1bdd5575de9b6c870/test/src/features/image.js#L35

**Comment by robertleeplummerjr** [comment]
Related:
* https://www.khronos.org/webgl/public-mailing-list/public_webgl/1212/msg00009.php
* https://www.opengl.org/sdk/docs/tutorials/ClockworkCoders/texturing.php

Ended up using `gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL, true);` to flip images.

**Comment by robertleeplummerjr** [comment]
Made some really good progress today for generalizing the image upload to the gpu, cpu to come next.  The visuals are slightly off, because they are still somewhat distorted in how they pack/unpack (they really don't need to because we aren't packing and unpacking, as we do with floating point number arrays).  The image is slightly distorted, but that is just simple math that I can work out, and isn't complex.
  
In short, the compiler and parser has been adjusted to work with the simplified input of a single image, where an array of images will be the next step and will be much easier, because they are simply adding another dimension.  This is what input/output currently looks like:

<img width="560" alt="screen shot 2018-06-02 at 3 19 08 pm" src="https://user-images.githubusercontent.com/679099/40880124-56ec9e36-6679-11e8-8b38-2c211d465201.png">

(input on left, output on right)

for the kernel looking like:

```js
var imageKernel = gpu.createKernel(function(image) {
  const pixel = image[this.thread.y][this.thread.x];
  this.color(pixel[0], pixel[1], pixel[2], pixel[3]);
}, {
  output : [276, 183],
  graphical: true
});
```

Good things!  I optimistically imagine by next week we'll have something, but we'll see.

**Comment by robertleeplummerjr** [comment]
Sometimes software development doesn't go as good as you'd hope.  Other times it goes way better.

**Comment by mauriceackel** [comment]
@robertleeplummerjr Is this feature also supported in CPU mode? When I pass an image element and try to access it like `img[y][x]` I always get the error: `TypeError: Cannot read property '0' of undefined`. Do you have any advice?
