### ISSUE TITLE
output to texture does not create a new texture for each call

### ISSUE THREAD

**Issue by sroboubi** [gpujs/gpu.js#298]
var gpu = new GPU();

        var makeSingleValTexture = gpu.createKernel(function(val)
        {
            return val;
        }).setOutput([1]).setOutputToTexture(true);

        var t3 = makeSingleValTexture(3);
        var t7 = makeSingleValTexture(7);

        console.log(t3.toArray(gpu));
        console.log(t7.toArray(gpu));

I would expect t3 to be [3] and t7 to be [7], but they are both [7]. I suspect the kernel is binding the output to only one texture and that overwrites t3 when we call it the second time. Is this a bug? Should it create a new texture to output for each call? If not then what is the correct way to do this?

**Comment by robertleeplummerjr** [comment]
`return val;`

This line is wrong, it should be at the very least:
`return val[this.thread.x];`

**Comment by sroboubi** [comment]
But I'm passing in a number, not an array: https://github.com/gpujs/gpu.js#accepting-input
Anyway, we can change the input to an array and refer to it the way you suggest. We'll get the same results:

        var gpu = new GPU();

        var makeSingleValTexture = gpu.createKernel(function(val)
        {
            return val[this.thread.x];
        }).setOutput([1]).setOutputToTexture(true);

        var t3 = makeSingleValTexture([3]);
        var t7 = makeSingleValTexture([7]);

        console.log(t3.toArray(gpu));
        console.log(t7.toArray(gpu));

**Comment by robertleeplummerjr** [comment]
oh ok, very cool.  Try this:
```js

var gpu = new GPU();

var makeSingleValTexture = gpu.createKernel(function(val)
{
    return val[this.thread.x];
}).setOutput([1]).setOutputToTexture(true);

var t3 = makeSingleValTexture([3]).toArray(gpu);
var t7 = makeSingleValTexture([7]).toArray(gpu);

console.log(t3);
console.log(t7);
```

**Comment by sroboubi** [comment]
When you call toArray() you're just copying the content of the texture to an array, however the texture is still modified in your next kernel call. Normally calling a function a second time does not change the value of the first call. For example if I have a makeTexture(inputArray) function to create a texture from an array, I would just assume that if I call it twice to get two different textures that it would work. But right now the second call would overwrite the texture returned from the first call... so I have to make a separate kernel function for each texture that I want to make. If this is the intended behavior then that's fine, but maybe it should be documented in the section about outputToTexture().

**Comment by robertleeplummerjr** [comment]
If you need to create an immutable array each time you call the kernel, use the option `outputImmutable: true` when creating a new kernel:
```js
const gpu = new GPU();
const kernel = gpu.createKernel(function() {
  // do stuff
}, {
  outputImmutable: true,
  outputToTexture: true
});
```

This causes a more costly, but often times needed, creation of a new texture on each call.

**Comment by sroboubi** [comment]
outputImmutable works as you suggested. Thanks.

**Comment by robertleeplummerjr** [comment]
No problem!
