### ISSUE TITLE
image is rendered top-down (y inverted) when switching from gpu to cpu

### ISSUE THREAD

**Issue by Fil** [gpujs/gpu.js#308]
Example here: https://beta.observablehq.com/d/b70d084526a1a764

if using cpu the Earth is flipped on the y-axis; also, background becomes white (black on gpu)

cpu
<img width="636" alt="cpu" src="https://user-images.githubusercontent.com/7001/41177278-be99dbfe-6b63-11e8-8026-3e3b6f8592e6.png">

gpu
<img width="656" alt="gpu" src="https://user-images.githubusercontent.com/7001/41177279-bec6473e-6b63-11e8-9a74-88e79a0bb065.png">

**Comment by robertleeplummerjr** [comment]
Potential fix here: https://jsfiddle.net/robertleeplummerjr/cgy3rsz9/2/
