### ISSUE TITLE
Variable max iterations for loops inside custom functions

### ISSUE THREAD

**Issue by sroboubi** [gpujs/gpu.js#311]
The documentation seems to indicate that loops in the kernel function must use a fixed size or a dynamic size via a global constant: https://github.com/gpujs/gpu.js#dynamic-sized-via-constants
I want to have a loop inside a custom function (https://github.com/gpujs/gpu.js#adding-custom-functions-directly-to-kernel) and I want the loop to have a different size each time I call the function. Each call can use a constant value, but it must be a different constant value.
For example the first time I call it I want the loop size to be this.constants.maxA and the second time this.constants.maxB. Is there any way to do this?

**Comment by nickhingston** [comment]
it depends on wether this loop changes the number of output items.  This needs to be a constant (though you can reset it by calling setOutput again)

for example, say you wanted to do a 'to the power of' operation on an input array:

```
const gpu = new GPU()
const pow = gpu.createKernel(function(data, n) {
	var val = 1;
	for (var i = 0; i < n; i++) {
		val = val * data[this.thread.x];
	}
	return val;
})
	.setOutput([9])

pow([1,2,3,4,5,6,7,8,9], 2);
```

would produce:
`[1, 4, 9, 16, 25, 36, 49, 64, 81]`

**Comment by sroboubi** [comment]
I was getting the wrong results from my kernel and from the documentation and the warning I was getting "Warning: loopMaxIterations is not set! Using default of 1000 which may result in unintended behavior.", I assumed I needed my loops to have a constant number of iterations. Now I see that I can use setLoopMaxIterations to set my maximum to a large enough number so my loops work as expected. Note that I had to dig into the code to see what loopMaxIterations was and how to set it (it is mentioned as a param in the documentation once, but it doesn't say what it does or how/why to use it). Thanks.

**Comment by robertleeplummerjr** [comment]
What would be suitable verbiage you think?

**Comment by robertleeplummerjr** [comment]
@sroboubi does https://github.com/gpujs/gpu.js/pull/342 resolve this reasonably?

**Comment by sroboubi** [comment]
Yes thanks.

**Comment by SnippyValson** [comment]
Whenever I try to use a loop I'm getting, unhandled type "NewExpression". I'm trying it on codesandbox.io and my broswer is Google Chrome.

**Comment by midnight-dev** [comment]
@SnippyValson Could you post a snippet of the problematic code or a link to a code sandbox that demonstrates this?

**Comment by SnippyValson** [comment]
https://codesandbox.io/s/cellular-automata-mo4b0

**Comment by SnippyValson** [comment]
https://codesandbox.io/s/loving-stonebraker-7zdym?file=/src/index.js

The sample code.
