### ISSUE TITLE
Multiple calls to custom function produces invalid results

### ISSUE THREAD

**Issue by sroboubi** [gpujs/gpu.js#313]
There seems to be something wrong with how custom functions are working, and I've tried to reduce it as much as possible to a tiny example:
https://jsfiddle.net/zdLgkw2u/5/

Note that the result should be 8, but we get 6. If you switch the commented out line in the kernel you'll get the expected result.

I hope the explanation/solution to what you see here would resolve all the issues with custom functions that I'm seeing.

**Comment by robertleeplummerjr** [comment]
Trying to debug this.  If I turn on debug (`.setDebug(true)`), I can pull out the kernel as a string and when I compare them I get:

<img width="1440" alt="screen shot 2018-06-10 at 10 48 04 pm" src="https://user-images.githubusercontent.com/679099/41210582-ab843534-6d00-11e8-9c47-2f5703c4f883.png">
(left is working, right is broken)

There is something up with the value tracing that is causing it to fail.  This should be a fairly easy fix.  I'll take a look in the morning.
