### ISSUE TITLE
this.constants is undefined (CPU mode)

### ISSUE THREAD

**Issue by picoCreator** [gpujs/gpu.js#32]
As by @staceytay reported in : https://github.com/gpujs/gpu.js/issues/31

**Comment by fuzzie360** [comment]
Won't fix. "this" refers to the current function in JavaScript and using "this" in an internal function does what it says on the tin. "Redefining" JavaScript rules, though technically possible, is out of the question.

Possible replacement for constant support:

* Use kernel arguments as a means to declare constants
* Use ALL_CAPS variables to indicate constant variables

In the long run, we probably might need to rethink how we use "this". Probably should consider adding "var self = this;" support in the kernel function or finding an alternative to "this".
