### ISSUE TITLE
GPU,.js blocks the main thread?

### ISSUE THREAD

**Issue by isaacguerreir** [gpujs/gpu.js#327]
I'm looking your code, and if I understand you're using WebGL to run this array/matrix structures using the GPU.  WebGL uses the main thread by default (you can actually off the main thread using offscreencanvas).

My question is:GPU.js blocks the main thread?

**Comment by robertleeplummerjr** [comment]
It depends on how you use it.  When you request values back from the GPU or are sending values to it, I believe the answer is yes.  For the most part, GPU.js is a wrapper and translator for GPU code, of which includes the canvas and webgl architectures, both of which are synchronous, and block the main thread.  OpenCL will be added soon, and it is a similar story there.
