### ISSUE TITLE
Array Support

### ISSUE THREAD

**Issue by sawman** [gpujs/gpu.js#33]
We want to support fix sized arrays. To ensure that, we check for modifications to arrays beyond initialization. Not very JS-like, but we need to either initialise or annotate the array var declaration for the type inference to work

**Comment by robertleeplummerjr** [comment]
Support is now in for whatever size of array you need, simply do:

```js
var kernel = gpu.createKernel(function() {
  for (var i = 0; i < size; i++) {}
}, { constants: { size: 1000000 } });
```
