### ISSUE TITLE
Interest in typescript version of this lib?

### ISSUE THREAD

**Issue by robertleeplummerjr** [gpujs/gpu.js#331]
Just thought I'd ask.

**Comment by Jayx239** [comment]
I'm very interested in this. Do you have any plans on doing this? It would help me out a lot.

**Comment by robertleeplummerjr** [comment]
I think the biggest issue would be translation and how that happens.  I'd imagine since typescript generates javascript we'd simply need to ensure the transpiler handles the generated javascript ok, which for the most part it does now.  I suppose in that case, the biggest hurdle would simply be to have typescript definitions of the library.

**Comment by jacobbogers** [comment]
you have my upvote

**Comment by robertleeplummerjr** [comment]
My first inclination was to be skeptical with use of `this`, but lo and behold: https://github.com/Microsoft/TypeScript/issues/229

Which lead me to: https://www.typescriptlang.org/docs/handbook/functions.html (search for "this:").  Which lead me to do this:


```js
class It {
    public value = "100%";
}

function kernel(this: It, test: string) {
    return test + " " + this.value + " complete";
}

const it = new It();
console.log(kernel.call(it, "skeptical"));
console.log("Hi mom!");```

outputs:

```js
skeptical 100% complete
Hi mom!
```

I don't believe there is much holding this back other than the typeing files.

**Comment by robertleeplummerjr** [comment]
Tested here: https://agentcooper.github.io/typescript-play/#code/MYGwhgzhAECSAu0DeAoa7oAcCuAjEAlsNAG5gjYCm0AvNAEQCMADMwKT0DcKAviigDNsAO2DwCAe2HQA1pQBOwyiAAU8ABYEIALjjwANNHiUI8XafkFhAcwCUyNBnmV42RUZOIA1A18+NWgB0ZBTUPvTQwBIAtpggLpRcvPxRwqbQBIh0SgDueiq23KkQEvGBIBLWKnKKyoHA5KqZhvQQcpjiDSD0toUoxaWU5ZUq9AASBNDRMQCEPZxAA

**Comment by Smilebags** [comment]
I'm currently looking at using GPU.js in a TypeScript based project and would be very interested in having at least type definitions made for your public API, though I feel a library like this would also benefit significantly from using TypeScript throughout.

If it is of interest, I might be able to help out somewhat with the migration.

**Comment by robertleeplummerjr** [comment]
V2, rc,2, is like 90% done with the typings so we can use typescript.  If you'd like to take a look, it is in the src folder.

**Comment by Smilebags** [comment]
I'm looking forward to the release.

What is your compiler setup for TypeScript? I'm getting errors about acorn not being under rootDir (which is intentional) so I can't build if including gpu.js. Is there some way to include acorn rather than importing it in the built gpu.js file?

If I force it to build regardless, I end up wit this in the browser after including this in one of my files `import { GPU } from "./gpu.js";`:
`_gpu_js__WEBPACK_IMPORTED_MODULE_2__.GPU is not a constructor`

I'm running a very simple webpack setup which just passes files through ts-loader and into a bundle.

**Comment by robertleeplummerjr** [comment]
Gpu.js shouldn't be built with typescript, but rather includes a typings file.  What that understanding, doesn't still fail?

**Comment by Smilebags** [comment]
I understand Gpu.js isn't built using TypeScript, but when using it in a TypeScript project, it should work smoothly. It is likely something about the build which the TypeScript interpreter can't handle. I'm not familiar enough with all of the pre-ES6 module loaders and bundlers so it is hard to see what isn't working.

It would be great to have an ES6 module version of Gpu.js, I think that's what I'm trying to get at. That way, given a typedef file, and as long as it isn't relying on node module resolution, then the TypeScript compiler shouldn't have any issues with it.

**Comment by Smilebags** [comment]
If I have time next week, I'll take a look at the source and see if it would be a lot of work to get something like what I've proposed happening.

**Comment by robertleeplummerjr** [comment]
Ty for your hard work in looking at this.  The GPU.js v2 should be completely or near converted to es6 style exports & imports, just fyi.

**Comment by robertleeplummerjr** [comment]
typeings file added in v2.  Will be out in a few days.
