### ISSUE TITLE
Looking for hints and/or internal documentation on the inner workings

### ISSUE THREAD

**Issue by jeffsaremi** [gpujs/gpu.js#334]
This is not a bug report or feature request but rather a documentation request.
I am simply amazed by how a matrix multiplication of arbitrary length (or actually any computation) is mapped to shaders and texture operations in WebGL.
Could you provide some guidance/links that could be used along with the source code to help us understand this? 
thanks
Jeff

**Comment by robertleeplummerjr** [comment]
Not all array's are the correct size, but if we oversize them, they can be mapped and truncated: https://github.com/gpujs/gpu.js/blob/cfd3c777d9d8481c5d12eba0d9b28c2a070236cb/src/core/utils.js#L372

**Comment by robertleeplummerjr** [comment]
In other words, a square peg can go in a round hole so long as the hole is larger

😎

**Comment by robertleeplummerjr** [comment]
Does this answer your question?

**Comment by jeffsaremi** [comment]
wow. this is a great start, Robert. Let me go through this and absorb it. If I have more questions I'll follow up.
