### ISSUE TITLE
Gulp fails with the message: Cannot GET /test/html/test-all.html

### ISSUE THREAD

**Issue by jeffsaremi** [gpujs/gpu.js#338]
I just cloned gpu.js and tried to build it using Gulp. I am of course assuming that this is the right tool to build this project.

First off, I was prompted about 20 times on missing modules. I had to to npm install for each one of them. It would be nice if someone added a line or two on what the build process looks like.

Second, right after running gulp I get this. I tried develop and master branches both.

Error shown in the browser: `Cannot GET /test/html/test-all.html`

```
D:\repos\gpu.js>gulp
[09:42:27] Using gulpfile D:\repos\gpu.js\gulpfile.js
[09:42:27] Starting 'minify'...
[09:42:27] Starting 'bsync'...
[09:42:27] Finished 'bsync' after 61 ms
[09:42:28] Finished 'minify' after 1.12 s
[09:42:28] Starting 'default'...
[09:42:28] Finished 'default' after 60 μs
[Browsersync] Access URLs:
 ----------------------------------------------------------
       Local: http://localhost:3000/test/html/test-all.html
    External: http://0.0.0.0:3000/test/html/test-all.html
      Tunnel: https://witty-falcon-26.localtunnel.me
 ----------------------------------------------------------
          UI: http://localhost:3001
 UI External: http://0.0.0.0:3001
 ----------------------------------------------------------
[Browsersync] Serving files from: ./
```

**Comment by robertleeplummerjr** [comment]
Did you `npm i` or `yarn` first?

**Comment by jeffsaremi** [comment]
No i didn't. So now i'm very confused. Do I install this right after getting the source? Does that mean there is no need to build anything?

Running the npm install now gives me this:

```
D:\repos\gpu.js>npm install gpu.js --save
npm ERR! code ENOSELF
npm ERR! Refusing to install package with name "gpu.js" under a package
npm ERR! also called "gpu.js". Did you name your project the same
npm ERR! as the dependency you're installing?
npm ERR!
npm ERR! For more information, see:
npm ERR!     <https://docs.npmjs.com/cli/install#limitations-of-npms-install-algorithm>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\jesaremi\AppData\Roaming\npm-cache\_logs\2018-07-05T16_50_28_559Z-debug.log
```

**Comment by robertleeplummerjr** [comment]
The error message is pretty telling.  The commands (one or the other) I mentioned above were complete, there is no need to put ' gpu.js --save` added.

**Comment by jeffsaremi** [comment]
Still dumbfounded. I can install this but I cannot build it? I guess there was no need for to clone the repo.

**Comment by robertleeplummerjr** [comment]
You are inside gpu.js, installing gpu.js into itself.  Simply go to a command line, and type _exactly_
*`npm i`
*`npm  make`

**Comment by jeffsaremi** [comment]
ok thanks. I gave up the npm route. The link to the pre-packaged file is good enough for me.

**Comment by robertleeplummerjr** [comment]
![](https://media1.giphy.com/media/Dnt2VnWFknFNm/200.gif)
