### ISSUE TITLE
Test case 'failure' - FP accuracy issue

### ISSUE THREAD

**Issue by nickhingston** [gpujs/gpu.js#349]
<img width="472" alt="screen shot 2018-07-23 at 14 54 59" src="https://user-images.githubusercontent.com/866805/43080783-70663b10-8e88-11e8-92db-a51422a75ca9.png">

is encode32 & decode32 working ok?

**Comment by robertleeplummerjr** [comment]
Assuming these are notes for yourself to visit the issue you mentioned to me in PM?

**Comment by nickhingston** [comment]
Correct

**Comment by nickhingston** [comment]
OK, just spent an hour looking at this.  if i change the test divide kernel part from 
```
function divide(v1, v2) {
        return v1 / v2;
      }
```
to:
```
function divide(v1, v2) {
        if (v2 == 3) {
          return v1 / 3;
        }
        return v1 / v2;
      }
```

it passes on my system!!  WTF?!

**Comment by nickhingston** [comment]
problem due to floating point division by 3 and some other primes...

fix basically checks wether divisor and dividend are integers, wether there is any remainder from mod, if so does an integer div operation...
