### ISSUE TITLE
GPU mode code does not have JS-like scoping rules

### ISSUE THREAD

**Issue by sawman** [gpujs/gpu.js#35]
We should implement function level scope for all variables, for more JS-like scoping. What this means is that in codegen we emit all code for variable declarations on top first. This could also mean that we need to decompose all for loops into while loops, because:

func() {
  for (var a = 0...) {}
  for (var a = 0...) {}
}

is now invalid code.

**Comment by picoCreator** [comment]
[as from #31] 

@sawman : My current suggestion would be to actually flag out a warning / exception, as we generate the code from AST. On repeated variable declaration (repeated var declares are a bad bad code readability idea anyway)

This would be an extension of the addFunction script, which already keeps track of function declarations and calling trace (automatically skipping functions that do not get called).

Question would be : do we do a warning, OR an exception? I vote for exception.

**Comment by robertleeplummerjr** [comment]
I vote exception

**Comment by robertleeplummerjr** [comment]
https://github.com/gpujs/gpu.js/commit/3d2da0580948250402ead40c73433f28e50035cf#diff-6418a176bd9201c8fff0b8e2f3c5ff84R463
