### ISSUE TITLE
Problem with the parameters in a GPU added function

### ISSUE THREAD

**Issue by Corrado972** [gpujs/gpu.js#359]
Hello,
in [this](https://jsfiddle.net/Corra72/5u87s4mo/) fiddle, there's the following error:
_An error occurred compiling the shaders: ERROR: 0:184: 'user_c1' : undeclared identifier
ERROR: 0:184: 'user_cC' : undeclared identifier_

The problem is in this function:
```
gpu.addFunction(function clcC(xx, yy) {
	return abs(xx - yy);
});
```

Because the generated GLSL code is:
```
float clcC(float user_xx, float user_yy) {
return abs((user_c1-user_cC));
}
```

And not what I expected:
```
float clcC(float user_xx, float user_yy) {
return abs((user_xx-user_yy));
}
```

I call the function is this way:
`clcC(c1, cC);`

Can you help me please?

**Comment by nickhingston** [comment]
yeah, looks like you have hit a bug in addFunction...will look into when i get some time...

in the mean time change the input params of clcC to c1 & cC and all should work

fixed fiddle:
https://jsfiddle.net/5u87s4mo/631/

**Comment by nickhingston** [comment]
simplified fiddle exhibiting problem for test case:

https://jsfiddle.net/5u87s4mo/650/
