### ISSUE TITLE
Multi-dimensional output is v.slow

### ISSUE THREAD

**Issue by nickhingston** [gpujs/gpu.js#361]
Whilst investigating #360 found that if you have a large multidimensional output, things are much slower.

Huge amount of time spent in utils.js splitArray.

**Comment by nickhingston** [comment]
this performance issue is fixed by changing utils.js split array to
`static splitArray(array, part) {
		const result = [];
		for (let i = 0; i < array.length; i += part) {
			result.push(new Float32Array(array.buffer, i * 4, part));
		}
		return result;
	}`

i.e. not converting the typed array to an untyped array.

This causes a lot of grief in QUnit.assert.deepEqual as all the tests are written with untyped array values...

@robertleeplummerjr I did see some conversation a while ago between yourself and a user about returning untyped arrays.  Can you remember the outcome?

My thoughts are we should always return Float32Arrays from the kernel and it's up to the user to convert if they need to...

**Comment by robertleeplummerjr** [comment]
I think the conversation was probably that we should support them.  I welcome this fix, if the unit tests break, then we'll simply fix them, and likely it'll be repetitive.
