### ISSUE TITLE
Undefined array using Float Texture

### ISSUE THREAD

**Issue by gpellegri** [gpujs/gpu.js#369]
Using Float Texture in a few points in the code an undefined array is used, throwing errors (inputArray)

gl.texImage2D(gl.TEXTURE_2D, 0, gl.RGBA, _size[0], _size[1], 0, gl.RGBA, gl.FLOAT, **inputArray**);

**Comment by gpellegri** [comment]
I'm using GPU 1.8.0 but also the previous version has the same issue

**Comment by robertleeplummerjr** [comment]
Found it.  I'll see if I can get a fix in soon for this.  Ty for finding!

**Comment by robertleeplummerjr** [comment]
Fixed in v2 rc13.  rc14 out in a few days.
