### ISSUE TITLE
No data using output Texture in CPU mode

### ISSUE THREAD

**Issue by gpellegri** [gpujs/gpu.js#370]
In CPU mode using a Texture as Kernel argument no exception is thrown but the output array contains only undefined values.

Is there any way to export the Texture data in CPU mode? Also without using GPU.js

**Comment by gpellegri** [comment]
I've found a Texture class in GPU which exposes a toArray method, could be used to export the Texture data to array?

**Comment by robertleeplummerjr** [comment]
Fixed here: https://github.com/gpujs/gpu.js/commit/20a9ed54c7a0047bfb244643cb6be6a3836491b1
