### ISSUE TITLE
GPU destroy method throw exception

### ISSUE THREAD

**Issue by gpellegri** [gpujs/gpu.js#371]
GPU 1.8.0
Calling the destroy method on a GPU instance an exception is thrown about the Context

This is the line which throw the exception

					if (loseContextExt) {
						**loseContextExt.loseContext();**
					}

**Comment by nickhingston** [comment]
which browser?

**Comment by gpellegri** [comment]
You're right, I forgot some info:
Browser: Chrome V. 69.0.3497.100 (64 bit)
OS: Microsoft Windows 10 Enterprise (x64)

**Comment by robertleeplummerjr** [comment]
Can you reproduce this in a jsfiddle or similar please?

**Comment by robertleeplummerjr** [comment]
This has been resolved in v2 rc 13.  rc 14 will be out in a few days.  Ty for catching.
