### ISSUE TITLE
Wrong Texture buffer size using output Texture and FloatTextures

### ISSUE THREAD

**Issue by gpellegri** [gpujs/gpu.js#372]
GPU 1.8.0
Using output as Texture and FloatTextures a wrong buffer size is allocated which crash in a caller function
The buffer size is managed in dimToTexSize and the problem is at this point (w is four times smaller and the caller create a buffer 4 times smaller, too small to contains the data)

			if (opt.floatTextures && (!output || opt.floatOutput)) {
				**w = numTexels = Math.ceil(numTexels / 4);**
			}

**Comment by robertleeplummerjr** [comment]
Can you reproduce this in a jsfiddle please?

**Comment by robertleeplummerjr** [comment]
I believe this to be resolved in v2, rc 13.  They are now tested much more thoroughly: https://github.com/gpujs/gpu.js/blob/develop/test/internal/backend/web-gl/kernel/addArgument.js#L165.  Closing as it should be resolved.
