### ISSUE TITLE
Exception thrown using some specific sizes of the input array

### ISSUE THREAD

**Issue by gpellegri** [gpujs/gpu.js#373]
GPU 1.8.0
I got crazy trying to figure out why using some input data the GPU was crashing, using an input array of e.g. 440000 items WebGL throw this: 
**INVALID_OPERATION: texImage2D: ArrayBufferView not big enough for request**
and the browser crash.

Using an input array of e.g. 1000000 of items no exception is thrown

Checking the code it seems some specific inputs length (like 440000) generate a size (width and height) which are not "good" for WebGL.
I've tried to solve forcing a "right" size and also gl.pixelStorei(gl.UNPACK_ALIGNMENT, 1); but I've had no good results.

It seems a GL problem which is solved (should be) with GL 2, but I didn't find a good solution. Also due to any GPU exception crash the code and the browser, so a strong solution is needed.

**Comment by robertleeplummerjr** [comment]
Can you reproduce this in a jsfiddle by chance?

**Comment by robertleeplummerjr** [comment]
I believe this is a browser implementation issue, and likely not actionable in GPU.js.  Closing for the time being.
