### ISSUE TITLE
GPU crash using "big" input data

### ISSUE THREAD

**Issue by gpellegri** [gpujs/gpu.js#374]
GPU 1.8.0
I've tried to use GPU.js within my project but after hours trying and trying again i'm going to throw the sponge, it seems GPU is unable to handle arrays of around 1~4mln of items with a bit of kernel logic.

With a simple kernel it works (just 1 if and 2 else), when I use such data with a bigger logic (a few if, for and Math.abs) an exception is thrown, GL crash and the browser too:
**GL_OUT_OF_MEMORY : glReadPixels:** 

I've tried with all available setting, the only way to let it work is use the outputToTexture. With this settings everything is working fine and also quickly. The problem is that I've no way later to read the result data, I've tried to create a method to read the Texture and return an array with its data but it crash with the same exception. It seems GPU.js in unable to handle such big array (as output or input) but it sounds strange.
I've also tried to use different GPU instances cleaning the allocations (destroy) but I didn't find a way to avoid the out of memory.

The last chance is to "manually" read the Texture data without using GPU.js but in the end I'm also evaluating if this effort makes sense.

**Comment by robertleeplummerjr** [comment]
Can you reproduce this somewhere?  GPU.js handles texture data and I think we can even simplify where you need the data if perhaps we only use exactly (or near) what is needed in the logic.

**Comment by darionco** [comment]
Have you tried `outputToTexture` then `glReadPixels` on smaller pieces of the texture instead of reading all the texture at once?

so if you have a `1024x1024` texture you first read pixels from `0x0` to `1023x255` process that, then read pixels from `0x256` to `1023x511` process that and so on...

**Comment by robertleeplummerjr** [comment]
Closing as likely not actionable here, and at least with one suggestion.
