### ISSUE TITLE
Proposal: add the feature to skip data

### ISSUE THREAD

**Issue by gpellegri** [gpujs/gpu.js#376]
This is a proposal, I've a short experience with GPU.js so maybe this is already possible, somehow.
Using a kernel to aggregate data allows the dev to skip some data, e.g. we can easily sum array values, skip some values and return the sum.
This is not possible returning the modified input array, e.g. I didn't find a way to send a 10 elements array to the kernel and return 8 values (where 8 is not a fixed size but the result of some logic)

**Comment by robertleeplummerjr** [comment]
This is what the kernel `option`'s `output` and `constants` are for.  The kernel must know its size before execution though.  That is just the GPU being the GPU.
