### ISSUE TITLE
Unable do declare small arrays (vectors, matrix etc.) inside kernel function

### ISSUE THREAD

**Issue by kamil-kielczewski** [gpujs/gpu.js#377]
I'm unable to declare vectors inside kernel and/or pass that vectors to function - here is example wchich raise two bugs (please copy-paste below code to empty .html file):

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Bug</title>
    <!-- library GPU JS  url: https://github.com/gpujs/gpu.js -->
    <script src="https://cdn.rawgit.com/gpujs/gpu.js/develop/bin/gpu.min.js"></script>
</head>
<body >
    <div>Click to below buttons to run (and watch in console):</div>
    <button onclick="runBug1()">Bug 1</button>
    <button onclick="runBug2()">Bug 2</button>

    <script>
       
        function kernelBug1() {
            let v = [this.thread.x, 2*this.thread.x, 3*this.thread.x];
            return v[2];
        }

        function kernelBug2() {
            return sum([this.thread.x, this.thread.x])
        }

        function sum(p) {
            return p[0] + p[1];
        }

        function runBug1() {
            const gpu = new GPU();
            const bug1 = gpu.createKernel(kernelBug1).setOutput([10]);
            console.log(bug1());
        }

        function runBug2() {
            const gpu = new GPU();
            const bug2 = gpu.createKernel(kernelBug2)
                .setOutput([20])    
                .setFunctions([sum]);  
            console.log(bug2());
        }
                                             
    </script>
</body>
</html>
```

Bug 1 give message:

> An error occurred compiling the shaders: ERROR: 0:161: '=' : array / non-array mismatch
> ERROR: 0:161: '=' : cannot convert from 'highp array[3] of float' to 'highp float'
> ERROR: 0:162: 'user_vSize' : undeclared identifier...

Bug 2 give message:

> An error occurred compiling the shaders: ERROR: 0:161: 'user_pSize' : undeclared identifier
> ERROR: 0:161: 'expression' :  left of '[' is not of type array, matrix, or vector 
> ERROR: 0:161: 'user_pSize' : undeclared identifier ...

If you want to work with vectors this bug not allow you to use brief vector notation (2-3 elements arrays as variables or function parameters).

**Comment by robertleeplummerjr** [comment]
Will be partially handled with https://github.com/gpujs/gpu.js/issues/385, still looking into matrices.

**Comment by kamil-kielczewski** [comment]
I create fiddle https://jsfiddle.net/fmkwh2ez/ for version 1.10.1
Bug one now is fix-ed :)
Bug two still exists :(
