### ISSUE TITLE
For-loop execute only first iteration on Safari

### ISSUE THREAD

**Issue by kamil-kielczewski** [gpujs/gpu.js#378]
On Firefox and Chrome below code will return array with number 18. But on Safari this code will return different result - array of number 4 - because on Safari for loop make only first iteration (save below code in .html file and run on chrome and safari):

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Bug</title>
    <!-- library GPU JS  url: https://github.com/gpujs/gpu.js -->
    <script src="https://cdn.rawgit.com/gpujs/gpu.js/develop/bin/gpu.min.js"></script>
</head>
<body >
    <div>Click to below button:</div>
    <button onclick="runBug1()">Bug on Safari</button>
    <div >Desired result: </div>
    <div> [18,18,18,18,18,18,18,18,18,18]</div>
    <div >Calculated result: </div>
    <div id="out"></div>

    <script>
       
        function kernelBug1(iter) {
            let sum = 0;
            
            for(let i=2; i<iter; i++) {
                sum = sum + i;
            }
            return 2*sum ; //+ this.thread.x;
        }

    
        function runBug1() {
            const gpu = new GPU();
            const bug1 = gpu.createKernel(kernelBug1)
                .setOutput([10])
                .setLoopMaxIterations(1000);
            
            let result = bug1(5);

            document.getElementById('out').innerText = JSON.stringify(Array.from(result));
        }
                                             
    </script>
</body>
</html>
```

**Comment by robertleeplummerjr** [comment]
Safari has been a bit of a thorn, having not fully supported webgl 1, and webgl 2 not yet even in alpha.  Much work does still need to be done to get safari full compatibility.

**Comment by robertleeplummerjr** [comment]
Speaking off the cuff, I think this may have to do with how the dimensions of the canvas are managed.  Safari fails a lot of the unit tests that handle this successfully in other browsers.  They definitely "think different".

**Comment by robertleeplummerjr** [comment]
Extensive upgrades to the existing safari handling was introduced in v2, and I believe this to be resolved in v2 rc13, added a unit test for the rc 14 cleanup here: https://github.com/gpujs/gpu.js/commit/a0a92586c01defd709a01e51dbb5eb4e770ab5a5, will have it out in a day or two.
