### ISSUE TITLE
Unable to compile kernel when it is class method

### ISSUE THREAD

**Issue by kamil-kielczewski** [gpujs/gpu.js#379]
Below is testcase - copy it to fresh html file and open in browser. 

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Bug Class kernel</title>
    <!-- library GPU JS  url: https://github.com/gpujs/gpu.js -->
    <script src="https://cdn.rawgit.com/gpujs/gpu.js/develop/bin/gpu.min.js"></script>
    <style>button { margin: 20px; }</style>
</head>
<body >
    <div>Click to below button:</div>
    <button onclick="run()">Run with external function (ok)</button>
    <button onclick="runBug()">Run with class function</button>
    <button onclick="runBugStatic()">Run with static class function</button>
   
    <script>

        function kernelOk(iter) { return 2*iter + this.thread.x; }

        class MyCalculations {

            kernel(iter) { return 2*iter + this.thread.x; }

            static kernel2(iter) { return 2*iter + this.thread.x; }

            constructor() { 
                this.gpu = new GPU(); 
            }

            init() {                           
                this.bug = this.gpu.createKernel(kernelOk).setOutput([10])
            }

            initBug() {
                this.bug = this.gpu.createKernel(this.kernel).setOutput([10])
            }

            initBugStatic() {        
                this.bug = this.gpu.createKernel(MyCalculations.kernel2).setOutput([10])
            }
                        
            getResult() { return this.bug(5); }
        }

        function run() {
            console.log('Try to run with external function...');
            let mc = new MyCalculations();
            mc.init();
            console.log(mc.getResult(), "ok");            
        }

        function runBug() {
            console.log('Try to run with class function...');
            let mc = new MyCalculations();
            mc.initBug();
            console.log(mc.getResult());            
        }

        function runBugStatic() {
            console.log('Try to run with class static function...');
            let mc = new MyCalculations();
            mc.initBugStatic();
            console.log(mc.getResult());            
        }
                                     
    </script>
</body>
</html>
```

When kernel is class method or static method, then gpu.js is unable to compile it and throw below error:

> jsFunction, to string conversion check failed: not a function? kernel(iter) { return 2*iter + this.thread.x; }
> jsFunction, to string conversion check failed: not a function? kernel2(iter) { return 2*iter + this.thread.x; }
> 
> jsFunction, to string conversion check failed: not a function?

To have clean code, this feature is quite important.

**Comment by robertleeplummerjr** [comment]
This is not currently supported, but could be if we proposed it.  By using `gpu.createKernel(function() {})` there simply isn't enough access to the rest of the class, so we'd need a means of feeding the whole class in.  Also, since classes can have many methods, we'd need a means of distinguishing which method is the kernel (unless, are they all kernels?  I don't think so?).

Here are a few options to get the proposal started, feel free to like or hate or propose your own:

```js
//option 1
const kernel = gpu.createKernel(MyClass.myMethod, {
  kernelClass: MyClass
});

//option 2
const kernel = gpu.createKernel(MyClass, {
  kernelMethod: MyClass.myMethod
});

//option 3
const kernel = gpu.createClassKernel(MyClass, MyClass.myMethod, options);

//option 4
const kernelClass = gpu.class(MyClass);
const kernel = kernelClass.createKernel('myMethod', options);
```

**Comment by kamil-kielczewski** [comment]
Currently when kernel is lonley function we assume that its body not use any external variables not binded to it explicity using gpu.js (by parameters, constans etc. ) (e.g. inside kernel we don't have access to JS main scope like `window`, `document` etc. ) - if Im wrong please correct me.

So I think we can make similar assumption in class methods case. So we don't need to have access to all class body using `gpu.createKernel(function() {})`. We want to have access only to his one method (kernel) .  In case when our kernel use other methods of that class (or other classes) we can use `setFunctions` (and others standard gpu.js mehtods like .setConstants etc. ) - here is egzample:

```
class MyKernels {
     kernel1() { ... let a= kernel2(77); let b = kernel3(a); ...  }
     kernel2(x) { ... }
     kernel3(x) { ... }

     init() {
          this.gpu = new GPU(); 
          this.calculator = gpu.createKernel(this.kernel1)
               .setFunctions([
                    this.kernel2, 
                    MyKernels.kernel3
               ]);
     }
    
    ....
}
```

This approach makes that we not change anything in point of gpu.js library user. 

Do you see any technical (JS) problem with this approach? So my proposition is to not create new method but rather extend existing methods (`createKernel`, `setFunctions`) to support class methods.

**Comment by robertleeplummerjr** [comment]
This sounds interesting, and I'm sure myself and the community would welcome proposals and PR's.

**Comment by robertleeplummerjr** [comment]
Going to go ahead and close this issue for the time being, if another is opened to handle it, it'll be focused on adding this as a feature.
