### ISSUE TITLE
Important: Unable to return vector value in kernel sub-functions

### ISSUE THREAD

**Issue by kamil-kielczewski** [gpujs/gpu.js#385]
We cannot return vector value from functions using by kernel. This feature is very important especially when we want to make process some vector and return other vector construct using processed values.

Example of usage:
procedure that normalize vector,
procedure that multiply vector by some matrix (e.g. rotation)
procedure that find normal vector on(to) surface at given point
...
currently it is imposible to delegate such tasks to separate functions

Here is fiddle test case with this bug (which shows that we are unable to delegate vector normalization to separate function - of course we can create two functions - first for calc `nx` and second for calc `ny` but we duplicate length calculations and lose performance...): 
https://jsfiddle.net/8mqokauw/1/

**Comment by robertleeplummerjr** [comment]
So the use case isn't returning it from the kernel, it is simply passing it from within the kernel from function to function, correct?

**Comment by kamil-kielczewski** [comment]
Yes - it is not about kernel but functions used by kernel - that functions cannot return vectors... (as small arrays with 2-4 elements)

**Comment by robertleeplummerjr** [comment]
Not to sidestep the issue (and this somewhat falls apart with larger matrices), but rather to offer a suggestion, you could simply:

```js
function kernelBug() {
  let vx = this.thread.x;
  let vy = this.thread.y;
  let l = calcL(vx,vy);
  return norm(l,vx) + norm(l,vy);
}

function norm(l, v) {
  return l*v;
}

function calcL(x, y) {
  return 1/Math.sqrt(x*x + y*y);
}
```

**Comment by robertleeplummerjr** [comment]
Note: I know this isn't a very practical solution, and not to diminish the importance of your use case.  I'm empathetic to need.

**Comment by kamil-kielczewski** [comment]
I know that we can do it (move common calculations outside function) with that simple function as normal calculation - but in my case I have raytracer and must return point of collision and other informations like distance or object id after ray hit (for texturing) - may be your approach is possible in my case but we will get spaghetti-hard-to-maintain-and-read code at output.

**Comment by kamil-kielczewski** [comment]
Do you think this feature is complicated and hard to implement? Can I help in some way?

**Comment by robertleeplummerjr** [comment]
>may be your approach is possible in my case but not trivial and we will get spaghetti-hard-to-maintain-and-read code at output.

Understood, I'll continue to think about this.

>Do you think this bug/feature is complicated and hard to implement?

I don't believe this is terribly hard to implement, but we'll need either a simple means of type detection or a stronger means of defining what a type is.

>Maybe if you give some hints about places in code where I can fix this, I try to do it myself and create pull request ?

Ty for your willingness to contribute.  It is truly welcome here!

I've been thinking about this for some time, and I honestly think we can find a means of looking up types because we have such a very specific environment.

Everything that deals with javascript to glsl (and soon to be opencl) is done each backend class.  The glsl WebGL v1 for example: https://github.com/gpujs/gpu.js/blob/develop/src/backend/web-gl/function-node.js

At only 1200-ish lines of code, because we're in a very specific environment, and _because the code that is transpiled must work in javascript_, we can surmise that we'll need to handle the following scenarios:

Returning arrays directly (easy):
```js
function() {
  return [];
}
```

Returning arrays referenced directly (easy):
```js
function() {
  const array = [];
  return array;
}
```

Returning arrays referenced indirectly (still fairly easy):
```js
function() {
  const array = [];
  const array2 = array;
  return array2;
}
```

Let me see if I can get an example together that fails and we'll see where it goes?  Keep in mind too, you can add your own native functions using `nativeFunctions` option.  I'll post an example momentarily.

**Comment by kamil-kielczewski** [comment]
I see this is complicated so I need time to research a little.

The question: in shader (C-like)  code we can use functions which are able to return arbitrary or fixed vector? (if arbitrary it will be nice, if only fixed size it will be satisfy too if we are able to return vec2,3,4 and maybe matrixes 2,3,4). If it is posible in c-shader to reutrn arbitrary sized array then there is chance to support this in js-shader.

**Comment by ubernaut** [comment]
This is super relevant to my gravity simulation. at the moment I am performing the acceleration due to gravity three separate times (once for each dimension) with a ton of redundant wasteful code because I can only return the acceleration value in one dimension at a time. This causes me to calculate the acceleration for all dimensions in the function but only return one.   

https://github.com/ubernaut/spaceSim/blob/30b50e08bda89fe7769908d419b02c66c1fcc11e/app/js/sim/systemBuilder.js#L335 

If I could return a full vector from a function it would speed up my nbody sim by a factor of 3

**Comment by robertleeplummerjr** [comment]
Ok, about 70% of the way there with https://github.com/gpujs/gpu.js/commit/4f26639a595a738de5d87f991dce577a8d9500e1.  Soon to be mvp.

**Comment by robertleeplummerjr** [comment]
We need a more generic term for vec2, vec3, vec4 and I'm up for suggestions.  Because we'll eventually have other gpu framework support, like opencl.

**Comment by robertleeplummerjr** [comment]
Ok, now full on working with static declarations like this:

```js
    var gpu = new GPU({ mode: mode });
    function typedFunction() {
      return [1, 2];
    }
    gpu.addFunction(typedFunction, {
      returnType: 'vec2'
    });
    var kernel = gpu.createKernel(function() {
      var result = typedFunction();
      return result[0] + result[1];
    })
      .setOutput([1]);
```

The glsl 1 to 1 of this outputs as:
```glsl
vec2 typedFunction() {
return vec2(1.0, 2.0);
}
void kernel() {
vec2 user_result=typedFunction();
kernelResult = (user_result[0]+user_result[1]);return;
```

I consider this to only really be half done though, because I believe we can be much more automated with type detection, but this gives us a starting point for when the values are detected.  However, this could easily be part of the API if the type detection is more overhead than we're comfortable with.  Also, this looks a little deceiving, in that the type detection (although extremely simple) partially is working, because if I do something like this (note change array size):

```js
    var gpu = new GPU({ mode: mode });
    function typedFunction() {
      return [1, 2, 3]; //<-- look here
    }
    gpu.addFunction(typedFunction, {
      returnType: 'vec2'
    });
    var kernel = gpu.createKernel(function() {
      var result = typedFunction();
      return result[0] + result[1];
    })
      .setDebug(true)
      .setOutput([1]);
```

The compilation breaks (which is what we actually want) because the array returned is being detected as a `vec3`, but the function is declared as returning `vec2`, and so compilation fails:

```
An error occurred compiling the shaders: ERROR: 0:161: 'return' : function return is not matching type:
```

which is transpiled to:

```glsl
vec2 typedFunction() {
return vec3(1.0, 2.0, 3.0);
}
void kernel() {
vec2 user_result=typedFunction();
kernelResult = (user_result[0]+user_result[1]);return;
}
```

**Comment by kamil-kielczewski** [comment]
may be in future we make smething more JS-like looking for array types - here is my proposition:

Instead of declaring type int his way 

`     returnType: 'vec2'`

We cen type (base on [this](https://stackoverflow.com/questions/34937349/javascript-create-empty-array-of-a-given-size))

`     returnType: Array(2);`

Is this possible for general `Array(n)` ?

**Comment by robertleeplummerjr** [comment]
>We cen type (base on this)
`returnType: Array(2);`

Yea, I like it!  But lets go one simple: to `"Array(2)"`, which reduces the complexity of instantiating an array for no other type than to reference its type.

>Is this possible for general `Array(n)` ?

It is, the feature is called "first-class array"'s but only seems to be working well with webgl2, and spotty with hardware and implementations at best - further reading: https://stackoverflow.com/questions/29734341/first-class-array-not-supported.

>However we can also consider array element type

I agree.  A very valuable feature!

>`returnType: [ Array(2), "double" ];`

I say, lets make it as terse as possible, like just a string, but lets address that when the times comes.

**Comment by robertleeplummerjr** [comment]
I'd say we are like 90% there now with https://github.com/gpujs/gpu.js/commit/d561fcf22828425e3267b0a37e469e56e9a09328

All unit tests now passing and use cases (as far as my naive understanding of the universe goes) covered using strongly typed means, which after I think about it more and more may be simply all and exactly what this needs.  There are a couple internal artifacts I'd like to clean up before release, but this should be enough for production usage.

**Comment by kamil-kielczewski** [comment]
Thank you for fix this - it is great :)

I have one more question - it is posible to return vector larger than 4 (or may be matrix instead) - e.g. somenone need to return 6 or 10 numbers... ?

**Comment by robertleeplummerjr** [comment]
>Thank you for fix this - it is great job :)

It has been a long time coming!  I look forward to this being a solid feature from this day forward.

>it is posible to return vector larger than 4 (or may be matrix instead)

Yes!  Why not both?  How big do we want to go?  Also, we want to support more than just three (xyz) dimensions, which is trivial to add as well.  Matrices as well if following the same development path will be trivial.

>if yes than maybe we can increase Array(n) from n=2,3,4 to n=2,...,16

I would say lets stick with what paths have been provided via stable GPU architectures first and foremost.  

>(btw: what is surprising to me JS not support 2D arrays in simple way... here )

Js supports them fine, it is GLSL or WebGL (but mostly GLSL, and by relation C/C++) that does not.  But you have to ask yourself, do you _really_ want it to?  When you think about how the threads work for building out a value for returning a set of values that will be in a collection, most notable an array or a matrix, or a cube, and that each thread _will run its entire lifecycle for each returned value to said collection_, which can be a *LOT* of overhead.

With that overhead, you can take something that is amazingly fast, the GPU, and reduce its performance to that of which isn't performant at all.  That being said there is still much that we can do from the perspective of the vertex that we've not investigated that may help with this.

As of now the code is in code review, and represents a substantial paradigm addition (perhaps "shift", but probably not the right word) and I invite you to code review and be critical.

Ty for the use case!

**Comment by kamil-kielczewski** [comment]
I update test case after merge of this fix, but unfortunatley there is still some problem:

https://jsfiddle.net/8mqokauw/3/

> gpu.js?20181030:2919 Uncaught TypeError: Cannot read property 'object' of undefined
>     at WebGL2FunctionNode.astVariableDeclaration (gpu.js?20181030:2919)
>     at WebGL2FunctionNode.astGeneric (gpu.js?20181030:1780)
>     at WebGL2FunctionNode.astFunctionExpression (gpu.js?20181030:2566)
>     at WebGL2FunctionNode.astGeneric (gpu.js?20181030:1750)
>     at WebGL2FunctionNode.generate (gpu.js?20181030:4868)
>     at WebGL2FunctionBuilder.getPrototypes (gpu.js?20181030:1367)
>     at WebGL2FunctionBuilder.getPrototypeString (gpu.js?20181030:1360)
>     at WebGL2Kernel._getKernelString (gpu.js?20181030:5613)
>     at WebGL2Kernel._getFragShaderArtifactMap (gpu.js?20181030:4021)
>     at WebGL2Kernel._getFragShaderString (gpu.js?20181030:5713)

In this line gpu.js:2919:

```
else if (init.object.object.object.object && init.object.object.object.object.type === 'ThisExpression' && init.object.object.object.property.name === 'constants') {
...
```

**Comment by robertleeplummerjr** [comment]
I can reproduce the issue with the minimalist test:
```js
var node = new GPU.WebGLFunctionNode(null, function assignThreadToVar() {
    let x = this.thread.x;
    let y = this.thread.y;
    let sum = x + y;
    return sum;
  });
```

Opened pr, and resolved there.  Please review when you have a chance.

**Comment by robertleeplummerjr** [comment]
Updated using http://unpkg.com/: https://jsfiddle.net/robertleeplummerjr/8mqokauw/4/

**Comment by robertleeplummerjr** [comment]
I did find an issue with CPU fallback I'm working to resolve now.

**Comment by kamil-kielczewski** [comment]
Ok the problem was that cdn cache file and  ignore query string (after `?`) so to read current version we needto give commit number - so for 01.11.2018 we have this: https://cdn.rawgit.com/gpujs/gpu.js/87ccce51df9c7162f0f91fde20992268425e75fd/bin/gpu.js

Ok so here is update test-case (I remove sqrt from norm to easy check result values) - test is pass so i close this issue: https://jsfiddle.net/8mqokauw/8/

**Comment by robertleeplummerjr** [comment]
Ty!
