### ISSUE TITLE
Getting value from setOutputToTexture

### ISSUE THREAD

**Issue by scheng123** [gpujs/gpu.js#386]
Hi! So basically after I set assign a kernel to variable "a" and I execute the function:
```
var gpu = new GPU();
var a = gpu.createKernel(function(){return this.thread.x;}).setOutput([10]).setOutputToTexture(true);
a();
```
I should get [0, 1, 2, 3, 4, 5, 6, 7, 8, 9];<br>
But I got some texture object, which makes sense in some cases, but how am I going to get the output data I need? (expected output: Array: [1, 2, 3, 4...])

**Comment by robertleeplummerjr** [comment]
Simply setup your kernels to do it for you.

```js
var gpu = new GPU();

var toTextureKernel = gpu.createKernel(function(){
  return this.thread.x;
})
  .setOutput([10])
  .setOutputToTexture(true);

var toArrayKernel = gpu.createKernel(function(value){
  return value[this.thread.x];
})
  .setOutput([10]);

var texture = toTextureKernel();
var array = toArrayKernel(texture);
```

**Comment by scheng123** [comment]
Oh, ok, sorry, couldn't find it anywhere in the readme
