### ISSUE TITLE
gpu.destroy() is not a function

### ISSUE THREAD

**Issue by binary-person** [gpujs/gpu.js#387]
Hi, so basically I saw in your readme, that you could cleanup kernels and gpu instances by this commands:
```
gpu.destroy();
kernel.destroy();
```
So I did:
```
var gpu = new GPU();
var kernel = gpu.createKernel(function(){return this.thread.x}).setOutput([100]);
var someValue = kernel();
// Cleanup Time!
kernel.destroy(); // Throws error gpu.destroy is not a function
gpu.destroy(); // Throws error kernel.destroy is not a function
```
Calling gpu.destroy() throws the function not found error. and kernel.destroy()
So then where exactly do you call it?

**Comment by scheng123** [comment]
https://jsfiddle.net/9mjc5p02/8

**Comment by StefanHue** [comment]
Same problem. Any solutions yet?

**Comment by scheng123** [comment]
Oh, I see, well I strongly suggest you update the download link on your webpage: https://gpu.rocks
