### ISSUE TITLE
How to take matrix as an input and output an image?

### ISSUE THREAD

**Issue by Jonathan-D-Ip** [gpujs/gpu.js#388]
How to take matrix as an input and output an image?

**Comment by robertleeplummerjr** [comment]
Like this? https://jsfiddle.net/robertleeplummerjr/2noezxm9/14/

**Comment by kamil-kielczewski** [comment]
If we add `transform:scale(1,-1)` to `paint.style` in fiddle we flip picture and it will be similar to array :P
