### ISSUE TITLE
combineKernels exmample not working?

### ISSUE THREAD

**Issue by slfan2013** [gpujs/gpu.js#396]
I am trying to learn `Combining kernels` using example. But I got an error of `Uncaught TypeError: Cannot read property 'x' of undefined`.
Please see following fiddle

https://jsfiddle.net/t8o7pufj/

**Comment by robertleeplummerjr** [comment]
Ty for finding this!  Handled here: https://github.com/gpujs/gpu.js/commit/62d4ea739d5fe2355216f1d453a5775bc3f032ab

Will be out in a few days.
Again, ty!
