### ISSUE TITLE
Array(2) examples: Directly returned  not working?

### ISSUE THREAD

**Issue by slfan2013** [gpujs/gpu.js#397]
I am trying to run the following example, 

```
const gpu = new GPU();

const myFunc = gpu.createKernel(function() {
     return [0.08, 2];
 }).setOutput([100]);
console.log(myFunc());
```

but it returns an error of 
```
gpu.js:3636 An error occurred compiling the shaders: ERROR: 0:161: '=' : dimension mismatch
ERROR: 0:161: 'assign' : cannot convert from 'const 2-component vector of float' to 'highp float'
```

Please see [fiddle](https://jsfiddle.net/geanuz1h/).

**Comment by robertleeplummerjr** [comment]
That type currently isn't supported as a return value is all.  Either float (`return 0.08`) or vec4(`return [0.08, 2, 0.08, 2]`) are currently only supported.

**Comment by slfan2013** [comment]
I see.

It should be 

```
gpu.createKernel(function() {
     const array2 = [0.08, 2];if(this.thread.x==1){return array2[0]}else{return array2[1];}
     
 }).setOutput([2,100])()
```

**Comment by robertleeplummerjr** [comment]
I spoke too soon-ish: https://jsfiddle.net/robertleeplummerjr/34Lpcgnf/34/
If you turn on texture mode, it writes the color data to a texture that is returned from the function which can be sent to another function.  So _direct return statements_ that are the main kernel only support floats.

Also: Don't do that weird if statement, that won't work well on GPU for anything larger than a single pixel.  Use raycasting/raytracing math for it.

**Comment by JeffCave** [comment]
Having tripped over this today, would it be reasonable to remove these examples from the documentation until such time as the feature works?

**Comment by robertleeplummerjr** [comment]
Not at this time.  The feature works for internal kernels, and we'll be adding support for it on the main kernel in the next month or so.

**Comment by Steve73** [comment]
> Not at this time. The feature works for internal kernels, and we'll be adding support for it on the main kernel in the next month or so.

@robertleeplummerjr: Are you still working on this? This feature would be a great help!

**Comment by robertleeplummerjr** [comment]
I'm currently working on the Node WebGL runtime, nearly done,  and that will be just after.

**Comment by Smilebags** [comment]
Looking forward to this working, too.

Not sure if I'm doing something wrong, or if this is a bug, but I am attempting to do vector processing on an array of triangles (which are each length-3 arrays with length-3 arrays in each item) and return a single array of vectors. What would the output flag for this be? I can't seem to figure it out.

**Comment by robertleeplummerjr** [comment]
This is still needing to be solved, but would love some assistance.  Getting the GPU node capabilities working and some remaining issues with the new version of GPU.js have seemed to suck up a great deal of time.

**Comment by Smilebags** [comment]
I would love to help but I feel like I'm a bit out of my depths - parsing JS into an AST and then executing that on a canvas - __mental__.

I'm hoping one-day soon we will get hardware-acceleratable primitives in JavaScript as a standard.

**Comment by robertleeplummerjr** [comment]
This has now been solved with v2 rc13.
