### ISSUE TITLE
Create Kernel Map not working

### ISSUE THREAD

**Issue by slfan2013** [gpujs/gpu.js#398]
Error:

```
Uncaught Error: kernel.output not an array
    at Function.checkOutput (gpu.js:6402)
    at WebGL2Kernel.validateOptions (gpu.js:4978)
    at WebGL2Kernel.build (gpu.js:3599)
    at WebGL2Kernel.run (gpu.js:5025)
    at shortcut (gpu.js:2274)
    at window.onload ((index):43)
```

Please see [fiddle](https://jsfiddle.net/dzhLrfjn/).

**Comment by robertleeplummerjr** [comment]
This is an expected error message.  It is trying to tell you that you need to define an output for your kernels.  Here is the slightly modified working version: https://jsfiddle.net/robertleeplummerjr/c8ph70k3/

**Comment by robertleeplummerjr** [comment]
I found that you are just copying the docs, and we need to correct them: https://github.com/gpujs/gpu.js#object-outputs

Reopening to get this resolved asap.

**Comment by robertleeplummerjr** [comment]
Fixed in https://github.com/gpujs/gpu.js/commit/4e1bf1f0d1bb1378b84bb2da925b42e574fa641a, will be released soon.
