### ISSUE TITLE
Return more than one value in the main kernel.

### ISSUE THREAD

**Issue by Steve73** [gpujs/gpu.js#405]
This post is related to #397 and a feature request. 

The abilty to return or write more than one value in the main kernel would be very useful. If the kernel does some expensive computation and returns two values you have to use .setOutput(..., 2). But then you  end up doing the expensive computation twice.

„return [x, y]“ would be perfect but I guess that‘s not possible, right? Maybe it‘s possible to write to global memory from within the main kernel? Or maybe you have some other idea to address the problem?

Thank you for this great library!

**Comment by Steve73** [comment]
I'm still looking for a way to return more data per return of the main kernel. Right now I can only return one value per return. With multiplications I'm able to pack more than one number in one return value:

```
const myFunc = gpu.createKernel(function() {
    var result1 = ...;
    var result2 = ...; 
    return value1 * 256 + value2;
}).setOutput([...]);
```

But this is ugly and costly. Is there a better way to do it?

Also, right now I'm limited to one 32-bit float value per return. But WebGL2 supports textures with more data per pixel (e.g. RGBA32UI, see https://webgl2fundamentals.org/webgl/lessons/webgl-data-textures.html). It would be great to access this functionality and return up to four 32-bit values per return.

**Comment by robertleeplummerjr** [comment]
This is solved in v2 rc13.
