### ISSUE TITLE
neural net feedforward  and backpropagation ?

### ISSUE THREAD

**Issue by extremety1989** [gpujs/gpu.js#409]
Is there any neural net implementation in GPU.js ?  i builded simple neural net class and matrix in javascript,then i  replaced matrix multiplication in vanilla javascript with gpu.js one from example, my browser just broke... soo much lagg

**Comment by kamil-kielczewski** [comment]
yes - you can implement it using js and gpu.js :)

**Comment by extremety1989** [comment]
any example ?

**Comment by extremety1989** [comment]
> 
> 
> yes - you can implement it using js and gpu.js :)

any example ?

**Comment by robertleeplummerjr** [comment]
Likely you aren't using GPU.js for its strengths, which are using textures.  Here is the complete implementation used in brain.js: https://github.com/BrainJS/brain.js/blob/master/src/neural-network-gpu.js
