### ISSUE TITLE
Issue with if statement?

### ISSUE THREAD

**Issue by aautar** [gpujs/gpu.js#410]
I started work on porting a line intersection test function to gpu.js (using latest version, v1.10.4) and noticed I was getting some bizarre output values. I just started stripping away data and code to try to figure out the cause, and eventually stripped things down to just a subtraction and a simple if-conditional.

```javascript
const gpu = new GPU();

const multiLineIntersect = gpu.createKernel(function(a) {

    const paramDenom = a[this.thread.x][1] - a[this.thread.x][0];
    if(paramDenom === 0) {
        return 100;
    }

    return 200;                             

}).setOutput([2]);


const result =                 
    multiLineIntersect(
        [
            [0, 0],
            [0, 2]    
        ]
    );

console.log(result);
```

The result I'm getting is `[64, 128]`, which is obviously wrong.

I also tried with a single input vector (`[0, 2]`) hardcoded in the kernel, and that produced a correct result, although that may just be the compiler optimizing away the conditional.

Not sure where to go from here. 
Maybe a bug or maybe I'm missing something obvious?

**Comment by Steve73** [comment]
This looks like the bug I reported under #358. You can try .setFloatOutput(true) as a workaround.

**Comment by aautar** [comment]
Thanks! It does look like it's the same as #358 
I tried `setFloatOutput(true)` as you suggested and I'm getting correct results.

**Comment by Steve73** [comment]
Thanks for letting us know! So I'm not the only one who is experiencing the bug.

@robertleeplummerjr: I found the bug #358 on all systems with NVIDIA GeForce cards I habe access to. You can check it with this simlpe fiddle: https://jsfiddle.net/argeuLt9/

**Comment by robertleeplummerjr** [comment]
Just reproduced.  How do you guys think we should handle this?  Documentation?

**Comment by robertleeplummerjr** [comment]
Documentation doesn't seem right...

**Comment by Steve73** [comment]
> Just reproduced. How do you guys think we should handle this? Documentation?

I would prefer a fix for the bug. :-) The setFloatOutput(true) workaround works but leads to unnecessary extra code in my project, e.g. calls of floor(). Do you know, what causes the bug?

**Comment by robertleeplummerjr** [comment]
If I use values that come from the CPU, the problem goes away as well for me:
```js

const { GPU } = require('./src');
const gpu = new GPU();

const multiLineIntersect = gpu.createKernel(function(a, b, c) {

    const paramDenom = a[this.thread.x][1] - a[this.thread.x][0];
    if(paramDenom === 0) {
        return b;
    }

    return c;
})
  .setDebug(true)
  .setPrecision('unsigned')
  .setOutput([2]);


const result =
    multiLineIntersect(
        [
            [0, 0],
            [0, 2]
        ],
        100, 200
    );

console.log(result);

```

Really weird!

**Comment by robertleeplummerjr** [comment]
Found a fix!  We are going to make the old encoder legacy, and use a new one.  Tested on OSX, Windows with and without Nvidia cards, and Linux.

**Comment by Steve73** [comment]
Great news!! I‘m going to test it tomorrow!
