### ISSUE TITLE
Unable to return three outputs

### ISSUE THREAD

**Issue by WedadAnbtawi** [gpujs/gpu.js#416]
Hello,

I'm trying to return three outputs as follows:
_**const gpu = new GPU();
var f = gpu.createKernel(function (arr) {
	var s = 0;
	var vx = 0;
	var vy = 0;
	var x = 0;
	var y = 0;
	var d = 0;
	var eq = 0;
	for (var i = 0; i < 3; i++) {
		x = arr[0][0]-arr[i][0];
		y = arr[0][1]-arr[i][1];
		d = Math.sqrt(x*x+y*y);
		eq = 1/(1+Math.pow(d,2));
		s += eq;
		vx += Math.pow(eq,2)*x;
		vy += Math.pow(eq,2)*y;
	}
	return [s,vx, vy];
}).setOutput([3])
console.log(f(Y));**_

Where Y is an array of 2D points.

I'm getting the following errors:

**An error occurred compiling the shaders: ERROR: 0:143: '[]' : array constructor supported in GLSL ES 3.00 and above only
ERROR: 0:143: '=' : array / non-array mismatch
ERROR: 0:143: 'assign' : cannot convert from 'highp array[3] of float' to 'highp float'**

**Comment by WedadAnbtawi** [comment]
@kamil-kielczewski Thank you for your comment. I saw codes using this.thread.x but I didn't get it how to use it, can you help me in that please?

**Comment by kamil-kielczewski** [comment]
for instance - you have array witch many numbers e.g 10000, and wan't to calculate sin function for each element. I will write code from head

Wrong way:
```
const matMult = gpu.createKernel(function(a) {
    var b = 0;
    for (var i = 0; i <10000; i++) {
        b= Math.sin(a[i]);
    }
    return b;
}).setOutput([10000]);
```

Right way:
```
const matMult = gpu.createKernel(function(a, b) {
    var b = 0; 
    b = Math.sin(a[this.thread.x]); 
    return b;
}).setOutput([10000]);
```

The first solution will works about ~10000x slower than second - now Idea is more clear?

**Comment by WedadAnbtawi** [comment]
@kamil-kielczewski Thank you! I have data of 10000 points and I used 3 only for testing. Can we avoid like b += a using this method? i.e. if I need to get the total sum of a vector. I tried it as follows s = s+eq[this.thread.x] and tried s += eq[this.thread.x] but I dot **'user_eqSize' : undeclared identifier**

**Comment by kamil-kielczewski** [comment]
show full code (when you put code here select it and click on <> button in editor)

**Comment by WedadAnbtawi** [comment]
```
gpu.createKernel(function (arr) {
	var s = 0;
	var vx = 0;
	var vy = 0;
	var d;
	var eq;
	var x;
	var y;
	x = arr[0][0]-arr[this.thread.x][0];
	y = arr[0][1]-arr[this.thread.x][1];
	d = x*x+y*y;
	eq = 1/(1+d);
	//for (var i = 0; i < 3; i++) { //I need to apply summation for the fields
		s += eq;
		vx += Math.pow(eq,2)*x;
		vy += Math.pow(eq,2)*y;
	//}
	return [s,vx,vy]; //I need to return 3 elements but it didn't work
}).setOutput([3]);
```

**Comment by kamil-kielczewski** [comment]
May be try something like this (I write from head)

```
gpu.createKernel(function (arr) {
	var s = 0;
	var vx = 0;
	var vy = 0;
	var d =0 ;
	var eq =0;
	var x =0;
	var y =0;
	
	for (var i = 0; i < 3; i++) { //I need to apply summation for the fields
            x = arr[0][0]-arr[this.thread.x][0];
	    y = arr[0][1]-arr[this.thread.x][1];
      	    d = x*x+y*y;
	    eq = 1/(1+d);
	    s = s+eq;
	    vx =  vx + Math.pow(eq,2)*x;
	    vy = vy + Math.pow(eq,2)*y;
	}

         var r=s; 
         if(this.thread.x%3==1) r=vx; 
         if(this.thread.x%3==2) r=vy; 
	return r;
}).setOutput([3]);
```

**Comment by robertleeplummerjr** [comment]
@WedadAnbtawi please let us know if that works for you.  Going to go ahead and close to keep things moving along.  If it does not, we'll Langley reopen.
