### ISSUE TITLE
Using the same canvas/context with graphical:true and different output sizes breaks on second output size

### ISSUE THREAD

**Issue by chadams77** [gpujs/gpu.js#419]
What I was doing was:
 1. Generating an image offscreen with GPU.js
 2. Copying it to a 2d canvas using ctx.drawImage(kernel.getCanvas(), 0, 0)
 3. Using the copy canvas to generate a three.js texture
 4. Generate an image offscreen with a different output size using GPU.js
 5. Copying it to a 2d canvas using ctx.drawImage(kernel.getCanvas(), 0, 0)
 6. Using the copy canvas to generate a three.js texture

Seems to be broken on step 4 or 5. I tried resizing and clearing the canvas used by the shared context between step 3 & step 4, something wasn't right. Since I only use three output sizes (512x512, 1024x1024, and 2048x2048), I've just been using a separate canvas/context for each size, which allows me to reuse webgl contexts and have everything still work, it would be nice to get all this texture gen using a single context if possible though.

**Comment by Jonathan-D-Ip** [comment]
i think i have a similar issue. I was trying to use two kernels to precompute two different noise textures of different sizes. if i render the smaller one first, everything works fine. if i render the larger one first, the smaller one is not rendered properly. The texture is ok but there is an extra white space surrounding the texture causing problem for my program. I guess this is due to the fixed canvas size.

**Comment by robertleeplummerjr** [comment]
Can you write a simple jsfiddle that reproduces the issue so we can easily diagnose and fix?

**Comment by ogewan** [comment]
> i think i have a similar issue. I was trying to use two kernels to precompute two different noise textures of different sizes. if i render the smaller one first, everything works fine. if i render the larger one first, the smaller one is not rendered properly. The texture is ok but there is an extra white space surrounding the texture causing problem for my program. I guess this is due to the fixed canvas size.

in gpu-browser.min.js@9087 the lib does updateMaxTexSize which stores the largest size of the internal canvas and resizes it to that, even if you force the canvas to be smaller externally. This is why you get the white space. 

with setGraphical true, perhaps it should not use maxTexSize to resize the canvas.

As a work around you can set kernel.maxTexSize to whatever you want

**Comment by robertleeplummerjr** [comment]
Going to go ahead and close as there is a current work around.
