### ISSUE TITLE
Incorrect processing of if-statement inside for-loop

### ISSUE THREAD

**Issue by jaapmurre** [gpujs/gpu.js#423]
It seems that with an if-statement inside a for-loop only the first statement in the if-statement is processed conditionally and the remaining statements are *always* processed, even if the condition is false. I am using a GTX 680 to run this.

In the code below the statement `a = 3;` is always processed even though it shouldn't. Moving the if-statement outside the for-loop restores correct behavior. Making the line `a = 3;` the first line also gives correct behavior but now `b = 2;` (as a second line) is erroneously always processed.

    const the_gpu = new GPU();
    const testIf = the_gpu.createKernel(function(v) 
    {
        let b = 0;
        let a = 0;

        for (let i = 0; i < 1; i++) // Leaving out the for-statement works correctly as well
        {
            if (v[this.thread.x] > 0) {
                b = 2; // Without this line it works correctly (only the first line is conditionally processed and the rest of the block always?)
                a = 3;
            } 
        }
        return a;
    }, {
    output : [4]
    }) // bug is not solved by setting .setFloatOutput(true);

    console.log("testIf: ",testIf([0,0,1,1])); // Should give [0,0,3,3] but gives [3,3,3,3], i.e., a = 3 is always processed

**Comment by robertleeplummerjr** [comment]
What version are you running of GPU.js?

**Comment by jaapmurre** [comment]
The package.json says 2.0.0-rc.1. I downloaded it two days ago.

**Comment by robertleeplummerjr** [comment]
Can you try 2.0.0 rc2?

**Comment by jaapmurre** [comment]
Sure, but I don't see it yet. When will it be available?

**Comment by robertleeplummerjr** [comment]
It was already, but I went ahead and published it for you: https://github.com/gpujs/gpu.js/releases/tag/2.0.0-rc2

**Comment by robertleeplummerjr** [comment]
Sorry, published via NPM, not on the releases area of the repo.

**Comment by robertleeplummerjr** [comment]
Awesome!  Ty for finding and reporting!
