### ISSUE TITLE
Pipeline into same kernel gives error

### ISSUE THREAD

**Issue by laurensdijkstra** [gpujs/gpu.js#424]
I would like to run the output of my kernel through the same kernel again and again, without the data having to be passed from cpu to gpu. I thought pipeline might help, but when I use the output of the pipelined kernel as input to the same kernel in the next iteration, I get

` WebGL warning: drawArrays: Texture level 0 would be read by TEXTURE_2D unit 0, but written by framebuffer attachment COLOR_ATTACHMENT0, which would be illegal feedback.`

I don't follow why this would result in a feedback loop, is it a bug?

Code to reproduce:

```javascript
    const gpu = new GPU();
    const compute = gpu.createKernel(function(input) {
        return input[this.thread.x][this.thread.y] + 1;
    }, {
        output: [2, 2],
        pipeline: true
    });

    var texture = compute([[1, 1], [1, 1]]);
    compute(texture);
    compute(texture);
```
Using 2.0.0-rc1 on Firefox

**Comment by laurensdijkstra** [comment]
Now you might ask why I would want to run the same kernel multiple times. I want to make gpu accelerated cellular automata, which I then want to eventually render on screen with some fancy effects. Every cell has the same function depending on its neighbours determining what its next state will be. I will probably want to render each iteration after it is computed, depending on how fast the simulation will run, but I intend to run it on 1024x1024x1024 cells so I really don't know how fast it will run.

Now I thought using a for loop in the kernel would:
1. not allow me to use the result after each iteration in a rendering pass
2. not be "thread safe" as some shaders might still be on iteration 1 while others might be on iteration 2?

**Comment by robertleeplummerjr** [comment]
I believe you just need to use `immutable` on the thread:

```
const compute = gpu.createKernel(function(input) {
        return input[this.thread.x][this.thread.y] + 1;
    }, {
        output: [2, 2],
        pipeline: true,
        immutable: true
    });
```

The problem is that the input arguments and output cannot be the same.

**Comment by laurensdijkstra** [comment]
Ok, and this would result in the data being written to the texture on the GPU and then reused without reuploading the next time I run the kernel?

**Comment by robertleeplummerjr** [comment]
It causes a new texture to be written each time, rather than writing to the same one.

**Comment by robertleeplummerjr** [comment]
Also, ty for finding the new name of the setting.  I apologize for the maneuvering stuff around whilst in pre-release mode.
