### ISSUE TITLE
node-gyp build fail

### ISSUE THREAD

**Issue by Smilebags** [gpujs/gpu.js#426]
`LINK : fatal error LNK1295: '/OPT:NOREF' not compatible with '/LTCG:incremental' specification; link without '/LTCG:incremental' 
[C:\Users\username\Documents\project-name\node_modules\gl\build\webgl.vcxproj]` occurs when installing `npm i -s gpu.js`

Windows 10, node v11.10.0, npm 6.7.0

**Comment by robertleeplummerjr** [comment]
You'll need to take a look at how to install headless-gl in windows.  There are a few prerequisites: https://github.com/stackgl/headless-gl#windows

Every other operating system is literally just `npm i` or `yarn i`, or very close to it.  If you find something that needs addressed and are up to the task, you'll help a lot of people in your shoes never have to see this bug.  I started to install in once in windows, and after about 10 or 15 minutes of tinkering, figured my time would be better spent continuing integration with gpu.js, and then I'd reach that point, or someone (like you) would beat me there.

**Comment by robertleeplummerjr** [comment]
Going to go ahead and close because this isn't actionable here.  Can you open this in https://github.com/stackgl/headless-gl?
