### ISSUE TITLE
Request: URL change

### ISSUE THREAD

**Issue by peaceiris** [gpujs/gpu.js#429]
<img width="382" alt="screen shot 2019-02-28 at 13 29 30" src="https://user-images.githubusercontent.com/30958501/53541375-e9612a80-3b5c-11e9-9d4c-2e59206fb9af.png">

```diff
- http://gpu.rocks/
+ https://gpu.rocks/
```

**Comment by robertleeplummerjr** [comment]
Done!  Ty for catching.
