### ISSUE TITLE
Incompabilities between API of v1 and v2

### ISSUE THREAD

**Issue by Steve73** [gpujs/gpu.js#433]
I've noticed some incompabilities between the API of v1 and v2:

1. Many chainable shortcut methods are not working with v2 anymore (e.g. .setOutputToTexture(true) or .setFloatOutput(true)). At the same time .setGraphical(true) is still working

2. To get the canvas in v1 I had to use "var canvas = render.getCanvas();". In v2 I have to use "var canvas = render.canvas;". The method render.getCanvas() is not working anymore.

Maybe these incompabilities are wanted interface changes in v2. Then please just ignore this issue and close it.

On the other hand the incompabilities prevent me from using the exact some code for v1 and v2.

**Comment by robertleeplummerjr** [comment]
Before v2 is released, we're going to still use these items with deprecation warnings.  FYI.  This will be covered as well in documentation.  I was honestly just super surprised so many people started using v2 early on.

**Comment by robertleeplummerjr** [comment]
This is resolved in v2rc13
