### ISSUE TITLE
Declaring variables doesn't work like described in readme

### ISSUE THREAD

**Issue by SpaceK33z** [gpujs/gpu.js#435]
I'm following [this part](https://github.com/gpujs/gpu.js#declaring-variables) of the readme and it says I can do this:

```js
import { GPU } from 'gpu.js';

const gpu = new GPU({ mode: 'gpu' });

const myFunc = gpu
  .createKernel(function() {
    return [0.08, 2];
  })
  .setOutput([100]);

myFunc();
```

However when doing this it crashes with:

```
Uncaught Error: Error compiling fragment shader: ERROR: 0:148: '=' : dimension mismatch
ERROR: 0:148: 'assign' : cannot convert from 'const 4-component vector of float' to 'highp float'
```

Using `gpu.js@2.0.0-rc.2` and latest Electron. I'm still super super new to GPU.js so of course it could be my own fault, but my guess is that the readme is wrong.

**Comment by robertleeplummerjr** [comment]
You can only return arrays from functions inside the kernel, but the actual kernel return value, as it stands, needs to be a float, or use `this.color()`.  We'll address this after the release of v2, with node GPU support.

This is a duplicate, and it will be handled here: https://github.com/gpujs/gpu.js/issues/397

Ty for finding!
