### ISSUE TITLE
Error: Error compiling fragment shader: ERROR: 0:121: '' : No precision specified (sampler) 

### ISSUE THREAD

**Issue by S6Regen** [gpujs/gpu.js#437]
What does this mean?
Error: Error compiling fragment shader: ERROR: 0:121: '' : No precision specified (sampler)

**Comment by S6Regen** [comment]
It was an example off the internet but it mutated into this as was experimenting to try to get it to work:
//var GPU = require("gpu.js");
var gpu = new GPU();

var gpuKernel = gpu.createKernel(function() {
    const k=1;
    return k;
}).setOutput([2,2]);

console.info(gpuKernel());

**Comment by S6Regen** [comment]
I also got that error with the examples in the github download .zip file.

**Comment by S6Regen** [comment]
Problem here in Pale Moon browser:  
  
gpu-browser.js:9002:10

Relating to this line of code:
if (!gl.getShaderParameter(fragShader, gl.COMPILE_STATUS)) {
			throw new Error('Error compiling fragment shader: ' + gl.getShaderInfoLog(fragShader));
		}

Maybe its just a first time user not understanding something obvious.  Maybe its is because I don't use Google software or services like Chrome.

**Comment by robertleeplummerjr** [comment]
Can you share more of your source if there is any, and your environment details?  Is this web, node, , operating system, video card, etc.?

**Comment by S6Regen** [comment]
Linux 64 bit on a cheap laptop with cheap Intel CPU/GPU.  Pale Moon browser.

Pup-SysInfo Hardware Report (Summary), Thu 14 Mar 2019


▶—— BASE SYSTEM ——◀

PC Manufacturer: ASUSTeK COMPUTER INC.
Product Name: X451CA

Motherboard Vendor: ASUSTeK COMPUTER INC.
Product Name: X451CA

Intel(R) Pentium(R) CPU 2117U @ 1.80GHz
Max Speed: 3800 MHz
Current Speed of Core
Core Count: 2
Thread Count: 2

Frequency governor   : powersave
Freq. scaling driver : intel_pstate

l1tf:Mitigation: PTE Inversion
meltdown:Mitigation: PTI
spec_store_bypass:Vulnerable
spectre_v1:Mitigation: __user pointer sanitization
spectre_v2:Mitigation: Full generic retpoline, STIBP: disabled, RSB filling

temp1 (coretemp) : +64.0 C (high = +87.0 C, crit = +105.0 C)
Core 0 (coretemp) : +63.0 C (high = +87.0 C, crit = +105.0 C)
Core 1 (coretemp) : +59.0 C (high = +87.0 C, crit = +105.0 C)

Personal Storage File:
 Name: /zzzScPup/ScPup64save.2fs
 Total Size: 128 MB
 Free Space: 21 MB
 Location: partition sda1

Memory Allocation:
 Total RAM: 1816 MB
 Used RAM: 979 MB
 Free RAM: 837 MB
 Buffers: 22 MB
 Cached: 470 MB
 Total Swap: 0 MB
 Free Swap: 0 MB

 Actual Used RAM: 487 MB  	Used - (buffers + cached)
 Actual Free RAM: 1329 MB	Free + (buffers + cached)

Linux Kernel: 4.19.13-lxpup64 (x86_64)
Kernel Version: #1 SMP Mon Dec 31 11:38:41 GMT 2018
Build GCC: 8.2.0



Distro: ScPup64 19.01
Window Manager: JWM v2.3.6
Desktop Start: xwin jwm

**Comment by S6Regen** [comment]
@version 1.0.0-rc.10 that I found in some Mandelbrot code is working on my system.
The sampler I suppose reads the result back from the GPU, well I'm just guessing.  
And some way, somehow just a line of code is missing from that, that some way or somehow  doesn't affect  most systems but does mine. 
Anyway I think I can get on with writing code for the fast Walsh Hadamard transform and other things for AI with the older version.  I guess there were no normal use case problems with that and the newer versions are just minor fixes and more complex use case improvements.

**Comment by robertleeplummerjr** [comment]
This should now be resolved in v2 rc13.
