### ISSUE TITLE
ERROR Error: Error compiling fragment shader: ERROR: 0:145: 'pow' : no matching overloaded function found

### ISSUE THREAD

**Issue by konradst** [gpujs/gpu.js#438]
Do I understand correctly that in 2.x you're writing matching functions from scratch?

**Comment by konradst** [comment]
Sure. The gpu.js files are downloaded from bin folder. When you uncomment 1.10.2, the script works. in 2.x it doesn't.
`<!doctype html>
<html lang="en">
<head>
    <script src="gpu-browser-2.0.0-rc2.js"></script>
    
    
    <script>
        function task () {
            let result = 0;
            for (let t = 10; t > 0; t--) {
                for (let i = 5000000; i > 0; i--) {
                    result += Math.pow(i, -i);
                }
            }
            return result;
        };

        const gpu = new GPU({ mode: 'gpu' });

        const kernel = gpu.createKernel(task, {
            output: [1]
        });

        const result = kernel();

        alert(result[0]);
    </script>
</head>
<body></body>
</html>`

**Comment by robertleeplummerjr** [comment]
I know what this issue is here, and will be adding a fix in the next day or two.

**Comment by konradst** [comment]
thank you:)

**Comment by robertleeplummerjr** [comment]
I believe this has been resolved in [v2.0.0 rc 4](https://github.com/gpujs/gpu.js/releases/tag/2.0.0-rc.4) and I as well added [unit tests](https://github.com/gpujs/gpu.js/blob/4aa08ca39308be8864ff53c4498b02c31838cb3a/test/internal/backend/web-gl/function-node/astCallExpression.js#L6) to prevent this from popping up in the future.  Ty for bringing this to my attention!

Let me know if that doesn't work for you, and as well if this or anything resembling it come up in the future.
