### ISSUE TITLE
Returning Uint8Array instead of Float32Array

### ISSUE THREAD

**Issue by Steve73** [gpujs/gpu.js#441]
It seems kernels always return Float32Array for numbers. Is there a way to return other types, e.g. Uint8Array?

The transfer of data out of texture memory is very slow and the bottleneck in my application. So I reduce the amount of data transferred. Currently I'm packing 3 bytes into each float32. That's the best I can do. But float is still about the worst type to pack bytes into. To return simple bytes in a Uint8Array (or at least chunks of 4 bytes in a Uint32Array) would make a whole lot more sense!

**Comment by robertleeplummerjr** [comment]
I think this is very doable before v2 is released.

**Comment by Steve73** [comment]
@robertleeplummerjr: Would be awesome if this feature gets included in v2! Hoping...

**Comment by Steve73** [comment]
Great to see the progress! Congrats!

Does rc12 address my request for the Uint8Array return type? I've just experimented with the _precision_ setting but without any success. Could you explain the meaning of the new settings _precision_ and _optimizeFloatMemory_. Thank you!

**Comment by robertleeplummerjr** [comment]
>Does rc12 address my request for the Uint8Array return type?

It doesn't yet, I just this morning came up with an idea to handle this to a reasonably graceful degree.  By taking the `.renderOutput()` out of the internal `.run()` method, and placing it beside the `kernelShortcut()` function, which will not change the external api, we can then simply call the internal methods (note: not private, just internal) like this:

```js
const gpu = new GPU();
const kernel = gpu.createKernel(function(v) {
  return v[this.thread.x] + 1;
}, {
  precision: 'unsinged', // this is important
  output: [1],
});

// get regular output, calls (first time only) `.build([100])`, `.run([100])`, and then `.renderOutput()`
const regularOutput = kernel([100]);

// get raw output, calls (first time only) `.build([100])`, `.run([100])`, and then `.renderOutput()`
kernel.run([100]);
// for use with kernel option `precision: 'unsigned'`
const uint8ArrayOutput = kernel.readPackedPixelsToUint8Array();
```

If alternatively you used `precision: 'single'`:
Note: Most of this is copied from above, but changed the `precision` and the method called to get raw output:

```js
const gpu = new GPU();
const kernel = gpu.createKernel(function(v) {
  return v[this.thread.x] + 1;
}, {
  precision: 'single', // this is important
  output: [1],
});

// get regular output, calls (first time only) `.build([100])`, `.run([100])`, and then `.renderOutput()`
const regularOutput = kernel([100]);

// get raw output, calls (first time only) `.build([100])`, `.run([100])`, and then `.renderOutput()`
kernel.run([100]);
// for use with kernel option `precision: 'single'`
const float32ArrayOutput = kernel.readPackedPixelsToFloat32Array();
```

Taking this a step further, single `.renderOutput()` is assigned at kernel build, we could add another similar value that allows us to get the raw output.  Perhaps calling it something as simple as `.renderRawOutput()`.

SO... my long winded reply and proposal would be, I think, to move the `.renderOutput()` to be beside `.run()` and then to add `.renderRawOutput()`, so that accessing this value can be done in either case of `precision`:

```js
const gpu = new GPU();
const kernel = gpu.createKernel(function(v) {
  return v[this.thread.x] + 1;
}, {
  output: [1],
});

kernel.run([100]);
// Float32Array OR Uint8Array, depending on precision
const rawOutput = kernel.renderRawOutput();
```

Since this is simple enough, and actionable, I'll go ahead and add it for the next release candidate.  Likely out today or tomorrow.

**Comment by robertleeplummerjr** [comment]
Feature and unit test added here: https://github.com/gpujs/gpu.js/commit/2b45882c58a6db81ee6df985263e4f74127c718f

**Comment by robertleeplummerjr** [comment]
Unit test added here: https://github.com/gpujs/gpu.js/blob/2b45882c58a6db81ee6df985263e4f74127c718f/test/features/raw-output.js

**Comment by robertleeplummerjr** [comment]
Closing to keep organized.

**Comment by Steve73** [comment]
Thank you, it works. The returned float can now be read as 4 bytes.

Is there also a way to write to each of the 4 bytes in the kernel? Something like:

`
const kernel = gpu.createKernel(function(v) {
    return [1,2,3,4];
}, {
    output: [1],
    precision: 'unsigned',
});
` 

Basically something like this.color() which allows to set the bytes individually.

**Comment by robertleeplummerjr** [comment]
That currently should work, but only in `precision: 'single'`, as we can use float's, otherwise, it will fallback to CPU (or at least v2 rc14 will).

**Comment by Steve73** [comment]
Wow, yes it works! I didn't realize this before. That's great. So I can return up to 4 individual float32 values per return.

On a second thought this will sum up to 16 bytes per return.

Is there also a way to return 4 values within 4 bytes?

**Comment by robertleeplummerjr** [comment]
If you can propose it yea, we can find a way, but it'll need to be after v2.0's release.

>Is there also a way to return 4 values within 4 bytes?

There is a way, but it is not yet built inside GPU.js.  We'll have to wait till after v2 to have it built.  In the gpu, we have access to returning `vec4`'s of either 8 bit or 32 bit, currently.  If we used a `vec4` of 8 bit integers, which maps to a `Uint8Array()` and map that to an `Array(4)` (like we do with 32 bits now) would that be what you are talking about?  If so, we'd need a way to establish what bits to use.  I'll get it out of the way early: Proposal - `gpu.createKernel({ bits: 32|8 })`, likely 16 would come in time.

**Comment by robertleeplummerjr** [comment]
Does that proposal look like it would meet your needs?

**Comment by robertleeplummerjr** [comment]
>I didn't realize this before.

I forgot to mention, it is new for v2.  Just fyi.  Also, don't feel discouraged about needing to make the new proposal not part of v2, it shouldn't take that long to implement, and I don't want to hold up v2's release.
