### ISSUE TITLE
Examples with arrays involved are not working in 2.0.0-rc.6

### ISSUE THREAD

**Issue by Somebi** [gpujs/gpu.js#446]
**Array(2) examples: Using declaration**

```
const myFunc = gpu.createKernel(function() {
    const array2 = [0.08, 2];
    return array2;
}).setOutput([100]);

const result = myFunc();
console.log('result:', result);
```

```
/var/local/project/node_modules/gpu.js/src/backend/web-gl/kernel.js:347
			throw new Error('Error compiling fragment shader: ' + gl.getShaderInfoLog(fragShader));
			^

Error: Error compiling fragment shader: ERROR: 0:149: 'assign' :  cannot convert from 'highp 2-component vector of float' to 'highp float'

    at HeadlessGLKernel.build (/var/local/project/node_modules/gpu.js/src/backend/web-gl/kernel.js:347:10)
    at HeadlessGLKernel.run (/var/local/project/node_modules/gpu.js/src/backend/web-gl/kernel.js:414:15)
    at shortcut (/var/local/project/node_modules/gpu.js/src/kernel-run-shortcut.js:7:21)

```

**Comment by Somebi** [comment]
Anyhow possible to return an array from inside of kernel?

**Comment by Somebi** [comment]
Multiple examples involving arrays are not working. It seems mapping from GLSL constructs to js are somewhere broken or invalid.

**Comment by robertleeplummerjr** [comment]
I'm actually working on this right now, fyi.

**Comment by Somebi** [comment]
Hmm but i'm trying the latest version and it throws errors.
Could you please give some working example?
I have tested previous versions and they are telling "Warning: gpu not supported, falling back to cpu support"

**Comment by Somebi** [comment]
On node.js 10.10.0 and Linux (Ubuntu)

**Comment by robertleeplummerjr** [comment]
>I have tested previous versions and they are telling "Warning: gpu not supported, falling back to cpu support"

Because the main work for v2 was to get node working.

**Comment by robertleeplummerjr** [comment]
So using v1 in node will fallback to CPU.

**Comment by Somebi** [comment]
```
const myFunc = gpu.createKernel(function() {
    const array2 = [0.08, 2, 0.1];
    return array2;
}).setOutput([100]);
```
```

/var/local/project/node_modules/gpu.js/src/backend/web-gl/kernel.js:347
			throw new Error('Error compiling fragment shader: ' + gl.getShaderInfoLog(fragShader));
			^

Error: Error compiling fragment shader: ERROR: 0:149: 'assign' :  cannot convert from 'highp 3-component vector of float' to 'highp float'

    at HeadlessGLKernel.build (/var/local/project/node_modules/gpu.js/src/backend/web-gl/kernel.js:347:10)
    at HeadlessGLKernel.run (/var/local/project/node_modules/gpu.js/src/backend/web-gl/kernel.js:414:15)
    at shortcut (/var/local/project/node_modules/gpu.js/src/kernel-run-shortcut.js:7:21)
    at Object.<anonymous> (/var/local/project/matrix_calc.js:9:16)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)

```

**Comment by Somebi** [comment]
that is develop branch

**Comment by Somebi** [comment]
latest rc.6 same error

**Comment by robertleeplummerjr** [comment]
I'm aware, and I'm working on it.

**Comment by Somebi** [comment]
Oh, is there any workaround for this atm?

**Comment by robertleeplummerjr** [comment]
Possibly put it in cpu mode or use mapped kernel.

**Comment by Somebi** [comment]
Ty, will be waiting for updates. ;)

**Comment by Somebi** [comment]
Great project, ty for your work. ;)

**Comment by robertleeplummerjr** [comment]
Should be the next day or two I'll have it worked out.

**Comment by robertleeplummerjr** [comment]
Ty for your kind words.

**Comment by Somebi** [comment]
Would it be possible to return folded arrays like [[some_values],[some_values],[some_values]];
For example make matrix inversion inside kernel and return resulting matrix inverse.
And pass large set of integers [3,3]
This way i could check y % 3, make matrix inversion and return calculated matrix.

**Comment by Somebi** [comment]
In current situation i couldn't find a solution. ;(

**Comment by Somebi** [comment]
Any update?

**Comment by robertleeplummerjr** [comment]
I have not looked into the matrix solution yet, but am working out the the other logic to resolve this.  ETA, it will be sometime this weekend.  But if I run into delays, I'll be sure to post them.

This will solve the following:

* When float capabilities are available, there will be NO NEED for bit packing and unpacking.
  * This is HUGELY important for next level performance. 
  * bit packing and unpacking is already what we are currently doing, and it is still much faster generally than CPU.  The idea here would be that we don't need to do that, so we should see a substantial gain in performance
* Arrays in and out of base kernel.
  * Because of how the above works, we need this item to be solved, so I'm finally just doing it.
* Graphics in and out of base kernel, not just writing to graphics.
* There are a host of other things that have been resolved, including end to end type detection and TONS of bugs, along with unit tests.


Working on this very strictly, early in the morning before work, on breaks, lunch, and after work... It will be solved very soon!

Ty for all your motivation and everyone else's on this.

**Comment by Somebi** [comment]
I think your project requires more attention from the public. Need to advertise it somehow. As an example, you could post something to Three.js project or contacts guys who are involved into it's development.
I think this cooperation will bring more people to this project.

I'm myself using this project to drop tons of matrix calculations and manipulations in my project to GPU.
GPU libs and GLSL was always a headache for me. Haven't coded anything in 3d myself, tried only Three.js earlier. Raw webgl is a bit complicated.

Btw you have to write and better draw some explanation about how things are going in the background of your project. I mean the basic workflow, about data flow and how they are being used internally and how are being passed out (i'm talking about output parser/formatter).
Because it took me some time to understand how things are working and that data are pre-formatted and presented in "3d space/dimension".

Anyway, waiting for your updates to test that in a real stress test here.

**Comment by robertleeplummerjr** [comment]
Status tonight on this issue:
* Got raw (like one flattened array) output webgl2 working for
  1. kernel generating array and output
  2. array in to array out
  3. array in to texture to array output

Both webgl and headlessgl both support similar behaviour, so I'm going to be adding that tomorrow, but first, I broke some other areas, and I'll be working on clean up tomorrow, then formatting the flattened array to a more correct value, adding tests, etc.

>I think your project requires more attention from the public.

Though this is probably not anything what you meant: I actually wanted to make "an artistic commercial" (if you could call it a commercial, though it isn't really, more a celebration of simplicity) in a similar style to Apple's "Crazy ones" commercial.  I wrote the music, visual progression, verbiage, and most of the dialog that'd be used, but have yet to meet anyone interested in contributing as an open source directory, for an open source project.  World: Invitation open!

To more specifically reply to your comment: I agree, my main thrust is mostly to finish what the original authors prototyped.  I simply want it to be fast, and to use it, and provide a stable platform that offers GPU acceleration with little need for insight into all the specifics of GPU, other than the very basics like threading.

Would you be interested in helping out with some visualizations for v2 documentation?

**Comment by Somebi** [comment]
Not good at this, I'm more high-load architector than 3d guru. I'm more
like dev-ops and server-side dev.

Ty for your update. Staying tuned.

I would be more interested in creation of rpc-gpu for node based on your
project in the future, when I'll have more free-time ;)

вс, 31 мар. 2019 г., 4:15 Robert Plummer <notifications@github.com>:

**Comment by robertleeplummerjr** [comment]
What is "rpc-gpu"?  The v2 of this project should work fine for node.

**Comment by Somebi** [comment]
Remote procedure call for your project. To scale GPU calculations with node.js on GPU servers.

**Comment by Somebi** [comment]
Any updates, related to "array return from kernel" feature?

**Comment by Somebi** [comment]
Serverless gpu idea based on your project would be interesting too.

**Comment by Somebi** [comment]
Heya, got some news?

**Comment by robertleeplummerjr** [comment]
>Serverless gpu idea based on your project would be interesting too.

So long as serverless has a GPU available, or if fallback is ok, gpu.js should be compatible.  

>Any updates, related to "array return from kernel" feature?
>Heya, got some news?

I'm chipping away at it still.  This week has been terrible for meetings and high priority items, but when I get personal time (which I'm making sure I get) I've been working on this.

There are several different "render strategies" that are introduced, and I'm just trying to organize the logic for this.  I expect to have most of this done by the 7th, if not beforehand.  The logic introduces the following (notice I'm as well adding raw Uint8Array output for those who asked) render strategies:

* PackedPixelToUint8Array
* PackedPixelToFloat
* PackedPixelTo2DFloat
* PackedPixelTo3DFloat
* PackedTexture
* FloatPixelToFloat32Array
* FloatPixelToFloat
* FloatPixelTo2DFloat
* FloatPixelTo3DFloat
* FloatPixelToArray2
* FloatPixelTo2DArray2
* FloatPixelTo3DArray2
* FloatPixelToArray3
* FloatPixelTo2DArray3
* FloatPixelTo3DArray3
* FloatPixelToArray4
* FloatPixelTo2DArray4
* FloatPixelTo3DArray4
* FloatTexture

The majority of the the time is for organizing and testing.  I did, however, double check with the guys on freednode opengl and as well the Khronos WebGL specification to ensure I'm utilizing integer buffers correctly, all green lights there.

Sorry it is taking so long, we'll have it soon enough!

**Comment by Somebi** [comment]
All trust in you right now :)
Can't wait to get my hands on it.

**Comment by robertleeplummerjr** [comment]
As of 3 minutes ago I have (ignore the red and look at success from webgl2):
<img width="1440" alt="Screen Shot 2019-04-06 at 5 55 24 PM" src="https://user-images.githubusercontent.com/679099/55675778-44d9b300-5895-11e9-865d-3765fdb4a050.png">


I'll see if I can get this committed tonight, but will get webgl1, headlessgl, and cpu working first.

**Comment by Somebi** [comment]
Whoa! :) great news! seems everything going well, will have to wait a bit more.
Thank you for your hard work.
Waiting for a release or some working branch. ;)

**Comment by Somebi** [comment]
Heya, any update?

**Comment by robertleeplummerjr** [comment]
All of webgl2 minus the direct Float32Array, UInt8Array, and the array that contains all integers covered by float 32 array are working, I am having a hard time tracking down where that bug is coming from, so I thought I'd go ahead and get webgl and headlessgl up to date, and then revisit.

Been a very busy couple of weeks, very sorry for this taking so long.

**Comment by robertleeplummerjr** [comment]
I'm knocking things out pretty fast this morning, I *will* have something today committed.

**Comment by Somebi** [comment]
It's ok no problem. Ok, waiting for commit. Will try to make something out of it right away. ;)

**Comment by robertleeplummerjr** [comment]
This branch has the goods: https://github.com/gpujs/gpu.js/tree/rc7-cleanup

I'll merge and release a new candidate as soon as it is totally cleaned up, and all tests passing.  On the subjects of texts passing: There is now much better support for float handling, but there is an edge case I'm working through that has to do with the `immutable` option, I'm sure I'll have it in a day or two. This is passing 99% of tests, and there is some debugging and todo's left, but should give you most of what you need.

Note: I've not started working on the headlessgl upgrades todo with this refactor, but I'll get to it in the coming days.

**Comment by Somebi** [comment]
Thank you very much. Will take a look and report.

**Comment by Somebi** [comment]
Heya, started to code a little bit.
What conditionals can be used inside kernel? If need to check response type, how can this be done?
Check whether returned value is array or empty/null/false.
`Error: Unhandled binary expression between Array(3) & Number on line 7, position 1`
It throws errors when trying to compare different types as i understand.

**Comment by Somebi** [comment]
As i understand, you can't know the size or created array, like Array.length. Have to pre-provide all required length into kernel as inputs.

**Comment by Somebi** [comment]
Folded arrays not supported as i understand? Thinking how to return created inversed matrix. Can't return [1,2,3,4,5,6,7,8,9] or folded arrays [[1,2,3], [1,2,3],[1,2,3]].
Any ideas of how to return inversed matrix?
Can't create identity matrix inside kernel as well.
What primitives are available inside kernel?

**Comment by robertleeplummerjr** [comment]
>What conditionals can be used inside kernel?

(Great question, we should add this to the Docs)
Properties that can be used are:

Current index:
* `this.thread.x`
* `this.thread.y`
* `this.thread.z`

Output size:
* `this.output.x`
* `this.output.y`
* `this.output.z`

>If need to check response type, how can this be done?

Standard operators and math functions for evaluating variables is available.  Bit operators will likely land after v2.

>Check whether returned value is array or empty/null/false.

I'll need to investigate this.

>It throws errors when trying to compare different types as i understand.

Strongly typed end to end variables, arguments, and functions are in v2, if there is a use case that isn't covered we'll add it with unit tests.  We're trying to cover everything on v2, but some items may be missed, but will be added as they are brought to our attention.  The important thing is that the framework is now fully robust enough to handle just about anything we can through at it.

>As i understand, you can't know the size or created array, like Array.length. Have to pre-provide all required length into kernel as inputs.

That is correct for the time being, there isn't an easy way to inspect the current array size.  I believe the hope originally was those sizes would mostly be static, or known before calculation.  That being said, this would be a very useful feature.  I can easily see how useful it'd be to:
```
const argumentDepth = argument.length;
const argumentHeight = argument[0].length;
const argumentWidth = argument[0].length;
const cDepth = this.constant.c.length;
const cHeight = this.constant.c[0].length;
const cWidth = this.constant.c[0][0].length;
```

Let's make this a feature request!

>Folded arrays not supported as i understand?

Cubes (3d) of numbers, matrices (2d) of numbers, and arrays (1d) of numbers, are currently supported, [amongst others](https://github.com/gpujs/gpu.js#supported-input-types).

>Any ideas of how to return inversed matrix?

This is one of my favorite kernels:
```
const gpu = new GPU();
// added for clarity
const standardMatrixKernel = gpu.createKernel(function(matrix) {
  return matrix[this.thread.y][this.thread.x];
}, { output: [3, 3] });

const inverseMatrixKernel = gpu.createKernel(function(matrix) {
  return matrix[this.thread.x][this.thread.y]; // note the flipped x and y coordinate
}, { output: [3, 3] });

const matrix = [
  [1,2,3],
  [4,5,6],
  [7,8,9],
];

const inversed = inverseMatrixKernel(matrix);

```

>Can't create identity matrix inside kernel as well.

I'll need more detail on this, but _inside the kernel_ arrays of 4 or less are currently supported in arrays, larger than that are not.  They could easily be created in their own kernel, however.

>What primitives are available inside kernel?

I believe this was answered above.

**Comment by Somebi** [comment]
I think this can be close. By now it's fixed. Thank you very much again. At least this will soon be merged into the main branch as i understand.

**Comment by Somebi** [comment]
The author is awesome. Helped me to solve my issues and understand the project. Additional thanks for that as well.

**Comment by robertleeplummerjr** [comment]
Ty!
