### ISSUE TITLE
Failure when using in more than one jest suite

### ISSUE THREAD

**Issue by swistak35** [gpujs/gpu.js#449]
I've added a usage of GPU.js to my code and found out that some of my tests started to fail. It looks that only the first jest suite is behaving correctly in tests, and the subsequent ones, despite the cleanup, are failing with error:

```
    TypeError: framebufferTexture2D(GLenum, GLenum, GLenum, WebGLTexture, GLint)

      3 | describe("Suite2", () => {
      4 |   it('test', () => {
    > 5 |     const gpu = new GPU()
        |                 ^
      6 |     gpu.destroy()
      7 |   })
      8 | })

      at WebGLRenderingContext.framebufferTexture2D (node_modules/gl/webgl.js:2570:11)
      at resizeDrawingBuffer (node_modules/gl/webgl.js:4476:27)
      at Object.allocateDrawingBuffer (node_modules/gl/webgl.js:4459:3)
      at createContext (node_modules/gl/node_index.js:105:9)
      at Function.setupFeatureChecks (node_modules/gpu.js/src/backend/headless-gl/kernel.js:25:17)
      at Function.get isSupported [as isSupported] (node_modules/gpu.js/src/backend/headless-gl/kernel.js:16:8)
      at GPU.chooseKernel (node_modules/gpu.js/src/gpu.js:175:24)
      at new GPU (node_modules/gpu.js/src/gpu.js:120:8)
      at Object.it (test2.test.js:5:17)
```

I've reproduced it only in Jest for now. Also, note that there can be multiple instances of GPU in one jest suite and it works just fine, the problem is to create GPU.js instance in two different suites. I'm not sure what exactly jest is using internally (some threads maybe?), but it would be nice to get some guidelines how to fix that.

I've prepared minimal reproduction repository here: https://github.com/swistak35/gpu-js-fail-example

**Comment by robertleeplummerjr** [comment]
What is the test runner you are using?

**Comment by swistak35** [comment]
A default one, `jasmine2`.

**Comment by robertleeplummerjr** [comment]
I believe this to be the culprit: https://github.com/tensorflow/tfjs/issues/540
Would you be in a position to try out: https://github.com/tensorflow/tfjs/issues/540#issuecomment-408716995 ?

**Comment by swistak35** [comment]
We were already using `testEnvironment: "node"`. I can add that to the example repository because it's not reflected in it, but that doesn't fix the issue.

**Comment by swistak35** [comment]
After a little bit longer investigation, it seems that `headless-gl` and `jest` have already a history of not liking each other: https://github.com/facebook/jest/issues/2029 (the suggested workaround, `--no-cache`, didn't help me, but still, the issue was there)

I've wanted to use `node-webgl` backend instead, but this one on the other hand looks unmaintained ( https://github.com/mikeseven/node-webgl/issues/64 ).

In the end, the `cpu` mode works, and when it comes to tests, it's good enough for me :) So I think it's not really gpu.js issue, feel free to close it if you wish :)

**Comment by robertleeplummerjr** [comment]
Ty for the update.  We will continue to investigate this issue.
