### ISSUE TITLE
Passing arrays of strings to / from kernels [Feature Request]

### ISSUE THREAD

**Issue by wbrickner** [gpujs/gpu.js#450]
Hello,

I'd like to be able to pass arrays of strings to/from my kernels.
As I understand it, this is currently impossible.  This feature is valuable to me for applications in text analysis, specifically genomic analysis.

I can try to use a gross hacky way to do this, which involves passing string data to the kernel as an array of integers representing characters or sub-strings, and then converting back on the fly.

Let me know if it makes sense to include this feature in GPU.js.

**Comment by robertleeplummerjr** [comment]
We can find a way to encode it, and have the transpiler work out the representation.  So this should not be an issue.

**Comment by robertleeplummerjr** [comment]
To be clear: this isn't currently a feature, but this proposal shouldn't be too terribly difficult.

**Comment by wbrickner** [comment]
For now, I've used 

```
const numbers = new Array(str.length)
for (var j = 0, jlen = str.length; j < jlen; ++j) {
  numbers[j] = str.charCodeAt(j)
}
// ...
```

I've got no idea how to go about modifying the transpiler.

**Comment by robertleeplummerjr** [comment]
Exploring this idea, what would you be doing with the string?

**Comment by wbrickner** [comment]
I was thinking I could leverage the parallelism to search for substrings in extremely large strings, or something similar.

I've benchmarked the GPU and CPU versions of my code, and the CPU version runs hundreds/thousands of times faster than the GPU version (😭), even on very large inputs (all works of Shakespeare)

Maybe my specific application/implementation is not a good use of the GPU?

**Comment by HarshKhandeparkar** [comment]
GPU is good for heavy(repetitive) maths operations. Secondly, maybe the way you implemented it is (probably) not parallelized

**Comment by HarshKhandeparkar** [comment]
Can you post some code of your actual string analysis?

**Comment by HarshKhandeparkar** [comment]
If you are converting characters back to string in the kernel itself, then I think it will slow it down significantly. If you are doing that, try converting the whole output array of charCodes to characters after the full analysis is complete.

**Comment by wbrickner** [comment]
I don't bother converting back to strings inside the kernel, I just look for the given substring. I'm a bit new to GPU.js, and my approach was likely naive. Let me find my code and maybe we can identify some anti-patterns.

**Comment by wbrickner** [comment]
I think there are some bugs in this code, and it's a little sloppy, but I don't think those facts should affect performance in this case.

**Results at bottom.**

```javascript
const { GPU } = require("gpu.js")

const gpu = new GPU()

function kernelCore(numbers, pattern, numLength, patternLength) {
    for (var j = 0, idx = this.thread.x; j < patternLength; ++j) {
        if (idx >= numLength) { return -1 }
        if (pattern[j] !== numbers[idx]) { return -1 }
        idx++
    }

    return this.thread.x
}

function getKernel(numbersLength) {
    const name = numbersLength + ""

    if (!this.kernels[name]) {
        console.info("Creating kernel...")
        this.kernels[name] = gpu.createKernel(kernelCore).setOutput([numbersLength])
    } else {
        console.info("Reusing kernel...")
    }
    
    return this.kernels[name]
}

function resultFilter(x) { return (x !== -1) }

function findOccurances(numbers, pattern) {
    this.kernels = this.kernels || { }
    const kernel = getKernel.apply(this, [ numbers.length ])

    const result = kernel(numbers, pattern, numbers.length, pattern.length)
    return result.filter(resultFilter)
}

function stringToNumbers(string) {
    const stringLength = string.length
    const nums = new Array(stringLength)

    for (var j = 0; j < stringLength; ++j) {
        nums[j] = string.charCodeAt(j)
    }

    return nums
}

function toNumbers(string, substring) {
    const numbers = stringToNumbers(string)
    const pattern = stringToNumbers(substring)
    return { numbers, pattern }
}

const fs = require("fs")
const shake = fs.readFileSync("./t8.shakespeare.txt", "utf8")

const startConv = process.hrtime()
const { numbers, pattern } = toNumbers(shake, "and")
const durrConv = process.hrtime(startConv)

findOccurances(numbers, pattern)
const startOcc = process.hrtime()
const occurances = findOccurances(numbers, pattern)
const durrOcc = process.hrtime(startOcc)

const startMatch = process.hrtime()
const cpuOccurances = []
outerLoop:
for (var j = 0, jlen = numbers.length, klen = pattern.length; j < jlen; ++j) {
    for (var k = 0; k < klen; ++k) {
        if (j + k > jlen || numbers[j + k] != pattern[k]) {
            cpuOccurances[j] = -1
            continue outerLoop;
        }
    }
    cpuOccurances[j] = j
}
const results = cpuOccurances.filter(resultFilter)
const durrMatch = process.hrtime(startMatch)

console.log(results)
console.log(occurances)

console.log("[Conversion]\t", durrConv[0] * 1E3 + durrConv[1] * 1E-6, "ms")
console.log("[GPU Occurances]\t", durrOcc[0] * 1E3 + durrOcc[1] * 1E-6, "ms")
console.log("[CPU Occurances]\t", durrMatch[0] * 1E3 + durrMatch[1] * 1E-6, "ms")
console.log("[CPU matches GPU]\t", JSON.stringify(results) === JSON.stringify(occurances))
```

**Results**

```text
[Conversion]        30.345792999999997 ms
[GPU Occurances]    1276.506683 ms
[CPU Occurances]    181.032734 ms
[CPU matches GPU]   false
```

The code doesn't seem to work in one case or another, as the output does not match.
Aside from that, am I doing anything obviously wrong performance-wise?

Thank you.

**Comment by HarshKhandeparkar** [comment]
First of all:
1. Never use if...else statements inside the kernel. You are also using if else inside a for loop inside a kernel. That will seriously hinder performance.
2. Try running `kernel.build()` in the getKernel method. This is something I learnt yesterday.
Like
```js
function getKernel(){
  // First few lines
  this.kernels[name].build(numbers, pattern, numbers.length, pattern.length)
  return this.kernels[name];
```

Now please note one thing that you have to run the build function with the final parameters or similar parameters. Similar data types. If you are going to use the kernel with `array, array, integer, integer)` arguements, you will have to build it with the same type of arguements.

Another thing is that you have to return the kernel itself and not what is returned by the build method.
You can also have a look at [this](https://codepen.io/imnotacoder/pen/KEyYjm) codepen.

I hope this helps you :)

**Comment by HarshKhandeparkar** [comment]
And yes. If else will seriously reduce performance.

**Comment by HarshKhandeparkar** [comment]
I don't know why your code isn't matching. You will have to look at it yourself as I don't quite understand it fully yet. I don't have time right now. I will dig into it later and tell you if I find something.

**Comment by wbrickner** [comment]
That's very interesting that if/else inside loops causes such a large performance drop, do you know why? Is it just inherent to GPUs that branching is costly compared to other operations?

**Comment by HarshKhandeparkar** [comment]
I am not sure why but I think that the gpu processing cores cannot compute boolean statements. This is my guess. @robertleeplummerjs am I right? What is the correct reason?

**Comment by Somebi** [comment]
I think best practices list is required in the docs. Examples of `do` and `don't`. Facebook-like style docs. At least the most critical moments which can lead to dramatic performance drop.

**Comment by wbrickner** [comment]
I agree, as a GPU.js beginner, I had zero intuition about this (big) problem with my code.

@HarshKhandeparkar Why do you recommend using the `.build()` method?  I see you're passing the actual parameters, is this somehow better for performance?  Can certain things be determined by examining the data provided which leads to more optimized shaders or something?

**Comment by wbrickner** [comment]
Also, is looping terribly bad for performance?  Some problems look like they must be looped, but maybe there are clever ways to get around this for some problems where performance suffers.

**Comment by HarshKhandeparkar** [comment]
Ok 
1. Looping isn't bad at all. Using if else inside loops is terribly bad beacuse if else itself is terrible. Terrible*iterations = performance drop.
2. I told you to run the build function as when you run the kernel for the first time, it is built if it isn't already. The `createKernel` method just prepares a kernel template for compilation but it isn't compiled. It is compiled at runtime or when the `build` method is called if it is called.
3. I told you to build it as you were also including the compile time in your benchmark.

**Comment by robertleeplummerjr** [comment]
Hey guys, I think the biggest thing is to reduce the logic in the kernel to what you *need* to do.  If statements and loops (in every good loop, there are at least 1 if statements) do affect performance, but let a profiler try and tell you about how they affect performance.  If we just say "all if statements will make it slow", we are just doing premature optimization...  Which I'm told is the "root of all evil", lol.

Things to note:  Strings don't even exist in glsl as far as I'm aware.  The language doesn't even have them spec'ed in, so as to focus on number computation.

**Comment by wbrickner** [comment]
That's a good point.  Can you help me understand why if/else statements can be bad, maybe we can more narrowly define the anti-pattern?

As for the bit about strings, could GPU.js provide a function in JS user-land which converts the strings to an optimized numerical representation, and then it could appear that a magical function already exists inside the scope of the kernel function which "pulls" the string into the scope, and higher-level operations can be done, so the user doesn't need to think about the fact that it's an array of floating point numbers?  This function would be transpiled into the code which operates on the floating points, hiding the truth of the operation.

This could actually be an interesting way to pass arbitrary data to/from the kernel in a performant way. If we're clever, we could pack arbitrary data (think msgpack) into a binary representation, chunk into floating points, then reconstruct on-the-fly when we need to access things in the kernel.

Even objects with a self-references, nested properties and other fancy qualities could be efficiently represented using some binary encoding (again, think msgpack).

That's how I would do it, but it wouldn't be trivial to implement, and passing arbitrary data to/from the kernel may not be very valuable to the majority of users.

**Comment by wbrickner** [comment]
I apologize, this idea may be totally contrary to your real point, which is to simplify the logical structure of the kernel as a conscious design choice.  

I can dream of a world in which I can run a cursed web server on my GPU!

**Comment by robertleeplummerjr** [comment]
>could GPU.js provide a function in JS user-land which converts the strings to an optimized numerical representation

That would be exactly how I would do it, and I see no problem with doing this, so long as we can land on a reasonable feature request.

Just experimenting with the idea:

```js
const kernel = gpu.createKernel(
  function(encodedString) {
    // What types of abilities should we plan for here?
  }
);
```

I ask the question "What types of abilities should we plan for here?" above to get myself (and you guys if you like) to think what type of logic we need to expose for the end user.  This is going to be fun!

* I suppose string modifiers or operations (concatenation, substring) may be out of the question, but maybe not so long as we can join the logic to texture operations
* We have index lookup (`string[index]`) would likely be fine
* We'd have to account for string literals (`string[index] === 'a'`)
* `.indexOf()` would be nice

Can you guys think of any others?  Just getting started, and I apologize for leaving any out.

>I apologize, this idea may be totally contrary to your real point, which is to simplify the logical structure of the kernel as a conscious design choice.

>I can dream of a world in which I can run a cursed web server on my GPU!

I see no reason to put your ideas down, I think it is perfectly viable and related.  After all, those who are crazy enough to change the world...

**Comment by wbrickner** [comment]
I personally think the convenience of being able to treat them like they're strings, and put string literals in the kernel would be enough, with maybe some convenience functions like `.charCodeAt()` and `.indexOf()` like you say.

**Comment by HarshKhandeparkar** [comment]
Can we just return a byte for each character and the byte will be recognised as a character on the js side but as a normal number on GLSL side. @robertleeplummerjr.

So:
1. Convert strings as array or bytes into their respective char codes on the gpu itself.
2. Do all the computation on the charcodes.
3. Convert final char codes back to bytes
4. Give the bytes to js. JS can then recognise it as a string.
5. The bytes can be stored on a texture and GLSL will think of it as coordinates.
6. We can also create an ASCII charmap to convert bytes to charcode in decimal. This is kind of like the process used for converting different coordinate types (clip, world etc)

@robertleeplummerjr
Btw, why does logic in a kernel take time?

**Comment by wbrickner** [comment]
As an aside, I've written a module which converts arbitrary JS data to an array of floating-point numbers, the binary representation of which when taken together contains a near-optimal representation of the original data (thank you `msgpack`).  

The only remaining hard part would writing GLSL code which can parse the structure selectively, only pulling out what is requested by the JS kernel.  This would require additional transpilation of the kernel, discovering which data is being accessed and how, and then inserting the GLSL code to tease out the data using bit-shifts etc.  Maybe this is too big a task to consider, I've never touched GLSL nor do I have a graphics background.

**Comment by RyanRutkin** [comment]
Curios where this stands now, nearly three years later. Are string types supported? String index lookup? Any of the suggested string methods? Can this issue be closed?

**Comment by robertleeplummerjr** [comment]
I don't think this is feasible from a hardware and sanity standpoint.  Unless someone can think of a way and present it.  Closing this now because I don't feel that it is actionable.
