### ISSUE TITLE
Documentation Needed.

### ISSUE THREAD

**Issue by Greg-Tarr** [gpujs/gpu.js#451]
The "Pipelining" section is very under documented. Apparently this can "result in extremely fast computing" but the documenting does not describe how and/or when to implement this.

> Pipeline is a feature where values are sent directly from kernel to kernel via a texture. This results in extremely fast computing. This is achieved with the kernel option pipeline: boolean option or by calling kernel.pipeline(true)

Likewise, I feel sections on **Useful Kernels** and **How to Write efficient Kernels** would be much appreciated.

**Comment by robertleeplummerjr** [comment]
Documentation has been added and as well backwards compatibility in [v2 rc7](https://github.com/gpujs/gpu.js/releases/tag/2.0.0-rc.7).  Added your note to the site's refactor issue.  Ty for help.  Closing as actionable item with this repo has been resolved.
