### ISSUE TITLE
[Feature Request] Dynamic kernel output size

### ISSUE THREAD

**Issue by Somebi** [gpujs/gpu.js#452]
I'm currently finished developing matrix inverse functionality based on gpu.js with the help of Robert and after stress testing, we have noticed that output transformation from texture to array is very slow because output data was huge.

Calculations itself was approximately 4x~ times faster than CPU, but because of that transformation Texture.toArray() overhead, there were no benefits in speed between CPU and GPU.

In my case, this could be solved by moving decision logic of whether output data worth returning or not into the GPU kernel. This way I could get rid of wast amount of not valid/not required output inside kernel and return only the required ones.

The problem is, that currently kernel output size and dimensions are defined at the kernel creation time.

- Setting dynamic if possible, else fixed approximate/expected size of result/output buffer
- Allow skip/void any kernel iteration result

What do you think?

**Comment by HarshKhandeparkar** [comment]
This is impossible. Isn't it? We actually need to have an output size because gpu.js doesn't create an putput array but computes as many operations as the size of the output array in parallel. Please let me know if I have said something wrong.

**Comment by HarshKhandeparkar** [comment]
GPU.js has to book a texture in advance so ...

**Comment by HarshKhandeparkar** [comment]
@robertleeplummerjr?

**Comment by Somebi** [comment]
As i understand the main limitation is that renderer is rendering to a single texture at a time, but here i found this:
https://developer.mozilla.org/en-US/docs/Web/API/WEBGL_draw_buffers

```
  gl_FragData[0] = vec4(0.25); 
  gl_FragData[1] = vec4(0.5);
  gl_FragData[2] = vec4(0.75); 
  gl_FragData[3] = vec4(1.0);
```

I'm wrong?

**Comment by Somebi** [comment]
So you can pick as much data as you like, make calculations and then split result to multiple textures. On javascript side just synchronously read from all textures to receive correct results.

**Comment by Somebi** [comment]
```
  gl_FragData[0] = calculated_matrix3x3[0];
  gl_FragData[1] = calculated_matrix3x3[1];
  gl_FragData[2] = calculated_matrix3x3[2];
```

Or same with 4x4 matrices, or even 512x512 matrices writting and reading from 512 textures if memory overhead per texture is not very big.

**Comment by Somebi** [comment]
Stupid example of results parsing:
```
for(let i=0;i<matrices_calculated_amount;i++) {
     const matrix_row1 = textures[(i%3)+i][0];
     const matrix_row2 = textures[(i%3)+i][0];
     const matrix_row3 = textures[(i%3)+i][0];
     const matrix3x3 = [matrix_row1, matrix_row2, matrix_row3];
     results.push(matrix3x3);
}
```

**Comment by Somebi** [comment]
`document.createElement("canvas").getContext("webgl").getSupportedExtensions().join("\n")`

`Version 73.0.3683.103 (Official Build) (64-bit)`

It seems google chrome already supporting this feature.

**Comment by Somebi** [comment]
Currently gpu.js is doing it this way:

`gl_FragData[0][0] = kernelResult;`

**Comment by Somebi** [comment]
https://github.com/stackgl/headless-gl/releases

New features:
WEBGL_draw_buffers extension support

The exact version gpu.js uses.

**Comment by HarshKhandeparkar** [comment]
Ok. Thanks for taking the time to enlighten me. I was just curious to know about. I don't know much about this.

**Comment by Somebi** [comment]
Yesterday I tried to implement that feature based on gl module and I was always receiving an error at the end. Not sure what does that error mean... Will post details in a while.

**Comment by Somebi** [comment]
https://gist.github.com/Somebi/76e58fdb07a2dd2b8c59ef7f77b26936

**Comment by Somebi** [comment]
FRAMEBUFFER_UNSUPPORTED code is returned. Maybe it's because of my driver's or video card. Can you test this code on your side?

**Comment by Somebi** [comment]
But currently, more importantly to skip/void results based on simple conditional. If data is not required, then just skip it if that possible.

**Comment by Somebi** [comment]
Rob is currently busy with releasing v2 as i understand. So this stuck as it is for now. Will have to use CPU scaling in my project it seems. gpu.js is not usable at the moment for my project, data round-trip overhead kills all the benefits of using GPU.
Have to keep maximum logic inside kernels to benefit in my opinion.
But i can't put simple conditional, to decide what is required and what is not for the final output.
Let's wait, what Rob will say about it.

**Comment by robertleeplummerjr** [comment]
This has been added here: https://github.com/gpujs/gpu.js/commit/aca274198db202885e2074a3f445f6f81494b6a0

Closing to keep organized.  This will be released in a few days.
