### ISSUE TITLE
Math.pow support

### ISSUE THREAD

**Issue by HarshKhandeparkar** [gpujs/gpu.js#455]
@robertleeplummerjr why isn't `Math.pow` supported?

**Comment by HarshKhandeparkar** [comment]
@Somebi do you know anything about this?

**Comment by robertleeplummerjr** [comment]
This is fully supported by v2, which is on release candidate 7.  It is going to be released very soon as fully stable.  Here is proof of it working:
https://jsfiddle.net/robertleeplummerjr/yb5um83s/2/

**Comment by HarshKhandeparkar** [comment]
Great!
