### ISSUE TITLE
Bool is not yet supported

### ISSUE THREAD

**Issue by hey24sheep** [gpujs/gpu.js#457]
I have been trying to create a reusable bool condition like so 

```
// sample code
let s = r > 0.5;
```

**Error will be -**  **An error occurred compiling the shaders: ERROR: 0:173: '=' : cannot convert from 'bool' to 'highp float'**

```
// GLSL Code
float user_s=(user_r>0.5);
```

Alternate method (trying to parse manually using Boolean())

`let s = Boolean(r > 0.5);`

**Error will be -  An error occurred compiling the shaders: ERROR: 0:173: 'Boolean' : no matching overloaded function found**

How could I create something like this ? I have to use If/Else and I am trying to use a variable instead of using it directly multiple times. (My conditions are more complex)

**Comment by robertleeplummerjr** [comment]
Fixing this now, fyi.

**Comment by hey24sheep** [comment]
Okay, thank you for the update.

**Comment by robertleeplummerjr** [comment]
Now supported as variables, arguments, and constants in https://github.com/gpujs/gpu.js/releases/tag/2.0.0-rc.13 .

Let us know if you have any more issues.

**Comment by hey24sheep** [comment]
@robertleeplummerjr  We cannot && concat conditions?
