### ISSUE TITLE
[Feature Request] Create canvas context with alpha in a web worker

### ISSUE THREAD

**Issue by hey24sheep** [gpujs/gpu.js#460]
I would like to know how could I create a canvas with alpha in a web worker? I am trying to use your approach given in offscreen canvas. I wasn't able to create it. 

I have one more suggestion, I haven't read all the code yet. But, I think probably it is here.
Can't we add alpha input in setting and set here, for line 105 settings [here] (https://github.com/gpujs/gpu.js/blob/7ec15719a5ef0fc6d34b6d2f212b1b178457894b/src/backend/web-gl2/kernel.js). I would like to help but I don't know if I am right or not. 

Thank You

**Comment by robertleeplummerjr** [comment]
https://github.com/gpujs/gpu.js#alpha

You just need to give your configured context to `new GPU()` like this:

```js
const canvas = document.createElement('canvas');
const context = canvas.getContext('webgl2', { premultipliedAlpha: false });
const gpu = new GPU({ canvas, context });
```

If you'd like to make a suggestion to include this in the GPU.js api, that'd be great!

**Comment by hey24sheep** [comment]
@robertleeplummerjr I know I could do that. I am trying to say, why can't we just give a kernel setting to enable alpha in initCanvas function? Because I wan't to create a canvas in web-worker and that is not possible for me because I can't access Dom in Web-Worker.

**Comment by robertleeplummerjr** [comment]
The same holds true there I believe: 

```js
const canvas = new OffscreenCanvas(width, height);
const context = canvas.getContext('webgl2', { premultipliedAlpha: false });
const gpu = new GPU({ canvas, context });
```

**Comment by robertleeplummerjr** [comment]
I open to adding the feature, but it needs to be presented.  If you'd like to present it, put some thought into how it can be added in a simple manner, and the community will review it.

**Comment by hey24sheep** [comment]
Okay, Thank you.
