### ISSUE TITLE
GetPixels creates upside down image

### ISSUE THREAD

**Issue by hey24sheep** [gpujs/gpu.js#461]
Get pixels function is giving an array which is creating an inverted image. I can't figure out why.

Here is a pen to recreate this issue. 
[Pen](https://codepen.io/Hey24sheep/pen/Pggwzv)

**Comment by HarshKhandeparkar** [comment]
@hey24sheep I don't fully understand your code but I can tell you one thing that gpu.js returns an array of size `array[this.output.y][this.output.x]`. I hope this helps. Secondly just see your code again as it is only the y-axis that is inverted.

**Comment by HarshKhandeparkar** [comment]
I saw your code. I think what you are doing is a bit inefficient, refer to https://github.com/gpujs/gpu.js/blob/develop/README.md#input-examples

**Comment by hey24sheep** [comment]
@HarshKhandeparkar I am not using array output. I am setting up canvas graphical. 

Secondly, I know y-axis are inverted. I wan't to know why? Shouldn't it just return the right one? 

Would you elaborate what is inefficient? That's just a quick/sample of my actual code.

**Comment by HarshKhandeparkar** [comment]
Ok thanks. What I would like you to do is not to complicate things using
canvas etc, just use the example code, create an `img` tag, use its source
onload event listener. I don't know why the y axis is inverted now. What
you are doing is you are just overcomplicating the code, give it `img.src`
and access the pixel using `src[this.thread.y][this.thread.x]`. This should
work. I have used gpu.js for image manipulation before and never seen such
an error.

Another thing you can do is use a non-square image. Use a rectangle, if
anything goes out of bounds and shows an error, please tell me.

**Comment by hey24sheep** [comment]
@HarshKhandeparkar I can't use image src. I have canvas in my code. I get imageData which I have to manipulate. Rectangle, square and others all work. no issues in that. Only issue is that the image is inverted. 

For now I am flipping pixels using this function.
Here is a typescript version of [flip pixels](https://github.com/dy/flip-pixels/blob/master/index.js)

```
flip(pixels: any, w: number, h: number, c?: any) {
    // handle Arrays
    if (Array.isArray(pixels)) {
      const result = this.flip(new Float64Array(pixels), w, h, c);

      for (let i = 0; i < pixels.length; i++) {
        pixels[i] = result[i];
      }
      return pixels;
    }

    if (!w || !h) {
      throw Error('Bad dimensions');
    }

    if (!c) {
      c = pixels.length / (w * h);
    }

    // tslint:disable-next-line:no-bitwise
    const h2 = h >> 1;
    const row = w * c;
    const Ctor = pixels.constructor;

    // make a temp buffer to hold one row
    const temp = new Ctor(w * c);

    for (let y = 0; y < h2; ++y) {
      const topOffset = y * row;
      const bottomOffset = (h - y - 1) * row;

      // make copy of a row on the top half
      temp.set(pixels.subarray(topOffset, topOffset + row));

      // copy a row from the bottom half to the top
      pixels.copyWithin(topOffset, bottomOffset, bottomOffset + row);

      // copy the copy of the top half row to the bottom half
      pixels.set(temp, bottomOffset);
    }

    return pixels;
  }
```

**Comment by HarshKhandeparkar** [comment]
Do you have to use Canvas? Can you not use normal html img tags?

**Comment by hey24sheep** [comment]
I have only canvas. I cannot use img tags. I have canvas, I get imagedata and I want to manipulate image data in parallel as fast as I can.

**Comment by HarshKhandeparkar** [comment]
Is there a specific reason why you use canvas and only canvas? You use the
canvas to display the image right? Or do you do something else too?

**Comment by hey24sheep** [comment]
I cannot use anything else. I get only canvas. But, I will implement flip in getPixel which anyone else facing this similar issue can fix it easily.

**Comment by HarshKhandeparkar** [comment]
If you are using canvas, just use webgl fragment shader to do your
interpolation.

**Comment by robertleeplummerjr** [comment]
The pixels are flipped because that is what comes back from webgl.  We (I) initially flipped (keep in mind you are using pre-released features) the canvas pixels to match webgl, but perhaps we should flip all webgl, to match canvas.  Thoughts?

**Comment by HarshKhandeparkar** [comment]
I think matching canvas would be better.

**Comment by robertleeplummerjr** [comment]
I agree, I think it feels more like the JS way of doing things.  Does that sound ok, @hey24sheep?  I can probably have that in the next release, but in the middle of a few things, so it may be a few days.

**Comment by hey24sheep** [comment]
@robertleeplummerjr  I think it should by default flip with a optional boolean to get data in original form. I have given a code snippet above which I am using to flip pixels. It's not an issue. I would contribute myself once I get a lil free time. There is no hurry for now.

**Comment by robertleeplummerjr** [comment]
Added here: https://github.com/gpujs/gpu.js/commit/e3aded43b1bd0a4ca4a1da26e313c50834a744fa
Unit tests added: https://github.com/gpujs/gpu.js/commit/e3aded43b1bd0a4ca4a1da26e313c50834a744fa#diff-f54fde222fcfc27510320ff006727cab

Going to go ahead and close as this will be released soon.
