### ISSUE TITLE
Pipelining Clarification Request

### ISSUE THREAD

**Issue by batraxos** [gpujs/gpu.js#462]
Hi. 
Sorry if this has been answered before or if it is a stupid question, but I cannot seem to find the information anywhere.
From my understanding, pipelining stores the data from a kernel as a texture, so it can be easily loaded into another kernel.  But does this kernel remain in the GPU thus eliminating the overhead of Host to Device memory copy, or is just to eliminate the overhead of "encoding" the arrays to textures, but we still get the memory copy penalty?

Thanks

**Comment by HarshKhandeparkar** [comment]
Yes it does store the output data to a kernel. But at the terminal kernels that is the first input kernel and the final output kernel, the data will have to be transferred to the CPU and converted, thus the overhead
