### ISSUE TITLE
How to calculate matrix multiplication faster?

### ISSUE THREAD

**Issue by wdl000001** [gpujs/gpu.js#463]
Can we do some optimization to accelerate matrix multiplication?

**Comment by hmmhmmhm** [comment]
I also very curious about how to accelerate simple operations with gpu.js. It's so hard to understand Shader.

**Comment by robertleeplummerjr** [comment]
dot product matrix multiplication is one of our leading examples.  For example here: http://gpu.rocks/

Generally it works out to be far faster than the GPU.  I think in the worst scenario's, it is roughly 5 times faster, but in some of the best cases, it is hundreds of times faster than CPU.
