### ISSUE TITLE
Question about collision detection

### ISSUE THREAD

**Issue by lorankary** [gpujs/gpu.js#464]
Would it be possible to use gpujs to calculate the distance between one 2D coordinate pair and thousands of others for the purpose of collision detection?  If so, what might that code look like?

**Comment by HarshKhandeparkar** [comment]
If you have one coordinate, what you can do is push all of those other coords as an argument and set the output size to the number of auch coordinates. So,
```js
const kernelFunc = function(coords){
  const coordX = 5;
  const coordY = 7;

  const x = coords[this.thread.x][0];
  const y = coords[this.thread.x][1];

  return Math.sqrt(Math.pow((coordX - x), 2) + Math.pow((coordY - y), 2))
```

I have just selected an arbitrary value for the reference point coordinates. `(5, 7)`. Coords is an array argument with many coordinate pairs as arrays in it like `[[0, 2], [2, 3], [5, 8]]`. The output size will be 1d and will be the same as the length of the coords array.

Now to access the output distances, you can do `output[i]` where i is the point in the original coords array. So it will return the distance from the `i`th point in the coords array.

I hope this helps.

**Comment by lorankary** [comment]
Woohoo that works!  Thank you very much.
My follow up question has to do with setting the output dimension.  I see that it is necessary to call setOutput() with an array that specifies the dimension for the output.  The output size does not adjust itself automatically according to the input.
I was hoping that I could call gpu.createKernel() just once and then call setOutput() each time before I use the kernel function since the output will vary depending on the input.
That seems to work to shrink the output size but not to grow the output size.  
Presumably there is no great cost to calling gpu.createKernel() each time before I can use the kernel function but I wonder if there is a way not to have to do that.

**Comment by lorankary** [comment]
Now this is very unexpected.  If I have 10000 coordinate pairs and I call my kernel function 10000 times, it takes 6-10 times as long to use the gpu as it does to not use the gpu depending on whether the browser is firefox or chrome.
Are there operations that the gpu just does not do as efficiently as pure javascript?

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>GPU.js Collision Detection Performance</title>
</head>
<body>
<script src="../gpu.js/bin/gpu-browser.js"></script>
<script>

    var coords = [];
    var output = [];
    for(let i = 0; i < 10000; i++){
        coords.push([Math.random()*800, Math.random()*600]);
    }
    let loc = {x: Math.random()*800, y: Math.random()*600};

    let start = Date.now();
    for(let j = 0; j < 10000; j++){
        output = [];
        for(let i = 0; i < coords.length; i++){
            let dist = Math.sqrt(Math.pow(loc.x-coords[i][0], 2) + Math.pow(loc.y-coords[i][1], 2));
            output.push(dist);
        }
    }
    let stop = Date.now();
    console.log(stop-start + " ms");
    // Use the gpu to calculate the distance between one
    // coordinate pair and each coordinate pair in an Array
    // https://github.com/gpujs/gpu.js/issues/464

    const gpu = new GPU();
    const kernelFunc = function(coords,loc_x, loc_y){

    const x = coords[this.thread.x][0];
    const y = coords[this.thread.x][1];

    return Math.sqrt(Math.pow((loc_x - x), 2) + Math.pow((loc_y - y), 2))
    }


    const collisions = gpu.createKernel(kernelFunc);

    //coords = [[0, 2], [2, 3], [5, 8]];

    collisions.setOutput([10000]);  // dimension of 1D array
    start = Date.now();
    for(let j = 0; j < 10000; j++){
        output = collisions(coords,loc.x,loc.y);
    }
    stop = Date.now();
    console.log(stop-start + " ms");

</script>
</body>
</html>

**Comment by HarshKhandeparkar** [comment]
Just make the output size 10000 and run the kernel

**Comment by lorankary** [comment]
My question has changed from "how to" to performance so probably I should post as a new issue.

**Comment by HarshKhandeparkar** [comment]
Can you ask an explicit question if it has changed?

**Comment by lorankary** [comment]
https://github.com/gpujs/gpu.js/issues/466
