### ISSUE TITLE
kernel execution slow, only during the first call

### ISSUE THREAD

**Issue by AZE38** [gpujs/gpu.js#465]
![A GIF or MEME to give some spice of the internet](url)

## *What* is wrong?
when i tried to execute kernel, only the first time is very slow..

like : 
```javascript
const JanusStyle = gpu
  .createKernel(function(a, racine, massetot, mi, mg, g, Rneg, dt) {
    let sum = 0;
    let ax = 0;
    let ay = 0;
    let az = 0;
    let stp = racine;

    for (let i = 0; i < stp; i++) {
      for (let j = 0; j < stp; j++) {
        if ( this.thread.x != i && this.thread.y != j) {
        let Rij = Math.pow(
          (a[i][j][0] - a[this.thread.x][this.thread.y][0]) *
            (a[i][j][0] - a[this.thread.x][this.thread.y][0]) *
            (a[i][j][1] - a[this.thread.x][this.thread.y][1]) *
            (a[i][j][1] - a[this.thread.x][this.thread.y][1]) *
            (a[i][j][2] - a[this.thread.x][this.thread.y][2]) *
            (a[i][j][2] - a[this.thread.x][this.thread.y][2]),
          1 / 2
        );

        if (Rij > 0.5 && i < stp && j < stp) {
          ax +=
            (((g * mg[this.thread.x][this.thread.y][0] * mg[i][j][0]) / mi[this.thread.x][this.thread.y]) *
              (a[i][j][0] - a[this.thread.x][this.thread.y][0])) /
              Math.abs(Rij * Rij * Rij) +
            (((g * mg[this.thread.x][this.thread.y][0] * massetot) / mi[this.thread.x][this.thread.y]) * a[this.thread.x][this.thread.y][0]) /
              Math.abs(Rneg * Rneg * Rneg);
          ay +=
            (((g * mg[this.thread.x][this.thread.y][0] * mg[i][j][0]) / mi[this.thread.x][this.thread.y]) *
              (a[i][j][1] - a[this.thread.x][this.thread.y][1])) /
              Math.abs(Rij * Rij * Rij) +
            (((g * mg[this.thread.x][this.thread.y][0] * massetot) / mi[this.thread.x][this.thread.y]) * a[this.thread.x][this.thread.y][1]) /
              Math.abs(Rneg * Rneg * Rneg);
          az +=
            (((g * mg[this.thread.x][this.thread.y][0] * mg[i][j][0]) / mi[this.thread.x][this.thread.y]) *
              (a[i][j][2] - a[this.thread.x][this.thread.y][2])) /
              Math.abs(Rij * Rij * Rij) +
            (((g * mg[this.thread.x][this.thread.y][0] * massetot) / mi[this.thread.x][this.thread.y]) * a[this.thread.x][this.thread.y][2]) /
              Math.abs(Rneg * Rneg * Rneg);
        } else {
          ax += 0;
          ay += 0;
          az += 0;
        }
      }
    }
  }

    if (this.thread.z === 0) {
      sum += a[this.thread.x][this.thread.y][0] + 0.5 * ax * dt * dt + a[this.thread.x][this.thread.y][3] * dt;
    } else if (this.thread.z === 1) {
      sum += a[this.thread.x][this.thread.y][1] + 0.5 * ay * dt * dt + a[this.thread.x][this.thread.y][4] * dt;
    } else if (this.thread.z === 2) {
      sum += a[this.thread.x][this.thread.y][2] + 0.5 * az * dt * dt + a[this.thread.x][this.thread.y][5] * dt;
    } else if (this.thread.z === 3) {
      sum += a[this.thread.x][this.thread.y][3] + ax * dt;
    } else if (this.thread.z === 4) {
      sum += a[this.thread.x][this.thread.y][4] + ay * dt;
    } else if (this.thread.z === 5) {
      sum += a[this.thread.x][this.thread.y][4] + az * dt;
    }

    return sum;
  })
  .setOutput([2, 2, 6]);
```

a, is an array 2,2,6 for my impuslion space (x,y,z,vx,vy,vz) ,
racine scalar,Masstot scalar,
mi-mg array 2,2,1 
Rneg-dt scalar

## *Where* does it happen?

when i tried to execute 
`JanusStyle(PV, Rnmb, Mgtotneg, MMI, MMG, G, Rayon_Mneg, dt);
JanusStyle(PV, Rnmb, Mgtotneg, MMI, MMG, G, Rayon_Mneg, dt);
JanusStyle(PV, Rnmb, Mgtotneg, MMI, MMG, G, Rayon_Mneg, dt);
...
...
`
The first call , take 1min , other take 0.1ms... 

An idea for my problem ? Thanks !

**Comment by HarshKhandeparkar** [comment]
Hi @AZE38. The first call usually compiles the kernel which takes a very long time as your kernel is very big. You can compile it beforehand by using `kernel.build(args)`. Notice that you have to run the build method **with the arguments passed**.

**Comment by AZE38** [comment]
yes thanks , but if i just do the same loop  but without "ay","az"
`
for (let i = 0; i < stp; i++) {
  for (let j = 0; j < stp; j++) {
    if ( this.thread.x != i && this.thread.y != j) {
    let Rij = Math.pow(
      (a[i][j][0] - a[this.thread.x][this.thread.y][0]) *
        (a[i][j][0] - a[this.thread.x][this.thread.y][0]) *
        (a[i][j][1] - a[this.thread.x][this.thread.y][1]) *
        (a[i][j][1] - a[this.thread.x][this.thread.y][1]) *
        (a[i][j][2] - a[this.thread.x][this.thread.y][2]) *
        (a[i][j][2] - a[this.thread.x][this.thread.y][2]),
      1 / 2
    );

    if (Rij > 0.5 && i < stp && j < stp) {
      ax +=
        (((g * mg[this.thread.x][this.thread.y][0] * mg[i][j][0]) / mi[this.thread.x][this.thread.y]) *
          (a[i][j][0] - a[this.thread.x][this.thread.y][0])) /
          Math.abs(Rij * Rij * Rij) +
        (((g * mg[this.thread.x][this.thread.y][0] * massetot) / mi[this.thread.x][this.thread.y]) * a[this.thread.x][this.thread.y][0]) /
          Math.abs(Rneg * Rneg * Rneg);

    } else {
      ax += 0;
      ay += 0;
      az += 0;
    }
  }
}
`

is very very fast too... , why juste few line , grow dramaticaly kernel building time ?

**Comment by robertleeplummerjr** [comment]
Can you reproduce these results using https://github.com/gpujs/gpu.js/blob/develop/bin/gpu-browser.js using jsfiddle or similar?

**Comment by AZE38** [comment]
https://jsfiddle.net/fgnj1r7a/

**Comment by AZE38** [comment]
https://jsfiddle.net/29wnmk3s/

It's only the first time it's very long, with little Array [2,2,6]

**Comment by AZE38** [comment]
if we construct lot of kernel , only the First kernel is very long 

like 
const kernel1=gpu....
const kernel2=gpu...

kernel1();
kernel2();

with the same opération , just the first kernel take long time ! lol

**Comment by AZE38** [comment]
sry im just noob ^^

so i run the first loop in webworker and wait... ;)

Thanks

**Comment by AZE38** [comment]
gpu-browser.js in webworker works perfectly , thanks

**Comment by robertleeplummerjr** [comment]
When I look at a profiler of your code, I see that acorn struggles with this a bit, and accounts for about half the processing time:
FF:
![image](https://user-images.githubusercontent.com/679099/57394312-2e27c400-7193-11e9-8edc-e2c1042c3815.png)

Chrome:
![image](https://user-images.githubusercontent.com/679099/57394346-4a2b6580-7193-11e9-872c-6d516eb421e9.png)

And in Edge, I get that linking the program took the longest by far:
![image](https://user-images.githubusercontent.com/679099/57394437-8c54a700-7193-11e9-8aee-547b9c54ad34.png)


In either case, from what I see, the problem is never GPU.js.  In-fact, the timing that GPU.js takes is in the worst case, half, but in the best case, it takes only a few percent total of the total parse time.  Can you try with the latest GPU.js, release candidate?  I believe if there was a problem in v1 of GPU.js, it is likely handled in the release latest release candidate.

**Comment by leeoniya** [comment]
> When I look at a profiler of your code, I see that acorn struggles with this a bit, and accounts for about half the processing time:

keep an eye on Cherow, it's about 2x faster than Acorn [1].

[1] https://github.com/cherow/cherow/issues/303#issuecomment-458342516

**Comment by AZE38** [comment]
i have the last version 2.0.0-rc.13 , and i test too the cdn 1.10.4. It's the same time.

**Comment by robertleeplummerjr** [comment]
This is simply part of how GPU.js works, the first call builds, subsequent calls have a built kernel.  In v2, if the arguments are different, say if I send an array into the kernel, and afterwards, I send a texture, the kernel will recompile, and be saved beside the first kernel, and so there can be scenario's where there are more than one "slow" (ie compile) calls, but again, by design.
