### ISSUE TITLE
Errors installing the latest version of gpu.js

### ISSUE THREAD

**Issue by sbrl** [gpujs/gpu.js#467]
_Note: This is_ not _an issue. It's a guide to help people searching for solutions to the same errors I faced when installing gpu.js 2.0.0-rc.13._

I'm using Ubuntu 18.10, and when installing I got a number package / file not found errors. The issues could all be tracked down to missing packages. Doing this should help:

```
sudo apt install mesa-common-dev libxi-dev
``

**Comment by robertleeplummerjr** [comment]
Adding this to the readme.md would be of considerable help as well.  Would you mind adding it, and opening a PR?

**Comment by sbrl** [comment]
Can do!

**Comment by sbrl** [comment]
@robertleeplummerjr opened #469, but also #468 as I've run into some issues.
