### ISSUE TITLE
Weird behavior with % operator - Precision issue ?

### ISSUE THREAD

**Issue by Amev** [gpujs/gpu.js#470]
[This is weird](https://i.giphy.com/media/aZ3LDBs1ExsE8/giphy.webp)

## *What* is wrong?
% 3 and its multiples and may be other values ?

## *Where* does it happen?
In browser

## *How* do we replicate the issue?
```js
    const kernel = gpu.createKernel(function(mod) {
        return this.thread.x % mod;
    }, {
        output: [10, 5],
        argumentType: {
            mod: 'Integer',
        },
    });

    const result = kernel(6);

    console.log(result);
    //  [
      //  0: Float32Array(10) [0, 1, 2, 3, 4, 5, 6, 1, 2, 3],
      //  1: Float32Array(10) [0, 1, 2, 3, 4, 5, 6, 1, 2, 3],
      //  2: Float32Array(10) [0, 1, 2, 3, 4, 5, 6, 1, 2, 3],
      //  3: Float32Array(10) [0, 1, 2, 3, 4, 5, 6, 1, 2, 3],
      //  4: Float32Array(10) [0, 1, 2, 3, 4, 5, 6, 1, 2, 3]
    //  ]
```

## *How* important is this (1-5)?
4

## Expected behavior (i.e. solution)
6 % 6 should be **0**
```js
    //  [
      //  0: Float32Array(10) [0, 1, 2, 3, 4, 5, 0, 1, 2, 3],
      //  1: Float32Array(10) [0, 1, 2, 3, 4, 5, 0, 1, 2, 3],
      //  2: Float32Array(10) [0, 1, 2, 3, 4, 5, 0, 1, 2, 3],
      //  3: Float32Array(10) [0, 1, 2, 3, 4, 5, 0, 1, 2, 3],
      //  4: Float32Array(10) [0, 1, 2, 3, 4, 5, 0, 1, 2, 3]
    //  ]
```

## Other Comments
It seems like a precision issue impacting only multiples of 3 but I'm not sure...

**Comment by HarshKhandeparkar** [comment]
@Amev:
1. Please use restricted language on github.
2. Try multiplying and dividing by 100 or something. `(this.thread.x * 100) % (mod * 100)

**Comment by HarshKhandeparkar** [comment]
Also what is the version of gpu.js you are using?

**Comment by Amev** [comment]
> Please use restricted language on github.

I'm sorry if the title of my gif hurt you, I'll change it. Just wanted to respect your template :)

> Try multiplying and dividing by 100 or something. ((this.thread.x * 100) % (mod * 100)) / 100

For now I did recode a simple modulo function to replace the operator but I think it should be fixed or explained somewhere in your README to avoid to other users of the lib an horrible debug time like I had because of this weird behavior of the % operator which was lost in the middle of a big kernel function...

> Try multiplying and dividing by 100 or something. ((this.thread.x * 100) % (mod * 100)) / 100

Forgot to mention I was using last version (2.0.0-rc.13) sorry.

**Comment by robertleeplummerjr** [comment]
@HarshKhandeparkar runs a tight ship 😛 

I'll see about looking into this perhaps on my lunch break.

**Comment by HarshKhandeparkar** [comment]
@Amev your GIF definitely didn't hurt me. I was ROFL. I thought that it might hurt someone else since GitHub is kinda formal.

**Comment by robertleeplummerjr** [comment]
I believe the issue will be solved in v2 rc14, tested here: https://github.com/gpujs/gpu.js/commit/49a06ba30545a1701f013df2bc8fcedecb181e8a
