### ISSUE TITLE
Graphical Output 

### ISSUE THREAD

**Issue by batraxos** [gpujs/gpu.js#477]
I am looking for a way to have the Graphical output not appear Interpolated when the canvas size is bigger. The reason for that is that I want to have a clearer image , and then later on do my own interpolation in the Kernel so I can choose myself interpolation types.

Something similar to context.imageSmoothingEnabled = false;

Is there a way to achieve that somehow?

Thank you

**Comment by robertleeplummerjr** [comment]
There is an example for it: https://github.com/gpujs/gpu.js/blob/6c055ca5548d678564f395b28b2e046a35df0413/examples/fluid.html#L1302

Just use your own context:
```js
const canvas = document.createElement('canvas');
const context = canvas.getContext('webgl2');
context.imageSmoothingEnabled = true;
const gpu = new GPU({ canvas, context });
const settings = {
  output: [width, height],
  graphical: true
};
const kernel = gpu.createKernel(function..., settings);
kernel();
```

**Comment by batraxos** [comment]
FYI this did not help since I still got interpolated results.
What did help in case anyone has the same issue was actually a CSS entry. 
I added 
canvas.style = 'width: 800px; height: 600px; image-rendering: -moz-crisp-edges;  image-rendering: pixelated; image-rendering: -webkit-crisp-edges;' to my code and got the result (except on IE and Edge)
