### ISSUE TITLE
`npm i gpu.js` failing-ish  

### ISSUE THREAD

**Issue by luiscarbonell** [gpujs/gpu.js#478]
![A GIF or MEME to give some spice of the internet](https://media.giphy.com/media/11PVuEm7Osdjoc/giphy.gif)

## *What* is wrong?

Not much, really! Great stuff @robertleeplummerjr - _and team._

This is a might be a bit picky, but just noting it - _partially for myself, later._

`npm i -S gpu.js` is throws an error on **Debian 9** - _granted its uninstalled dependencies._

## *Where* does it happen?

* **Computer:** Acer Chromebook 14
* **OS:** Debian GNU/Linux 9.9 (stretch)
* **Node.js:**  v12.3.1
* **NPM:** v6.9.0

## *How* do we replicate the issue?

1) Activate _Linux (Beta)_ on any Chromebook OR install _Debian 9.9 (stretch)_ in  any laptop
2) Run `sudo apt-get update -y && sudo apt-get upgrade -y`
3) Install `nodejs`
4) Create a new directory and `npm init`
5) Try to install `gpujs`

## *How* important is this (1-5)?

**1** - _DEFINITELY A **1**_

## Expected behavior (i.e. solution)

`gpu.js` to handle the "non-node" dependency installs - _maybe through a `preinstall` script._

## Other Comments

**Screenshots**

![Screenshot 2019-05-29 at 3 09 56 AM](https://user-images.githubusercontent.com/21148993/58538357-f70d6700-81c2-11e9-8682-d398df1099dd.png)

![Screenshot 2019-05-29 at 3 10 44 AM](https://user-images.githubusercontent.com/21148993/58538369-fbd21b00-81c2-11e9-9720-26e7d85dc196.png)

**Comment by HarshKhandeparkar** [comment]
Try installing `sudo apt install libxi-dev`

**Comment by HarshKhandeparkar** [comment]
Then `npm rebuild`

**Comment by HarshKhandeparkar** [comment]
Ok just run `sudo apt-get install -y build-essential libxi-dev libglu1-mesa-dev libglew-dev pkg-config` this first and then the npm command.

**Comment by luiscarbonell** [comment]
I pulled it off by just running `npm i node-gyp` - going ahead and installing `libxi-dev` to avoid runtime errors.

I'll report the results.

**Comment by robertleeplummerjr** [comment]
Very interested to hear results.

**Comment by luiscarbonell** [comment]
@robertleeplummerjr Worked like a charm! 

I'm working on porting into `@liquid-carrot/carrot`.

I'm trying to blend it with an asynchronous streaming architecture - so far, so good.

I'll go ahead and close for you guys for now.

**Comment by robertleeplummerjr** [comment]
Ty ty!
