### ISSUE TITLE
Pipelined dynamically sized inputs

### ISSUE THREAD

**Issue by BillyWoods** [gpujs/gpu.js#487]
#178  *What* is wrong?

When the output of one kernel is passed into another as a texture, it will work as expected the first time around. However, if on another run the size of the texture isn't the same size as the second kernel expects/was compiled for, indexing elements in the texture doesn't work as expected. 

This seems to be due to indices getting normalised against the previous and incorrect texture dimensions on the second run. In a compiled kernel these texture dimensions are baked in as constants and then get passed into getFloatFromSampler2D(), etc, inside which the normalisation happens. A possible solution might be to pass these input texture dimensions into the kernel as a uniform, and update them at the same time as arguments get passed in.

## *How* do we replicate the issue?

https://jsfiddle.net/k4h2pawy/10/
See the difference between using webgl2/webgl and cpu modes to get an idea of expected behaviour.

## Expected behavior (i.e. solution)

Here is a workaround:
https://jsfiddle.net/k4h2pawy/33/

## Other Comments
Thanks for all the excellent work; gpu.js has been very nice to use.

**Comment by BillyWoods** [comment]
I've missed that kernel.setDynamicArguments(true) does exactly what is needed.  

Unfortunately when the arguments have updateValue() called, things fall apart with a few argument types that I've tried so far (WebGLKernelValueDynamicNumberTexture, WebGL2KernelValueDynamicSingleInput).

**Comment by robertleeplummerjr** [comment]
Can you reproduce with a jsfiddle or similar that shows the not working code?

**Comment by BillyWoods** [comment]
Give this a try: https://jsfiddle.net/uacwvo17/

**Comment by robertleeplummerjr** [comment]
I'll have a fix out later today.

**Comment by robertleeplummerjr** [comment]
Fixed in https://github.com/gpujs/gpu.js/releases/tag/2.0.0-rc.20

Ty very much for finding this and testing this feature manually.  Added tests so to ensure this doesn't happen again.

**Comment by robertleeplummerjr** [comment]
For continuity, here is the test: https://github.com/gpujs/gpu.js/blob/develop/test/issues/487-dynamic-arguments.js and in addition, the other tests surrounding it: https://github.com/gpujs/gpu.js/blob/develop/test/features/dynamic-arguments.js
