### ISSUE TITLE
Raspberry Pi is it supposed?

### ISSUE THREAD

**Issue by devalexqt** [gpujs/gpu.js#489]
Is it work on raspberry pi gpu?

**Comment by robertleeplummerjr** [comment]
I'm checking this morning.

**Comment by robertleeplummerjr** [comment]
It has been building for about an hour, since it is Linux that I'm testing it on, I'm somewhat optimistic that it will run.

**Comment by robertleeplummerjr** [comment]
It totally runs!  More info shortly.

**Comment by robertleeplummerjr** [comment]
![IMG_20190706_151009](https://user-images.githubusercontent.com/679099/60760270-b5ad7a00-a000-11e9-8dbe-703bf474efa5.jpg)

![IMG_20190706_151025](https://user-images.githubusercontent.com/679099/60760275-ca8a0d80-a000-11e9-92a4-d2467393a177.jpg)

**Comment by robertleeplummerjr** [comment]
A note of caution, you'll need to use install dependencies first for headlessgl: https://github.com/stackgl/headless-gl#ubuntudebian

After that, you'll need to simply `npm i gpu.js`

**Comment by robertleeplummerjr** [comment]
Also, it takes forever on this device, I'm sure it has improved on the newer Raspberry Pi's, but it isn't exactly a performance device.

**Comment by devalexqt** [comment]
Oh, it's very cool! 
Now we can play around with raspberry tonight.
Also, is it possible to check gpu usage on raspberry?

**Comment by robertleeplummerjr** [comment]
Through gpu.js, I don't have a way, but the OS will.

**Comment by devalexqt** [comment]
Just try multiply matrix
![2019-07-06-114019_1842x1032_scrot](https://user-images.githubusercontent.com/865007/60760964-0dd58380-9fe3-11e9-96c3-ef4073cf562c.png)

**Comment by devalexqt** [comment]
Something strange, but I try to multiply two matrix by code below and in GPU mode it's 2x slower than in CPU mode. ?)
```
const { GPU } = require('gpu.js');
const gpu = new GPU({mode:"gpu"});//gpu,cpu,headlessgl,
console.log("==>GPU.isGPUSupported:",GPU.isGPUSupported)
console.log("==>GPU.isKernelMapSupported:",GPU.isKernelMapSupported)
console.log("==>GPU.isOffscreenCanvasSupported:",GPU.isOffscreenCanvasSupported)
console.log("==>GPU.isWebGLSupported:",GPU.isWebGLSupported)
console.log("==>GPU.isWebGL2Supported:",GPU.isWebGL2Supported)
console.log("==>GPU.isHeadlessGLSupported:",GPU.isHeadlessGLSupported)
console.log("==>GPU.isCanvasSupported:",GPU.isCanvasSupported)
console.log("==>GPU.isGPUHTMLImageArraySupported:",GPU.isGPUHTMLImageArraySupported)
console.log("==>GPU.isSinglePrecisionSupported:",GPU.isSinglePrecisionSupported)

var length=512
//generate random matrixs length x length
var a=Array.from({length: length}, () => {return Array.from({length: length}, () => Math.floor(Math.random() * length))})
var b=Array.from({length: length}, () => {return Array.from({length: length}, () => Math.floor(Math.random() * length))})

console.log("==>random matrixs generated:\n","matrix a size:",a.length,"matrix b size:",b.length)
var startTime=new Date().getTime()
const multiplyMatrix = gpu.createKernel(function(a, b,length) {
    let sum = 0;
    for (let i = 0; i < length; i++) {
        sum += a[this.thread.y][i] * b[i][this.thread.x];
    }
    return sum;
}).setOutput([length, length]);

const c = multiplyMatrix(a, b,length);

console.log("=>multiplyMatrix result size:",c.length,", run time:",(new Date().getTime()-startTime)/1000,"sec")
```

**Comment by robertleeplummerjr** [comment]
If you are just running the function once there's a good chance we'll be slower.  Especially on this particular hardware.  The reason is because you are code is trancepiled (JavaScript to glsl) then compiled (glsl to machine code).  It would be best to run it a few times and get an average.

**Comment by robertleeplummerjr** [comment]
It should be noted that subsequent runs will not have the same penalty.

**Comment by devalexqt** [comment]
So, I run same kernel function (from previous code) multiple times and get lower execution time on second, etc run, but it still 2x slower that CPU mode, and device cpu usage is 100% at all cores (in GPU mode). But, in CPU mode it use only one core and it still 2x faster.
So, may be in gpu mode it uses software emulation....
For now I don't know how to check gpu utilization on raspberry pi, so can't confirm if gpu was loaded.

**Comment by devalexqt** [comment]
GPU mode with 100% CPU usage at all cores.
![2019-07-06-155212_1842x1032_scrot](https://user-images.githubusercontent.com/865007/60767429-2fbf1c80-a05c-11e9-8a56-cf150a0863e7.png)

**Comment by robertleeplummerjr** [comment]
Is it perhaps a driver issue?

**Comment by robertleeplummerjr** [comment]
In either case it's be either a driver issue or headlessgl issue (and by relation Google Angle).  You could perhaps rule out Google Angle by opening a webgl page Inna browser and monitor gpu usage.
