### ISSUE TITLE
GPU is not a constructor

### ISSUE THREAD

**Issue by ExtensionShoe** [gpujs/gpu.js#490]
OK this might be a stupid mistake I made but when I use my code attahed below I get an error saying GPU is not a constructor
What's up with that?

```
var GPU = require("gpu.js");
var gpu = new GPU();

var gpuKernel = gpu.createKernel(function() {
    return (this.thread.x + this.thread.y);
}).setOutput([2,2]);

console.info(gpuKernel());
```

**Comment by Gbr22** [comment]
Hey! You closed this issue, I have the same error, how did you fix it?

**Comment by benrayfield** [comment]
Mysteriously my old code that uses GPU.js stopped working in Chrome, Edge, and few other browsers (still worked in Firefox), saying GPU is not a constructor. I fixed it using "new GPU.GPU()" instead of "new GPU()"

**Comment by danielmihalcea** [comment]
I had the same issue. But the thing is that WebGPU only works in a secured location so the workaround sometime doesn't work. So I'm using the following code that always work : 

```
function initGPU() {
	try {
		return new window.GPU.GPU();
	} catch (e) {
		return new GPU();
	}
}
const gpu = initGPU();
```

**Comment by cyberfoxmeow** [comment]
I have the same issue. I tried all the methods mentioned above, but none of them works for me.

For `const gpu = new GPU();`, the error is `Uncaught (in promise) TypeError: (void 0) is not a constructor`.
For `train-neural-network.js:17 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'GPU'`, the error is `train-neural-network.js:17 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'GPU')`.
