### ISSUE TITLE
All results return 0 in "big" matrices

### ISSUE THREAD

**Issue by ExtensionShoe** [gpujs/gpu.js#491]
So I'm using the latest version of gpu.js in the latest version of Node.js
Here is my code the result should not be 0s but the result array is just full of zeros
What's the cause of this?

```
let { GPU } = require("gpu.js");
let gpu = new GPU({mode: 'gpu'});

const gpuMatMult = gpu.createKernel(function (A, B) {
        let sum = 0;
        for (let i = 0; i < 3900; i++) {
            sum += A[this.thread.y][i] * B[i][this.thread.x];
        }
        return sum;
})
.setOutput([3900, 3900]);

function generateMatrices() {
    const matSize = 3900;
    let A = [];
    let B = [];
    for (let n = 0; n < matSize * matSize; n++) {
        const randA = 1;
        const randB = 1;
        A.push(randA);
        B.push(randB);
    }

    A = splitArray(A, matSize);
	B = splitArray(B, matSize);

    function splitArray(array, part) {
        let tmp = [];
        for (let i = 0; i < array.length; i += part) {
            tmp.push(array.slice(i, i + part));
        }
        return tmp;
    }

    return {
        A,
        B
    };
}
let matrix = generateMatrices();
let result = gpuMatMult(matrix.A, matrix.B);
console.log(result);
```

**Comment by HarshKhandeparkar** [comment]
Hi, try using GPU mode instead of CPU mode. It probably just crashes

**Comment by ExtensionShoe** [comment]
> Hi, try using GPU mode instead of CPU mode. It probably just crashes

Tried it same result

**Comment by HarshKhandeparkar** [comment]
Does it give any error?

**Comment by HarshKhandeparkar** [comment]
Which version of gpu.js are you using? V2? Or v1.10?

**Comment by ExtensionShoe** [comment]
Using V2 no errors thrown just the returned values are all 0s
If the matrix size is small it functions normally

**Comment by ExtensionShoe** [comment]
OK after some more inspection I think the limitation is the output size
when I set the output to 1D [25000000] it spits out 0s
if I set it to 1D [250000] it works perfectly

**Comment by HarshKhandeparkar** [comment]
Weird. Is it the latest rc? Rc21? I will try to reproduce this.

**Comment by ExtensionShoe** [comment]
Yes it is the latest version

**Comment by ExtensionShoe** [comment]
so I tested and [1500, 1500] output shape also works fine anything higher doesn't
is this limitation caused by my GPU? or is this a bug?

**Comment by ExtensionShoe** [comment]
So even more trial and error later I discovered it has nothing to do with the output shape and the cause is the for loop iteration count inside the kernel
This code functions:

```
let { GPU } = require("gpu.js");
let gpu = new GPU({mode: 'gpu'});

const gpuMatMult = gpu.createKernel(function (A, B) {
        let sum = 0;
        for (let i = 0; i < 50; i++) { // i < 5000 doesnt't work!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
            sum += A[this.thread.y][i] * B[i][this.thread.x];
        }
        return sum;
})
.setOutput([5000, 5000]);

function generateMatrices() {
    const matSize = 5000;
    let A = [];
    let B = [];
    for (let n = 0; n < matSize * matSize; n++) {
        const randA = 1;
        const randB = 1;
        A.push(randA);
        B.push(randB);
    }

    A = splitArray(A, matSize);
	B = splitArray(B, matSize);

    function splitArray(array, part) {
        let tmp = [];
        for (let i = 0; i < array.length; i += part) {
            tmp.push(array.slice(i, i + part));
        }
        return tmp;
    }

    return {
        A,
        B
    };
}
let matrix = generateMatrices();
let result = gpuMatMult(matrix.A, matrix.B);
console.log(JSON.stringify(result));
```

**Comment by ExtensionShoe** [comment]
Is this a time-out issue or something?

**Comment by HarshKhandeparkar** [comment]
Hmm. Interesting. @robertleeplummerjr is this expected behaviour? (I don't
think so)

**Comment by robertleeplummerjr** [comment]
Take a look at: https://github.com/gpujs/gpu.js#loops

Specifically loopMaxIterations.  Does experimenting with this value fix the problem?

**Comment by ExtensionShoe** [comment]
I actually tried to change loopMaxIterations to an absurdly large number didn't work

**Comment by ExtensionShoe** [comment]
> Take a look at: https://github.com/gpujs/gpu.js#loops
> 
> Specifically loopMaxIterations. Does experimenting with this value fix the problem?

I tried this no luck here

**Comment by ExtensionShoe** [comment]
@robertleeplummerjr  any updates?

**Comment by robertleeplummerjr** [comment]
Will start working on this today to try and debug, was away over the weekend.

**Comment by ExtensionShoe** [comment]
oh thanks

**Comment by robertleeplummerjr** [comment]
I may have reproduced it [here](https://jsfiddle.net/robertleeplummerjr/86t2r5sn/11/), but I'd like to confirm if we have the same behavior.  I get values in rows all the way up to the 5000th row, but row 5001, I get zeros.  Is that what you get?

**Comment by ExtensionShoe** [comment]
Unfortunately no I ran the code you provided and the result matrices are just full of zeros and no other values

Here is my gpu if it helps:
ASUS R7 250X 2GB (OLD)

**Comment by HarshKhandeparkar** [comment]
It gives me this error
```
Error: WebGL warning: enableVertexAttribArray: -1 is not a valid `index`. This value probably comes from a getAttribLocation() call, where this return value -1 means that the passed name didn't correspond to an active attribute in the specified program. gpu-browser.min.js:13752:8
Error: WebGL warning: vertexAttribPointer: -1 is not a valid `index`. This value probably comes from a getAttribLocation() call, where this return value -1 means that the passed name didn't correspond to an active attribute in the specified program. gpu-browser.min.js:13753:8
Error: WebGL warning: linkProgram: Failed to link, leaving the following log:
Fragment info
-------------
Internal error: assembly compile error for fragment shader at offset 1499603:
-- error message --
line 65565, column 1:  error: too many instructions
-- internal assembly text --
!!NVfp5.0
OPTION NV_internal;
OPTION NV_gpu_program_fp64;
OPTION NV_bindless_texture;
# cgc version 3.4.0001, build date Mar 15 2019
# command line args: 
#vendor NVIDIA Corporation
#version 3.4.0.1 COP Build Date Mar 15 2019
#profile gp5fp
#program main
#semantic webgl_9257bf67a07c492b
#semantic webgl_e65c940aa30e5538
#semantic webgl_e694517b30dd79b7
#semantic webgl_5f4278df435421dd
#var int3 webgl_9257bf67a07c492b :  : c[0] : -1 : 1
#var int2 webgl_e65c940aa30e5538 :  : c[1] : -1 : 1
#var float2 webgl_45c333976bad9411 : $vin.ATTR0 : ATTR0 : -1 : 1
#var ulong webgl_e694517b30dd79b7 :  : c[2] : -1 : 1
#var ulong webgl_5f4278df435421dd :  : c[3] : -1 : 1
#var float4 webgl_c22d952d3af1947c : $vout.COL00 : COL0[0] : -1 : 1
PARAM c[4] = { program.local[0..3] };
ATTRI gpu-browser.min.js:13718:8
Error: WebGL warning: getAttribLocation: `program` must be linked. gpu-browser.min.js:13748:24
Error: WebGL warning: enableVertexAttribArray: -1 is not a valid `index`. This value probably comes from a getAttribLocation() call, where this return value -1 means that the passed name didn't correspond to an active attribute in the specified program. gpu-browser.min.js:13749:8
Error: WebGL warning: vertexAttribPointer: -1 is not a valid `index`. This value probably comes from a getAttribLocation() call, where this return value -1 means that the passed name didn't correspond to an active attribute in the specified program. gpu-browser.min.js:13750:8
Error: WebGL warning: getAttribLocation: `program` must be linked. gpu-browser.min.js:13751:29
Error: WebGL warning: enableVertexAttribArray: -1 is not a valid `index`. This value probably comes from a getAttribLocation() call, where this return value -1 means that the passed name didn't correspond to an active attribute in the specified program. gpu-browser.min.js:13752:8
Error: WebGL warning: vertexAttribPointer: -1 is not a valid `index`. This value probably comes from a getAttribLocation() call, where this return value -1 means that the passed name didn't correspond to an active attribute in the specified program. gpu-browser.min.js:13753:8
Error: WebGL warning: useProgram: Program has not been successfully linked. gpu-browser.min.js:13757:8
Error: WebGL warning: useProgram: Program has not been successfully linked. gpu-browser.min.js:15715:8
Error: WebGL warning: getUniformLocation: `program` must be linked. 5 gpu-browser.min.js:14052:66
Error: WebGL warning: drawArrays: The current program is not linked. gpu-browser.min.js:15773:8
```

It gives this even at size=1000, IDK the threshold but it didn't give any error at size=500. I have never seen this error before.

**Comment by ExtensionShoe** [comment]
hmmm are you running the code on jsfiddle? might be the cause maybe?
are you using node? or plain js on the browser?

**Comment by robertleeplummerjr** [comment]
Can you try with `useLegacyEncoder: true` or `kernel.setUseLegacyEncoder(true)` and give results?

**Comment by robertleeplummerjr** [comment]
I'm able to reproduce it all of a sudden, I'm not sure what changed.  Working out what is the cause.

**Comment by ExtensionShoe** [comment]
> Can you try with `useLegacyEncoder: true` or `kernel.setUseLegacyEncoder(true)` and give results?

tried it same result

> I'm able to reproduce it all of a sudden, I'm not sure what changed. Working out what is the cause.

weird that it just started happening all of a sudden

**Comment by HarshKhandeparkar** [comment]
I don't think it is jsfiddle

**Comment by robertleeplummerjr** [comment]
Can you try with this option: `optimizeFloatMemory: true` or `kernel.setOptimizeFloatMemory(true)` and give the results?

**Comment by ExtensionShoe** [comment]
nope still the same

**Comment by robertleeplummerjr** [comment]
What about using `precision: 'unsigned'` or `kernel.setPrecision('unsigned')`, what results when you do that?

**Comment by ExtensionShoe** [comment]
its still the same
so you get different results with these options?

**Comment by robertleeplummerjr** [comment]
I'm able to reproduce memory issues, when we go beyond the limit of our hardware, yes.  But I'm working out how to handle them.  What happens when you do something like this:
```js
const gpuMatMult = gpu.createKernel(function () {
  return 1;
})
.setOutput([3900, 3900]);
```

And could you run this:
```js
console.log(gpuMatMult.context.getParameter(gpuMatMult.context.MAX_TEXTURE_SIZE));
```

**Comment by ExtensionShoe** [comment]
> I'm able to reproduce memory issues, when we go beyond the limit of our hardware, yes. But I'm working out how to handle them. What happens when you do something like this:
> 
> ```js
> const gpuMatMult = gpu.createKernel(function () {
>   return 1;
> })
> .setOutput([3900, 3900]);
> ```
> 
Works perfectly outputs all zeros
> And could you run this:
> 
> ```js
> console.log(gpuMatMult.context.getParameter(gpuMatMult.context.MAX_TEXTURE_SIZE));
> ```

gives me 16384

**Comment by ExtensionShoe** [comment]
> I'm able to reproduce memory issues, when we go beyond the limit of our hardware, yes. But I'm working out how to handle them. 

So this issue is caused by my system?
Not enough memory?

**Comment by robertleeplummerjr** [comment]
If you are able to return all ones, then no it isn't likely a hardware issue.  I think it is likely an issue where the GPU is unwinding the for loop, and it is just too big for it to handle.  There is a bit of an interesting topic here https://stackoverflow.com/questions/10334555/prevent-loop-unwinding-in-fragment-shader that has to do with preventing the unroll.  It looks like to see if it works, you could put:

```
#pragma unroll 1
```
in a new line just after `__HEADER__` in (if you are using Firefox or Chrome) this file: https://github.com/gpujs/gpu.js/blob/develop/src/backend/web-gl2/fragment-shader.js, otherwise (for example, if you are using Node), it'll need to go in https://github.com/gpujs/gpu.js/blob/develop/src/backend/web-gl/fragment-shader.js

If you are using the browser and do not use your own build script, you'll need to run `yarn make`.

This is very edge case, and will likely not succeed, but there is a chance.  Are you in a position to "hack" this into your fragment shader, and see if it works?

**Comment by ExtensionShoe** [comment]
I have tried it and well bad news again it didn't work I use Node.js
so web-gl right?
edited it just like you said no luck

**Comment by ExtensionShoe** [comment]
Oh also tried it for browser as well 
it didn't work

**Comment by robertleeplummerjr** [comment]
How about, does this work, or some variation of it?:
```js
const gpuMatMult = gpu.createKernel(function (A, B) {
        let sum = 0;
        for (let i = 0; i < 1950; i++) {
            sum += A[this.thread.y][i] * B[i][this.thread.x];
        }
        for (let i = 1950; i < 3900; i++) {
            sum += A[this.thread.y][i] * B[i][this.thread.x];
        }
        return sum;
})
.setOutput([3900, 3900]);
```

**Comment by ExtensionShoe** [comment]
i really had my money on this i tried it didn't work i tried this:

```
const gpuMatMult = gpu.createKernel(function (A, B) {
        let sum = 0;
        for (let i = 0; i < 1000; i++) {
            sum += A[this.thread.y][i] * B[i][this.thread.x];
        }
        for (let i = 1000; i < 2000; i++) {
            sum += A[this.thread.y][i] * B[i][this.thread.x];
        }
		for (let i = 2000; i < 3000; i++) {
            sum += A[this.thread.y][i] * B[i][this.thread.x];
        }
        return sum;
})
.setOutput([3000, 3000]);
```
didn't work
i'll try smaller loops and let you know

**Comment by ExtensionShoe** [comment]
oh wow this worked:

```
const gpuMatMult = gpu.createKernel(function (A, B) {
        let sum = 0;
        for (let i = 0; i < 500; i++) {
            sum += A[this.thread.y][i] * B[i][this.thread.x];
        }
        for (let i = 500; i < 1000; i++) {
            sum += A[this.thread.y][i] * B[i][this.thread.x];
        }
		for (let i = 1000; i < 1500; i++) {
            sum += A[this.thread.y][i] * B[i][this.thread.x];
        }
		for (let i = 1500; i < 2000; i++) {
            sum += A[this.thread.y][i] * B[i][this.thread.x];
        }
        for (let i = 2000; i < 2500; i++) {
            sum += A[this.thread.y][i] * B[i][this.thread.x];
        }
		for (let i = 2500; i < 3000; i++) {
            sum += A[this.thread.y][i] * B[i][this.thread.x];
        }
        return sum;
})
.setOutput([3000, 3000]);
```

**Comment by robertleeplummerjr** [comment]
Victory!

**Comment by ExtensionShoe** [comment]
but it would be nice to not do this 
Thanks so much anyway I have taken so much of your time

**Comment by robertleeplummerjr** [comment]
So the issue here is the driver is unrolling the loop, and it looks like 500 may be the magic number.  I wonder, how close can you get to the exact limit?

**Comment by ExtensionShoe** [comment]
I'll try bigger numbers and let you know

**Comment by robertleeplummerjr** [comment]
>but it would be nice to not do this

This isn't something that is out of the picture for GPU.js, but likely it'll need to be in v2+, not in v2 exactly.

**Comment by ExtensionShoe** [comment]
750 also works let's see if I can go higher

**Comment by ExtensionShoe** [comment]
tried 900 aaaaaand.... nope
looks like 750 is the sweet spot

**Comment by ExtensionShoe** [comment]
I guess issue closed.......?

**Comment by robertleeplummerjr** [comment]
Ty for helping find this issue.  If it was a "feature", to fix this just in time for us, what do you think it'd be called?

**Comment by ExtensionShoe** [comment]
I have no idea..
maybe something with unrolling 
I really am not creative 😢😊

**Comment by ExtensionShoe** [comment]
I have no idea😢😊

**Comment by robertleeplummerjr** [comment]
Let's leave it as it is for the time being, if it starts becoming a big issue in the future, we can find a way to handle it.  Does that sound reasonable?

**Comment by ExtensionShoe** [comment]
Of course no problem again thank you so much

**Comment by robertleeplummerjr** [comment]
np!
