### ISSUE TITLE
Uncaught RangeError: Source is too large

### ISSUE THREAD

**Issue by liujiusheng** [gpujs/gpu.js#495]
![A GIF or MEME to give some spice of the internet](url)
https://github.com/liujiusheng/gpu.jsbug

## *What* is wrong?

it`s normal when i use V1.

But it get an error in V2 when my input array length is 80.

Uncaught RangeError: Source is too large
    at Float32Array.set (<anonymous>)
    at Object.flatten2dArrayTo (gpu-browser2.min.js:14)
    at Object.flattenTo (gpu-browser2.min.js:14)
    at WebGL2KernelValueSingleArray.updateValue (gpu-browser2.min.js:14)
    at WebGL2Kernel.run (gpu-browser2.min.js:14)
    at WebGL2Kernel.t (gpu-browser2.min.js:14)
    at r (gpu-browser2.min.js:14)
    at index.html:104
    at XMLHttpRequest.xhr.onload (helper.js:8)

## *How* important is this (1-5)?

4

**Comment by nowachri-de** [comment]
I get the same error, although everything is correct.

In my code I was able to reproduce the error. I get the error when I am doing the following:

const kernalA = gpu.createKernelMap({});

//call kernelA
let result = kernelA(a,b,c);

//do some OtherStuff
. . .
//call the same kernal again

result = kernelA(a,b,c);


I could work around the issue by doing the following:

let result = kernalA(a,b,c);
result      = kernelB(a,b,c); //the Code of kernelB is the same as of kernelA (Code Duplication)

**Comment by nowachri-de** [comment]
I think the reason for the error is, that I call the same Kernel twice.
When calling it the second time, the input dimensions of the arrays beeing passed, parameters a,b,c have changed. I think that causes the issue since kernels potentially compiled taking the dimensions of the input parameters into consideration.

**Comment by nowachri-de** [comment]
kernel.setDynamicArguments(true) solved my issue

**Comment by robertleeplummerjr** [comment]
Huzzah!  Sorry I've been busy today.

**Comment by robertleeplummerjr** [comment]
Also, that is the intended behavior.
