### ISSUE TITLE
Usable with p5.Image? 

### ISSUE THREAD

**Issue by Modjular** [gpujs/gpu.js#496]
## *What* is wrong?

I want to interface with the built-in [P5.Image](https://p5js.org/reference/#/p5/image) object that P5.js uses

## *How* important is this (1-5)?

1

## Other Comments
Sorry if this is a pretty basic question 😅but after scraping the docs for a while I thought it would be faster to ask here (and help anyone in the future).

To my understanding, a P5.Image is a flat array, where 
`my_img.pixels[i] = red`
`my_img.pixels[i+1] = green`
`my_img.pixels[i+2] = blue`
`my_img.pixels[i+3] = alpha`

**Comment by robertleeplummerjr** [comment]
I believe: just send in a flat array, and use some maths to lookup the indexes.
```js
import { GPU } from from 'gpu.js';
const gpu = new GPU();
const kernel = gpu.createKernel(function(image) {
  const i = /* some math here */;
  const r = image[i];
  const g = image[i + 1];
  const b = image[i + 2];
  const a = image[i + 3];
  this.color(r / 255, g / 255, b / 255, a / 255);
}, { graphical: true, output: [200, 200] });

document.body.appendChild(kernel.canvas);

kernel(image);
```

You can also use `GPU.input` with a flat array so that inside the kernel you have the convenience of using `x` & `y` if you like:

```js
import { GPU, input } from from 'gpu.js';
const gpu = new GPU();
const kernel = gpu.createKernel(function(image) {
  const pixel = image[this.thread.y][this.thread.x];
  this.color(pixel.r / 255, pixel.g / 255, pixel.b / 255, pixel.a / 255);
}, { graphical: true, output: [200, 200] });

document.body.appendChild(kernel.canvas);

kernel(input(image, [200, 200]));
```
