### ISSUE TITLE
Math.random in mode:gpu

### ISSUE THREAD

**Issue by marcelloexp386** [gpujs/gpu.js#498]
![A GIF or MEME to give some spice of the internet](url)

## *What* is wrong?

The random number distribution is Normal instead of Uniform[0,1] 

## *Where* does it happen?

Ex. In GPU.js when I run Math.random inside a gpu.createKernel(function() in Node.js on my pc windows 10  and Nvidia GPU 
NB If mode is set to cpu, all else equal, the numbers are Unifom
## *How* do we replicate the issue?

const { GPU } = require('gpu.js');
const gpu = new GPU({ mode: 'gpu' });
const nobs=10000;

const kernel = gpu.createKernel(function() {
    const y=Math.random();
    return y;
}, { output: [nobs] });
const data = kernel();
## *How* important is this (1-5)?

5
## Expected behavior (i.e. solution)

the data should be uniform 
## Other Comments
Probably, in the plugin you should have chosen nrandom instead of n4random.

**Comment by robertleeplummerjr** [comment]
Do you have a link to that function?  It was super difficult to find any insight when implementing.

**Comment by marcelloexp386** [comment]
Hi Robert, I am quite new to gpu.js and zero-knowledge of WebGL, shaders ... so I think to be quite hopeless in finding a solution. To be totally honest I just had the intuition that the problem was in the choice of n4rand.

In https://www.shadertoy.com/view/4t2SDh, you can find the file generating the noise with the 4 different functions. One can see that nrand produce a uniform histogram, while the others n1rand, n2rand, n3rand and n4 rand produces triangle and bell shaped histograms. 

 In your plugin triangle-noise.js, you make a functionReplace of Math.random() with n4rand(vTexCoord). If I interpreted correctly your code, the right function should be nrand.

My script for testing the statistical properties of the random numbers is attached here (as I said, I run it with node and one can alternatively select "cpu" or "gpu" in line 10). If you take the data saved in the txt file and plot the histogram you will immediately see the bell shaped curve for the data generated with the "gpu" mode. 
[stampa_randnumbers_GPU_v01.js.txt](https://github.com/gpujs/gpu.js/files/3628437/stampa_randnumbers_GPU_v01.js.txt)

**Comment by robertleeplummerjr** [comment]
Fantastic! Ty for not attacking this, it was quite the thing to figure out.  I'll review asap, and get it corrected.  Again TY!

**Comment by marcelloexp386** [comment]
Thanks to you and the gpu team for the fantastic job you are doing with gpu.js!

**Comment by robertleeplummerjr** [comment]
ty for trying it!

**Comment by marcelloexp386** [comment]
Hi Robert, i forgot to tell you if you can send me an email when you have solved the problem.

Yours, Marcello

Ottieni Outlook per Android<https://aka.ms/ghei36>

________________________________

**Comment by marcelloexp386** [comment]
Hi Robert, did you succeed in changing algorithm?

Ottieni Outlook per Android<https://aka.ms/ghei36>

________________________________

**Comment by robertleeplummerjr** [comment]
FYI: https://github.com/gpujs/gpu.js/tree/498-uniformly-distributed will be merged soon, and addresses the issue brought up here.

**Comment by marcelloexp386** [comment]
https://www.randompower.eu/

**Comment by marcelloexp386** [comment]
? In reality, my contribution was just about "testing" your random number generator algorithm. So, I would simply mention randompower.eu among the contributors to the gpujs project.

**Comment by robertleeplummerjr** [comment]
Awesome! Is there any sort of qualification that our random generates that we can make mention of?

**Comment by marcelloexp386** [comment]
We can analyze their statistical properties but it will take a bit of time because at the moment we are working on the hardware of our project. As soon as we have a couple of days free, we can come back with some stats. 
If/when you put a link to our website somewhere in your blog, let me know.

**Comment by robertleeplummerjr** [comment]
I'll just put a shout out to RandomPower in the readme if that is ok.  That way everyone sees it.  Also, I very much look forward to those test results!

**Comment by robertleeplummerjr** [comment]
Fixed in https://www.npmjs.com/package/gpu.js/v/2.2.0

**Comment by marcelloexp386** [comment]
Great! Thanks
