### ISSUE TITLE
webgl.node: undefined symbol: _Z15XextFindDisplayP15_XExtensionInfoP9_XDisplay

### ISSUE THREAD

**Issue by brunobcfum** [gpujs/gpu.js#505]
When installing for the first time I had undefined symbol issues. 
node_modules/gl/build/Release/webgl.node: undefined symbol: _Z15XextFindDisplayP15_XExtensionInfoP9_XDisplay

To solve I had to download **headless-gl** and recompile. Lates I copied the webgl.node file to my gpu.js app and it worked fine. Is it supposed to be like that? Couldn't find any mention on the documentation.

I'm running Node 8.10 and Xubuntu with NVIDIA 390 drivers.

**Steps to build webgl.node:**
Clone this repo: git clone git@github.com:stackgl/headless-gl.git
Switch to the headless gl directory: cd headless-gl
Initialize the angle submodule: git submodule init
Update the angle submodule: git submodule update
Install npm dependencies: npm install
Run node-gyp to generate build scripts: npm run rebuild

**Comment by robertleeplummerjr** [comment]
Is anyone else seeing this?

**Comment by vorticalbox** [comment]
I am seeing this when training NeuralNetworkGPU from brain.js

OS linux mint 19

node: 10.17 and 12.13

https://github.com/BrainJS/brain.js/issues/481

https://github.com/BrainJS/brain.js/issues/481

**Comment by Yanonix** [comment]
I also see this when running tests in mapbox-gl-js 
gl: 4.3.3
node: v8.10.0 on Ubuntu 18.04.3

**Comment by robertleeplummerjr** [comment]
Solved by https://github.com/stackgl/headless-gl/issues/65
