### ISSUE TITLE
Add browser field to package.json

### ISSUE THREAD

**Issue by chrisguttandin** [gpujs/gpu.js#509]
## *What* is wrong?
When bundling gpu.js for the browser it may throw an error because the 'fs' module of Node.js is required somewhere and is not available in the browser.

## *Where* does it happen?
This is caused by the `bindings` module.

gpu.js does already provide a special build which can used in a browser but unfortunately there is no way for webpack to pick it up yet. What about adding a `browser` field to the package.json file which points to `dist/gpu-browser.js`?

Please let me know if you think this makes sense as well. I would be happy to provide a pull request which adds the `browser` field.

**Comment by robertleeplummerjr** [comment]
This makes sense, and a PR is welcome.  Relevant lines: https://github.com/gpujs/gpu.js/blob/33a23958a60243f3487291b0816eb39e61689632/package.json#L13
