### ISSUE TITLE
Setting kernel to pipeline changes behaviour

### ISSUE THREAD

**Issue by VeryGoodDog** [gpujs/gpu.js#510]
Pipelines are not working as expected. The following example works as it should, logging an array of Float32Arrays and then an array of just 1s. The second example is not working properly.

```js
const gpu = new GPU();

const first = gpu.createKernel(function () {
		return [1, 0];
	})
	// .setPipeline(true)
	.setOutput([5]);

const second = gpu.createKernel(function (input) {
		const a = input[this.thread.x][0];
		return a;
	})
	.setOutput([5]);
const i = first();
const k = second(i);
console.log(i, k);
```
Here, a GLTextureArray2Float is printed and then an array of Float32Arrays.
```js
const gpu = new GPU();

const first = gpu.createKernel(function () {
		return [1, 0];
	})
	.setPipeline(true) \* NOTE THIS *\
	.setOutput([5]);

const second = gpu.createKernel(function (input) {
		const a = input[this.thread.x][0];
		return a;
	})
	.setOutput([5]);
const i = first();
const k = second(i);
console.log(i, k);
```

**Comment by robertleeplummerjr** [comment]
We could probably do a better job of breaking this part down, but what is needed here is to lookup the type, in this case, rather than this:

```js
const second = gpu.createKernel(function (input) {
		const a = input[this.thread.x][0];
		return a;
	})
```

You need to do this:
```js
const second = gpu.createKernel(function (input) {
		const value = input[this.thread.x];
		const a = value[0];
		return a;
	});
```

It wouldn't take a ton of work to get this working it has just rarely been requested.

**Comment by VeryGoodDog** [comment]
Sick! If I'm understanding this right the issue is that `const a = input[this.thread.x][0];` skips a type-check that `const value = input[this.thread.x]; const a = value[0];` does not skip and the type-check makes sure, in the second's case, `value` is the right type before it's used.

BTW, it worked, thanks.

**Comment by robertleeplummerjr** [comment]
>If I'm understanding this right the issue is that const a = input[this.thread.x][0]; skips a type-check

Yup, you are dead right.

>BTW, it worked, thanks.

Glad it could be of help to you.

**Comment by VeryGoodDog** [comment]
WELL, the fix works when pipelining is turned on, and it worked immediately as thats what I was trying to do. I disabled pipelining and it threw the following error:

```
Uncaught Error: Error compiling fragment shader:
ERROR: 0:390: 'user_valueSize' : undeclared identifier
ERROR: 0:390: 'user_valueDim' : undeclared identifier
ERROR: 0:390: 'getMemoryOptimized32' : no matching overloaded function found
```

The whole source is as follows:

```js
const gpu = new GPU();

const first = gpu.createKernel(function () {
		return [1, 0];
	})
	// .setPipeline(true)
	.setOutput([5]);

const second = gpu.createKernel(function (input) {
		const value = input[this.thread.x];
		const a = value[0];
		return a;
	})
	.setOutput([5]);
const i = first();
const k = second(i);
console.log(i, k);
```

**Comment by robertleeplummerjr** [comment]
You need to use an argument type in this use case, like this:

```js
  const gpu = new GPU();
  const first = gpu.createKernel(function () {
    return [1, 0];
  })
  // .setPipeline(true)
    .setOutput([5]);

  const second = gpu.createKernel(function (input) {
    const value = input[this.thread.x];
    const a = value[0];
    return a;
  })
    .setArgumentTypes({ input: 'Array1D(2)' })
    .setOutput([5]);

  const i = first();
  const k = second(i);
  
  console.log(i);
  console.log(k);
```

Working example: https://jsfiddle.net/robertleeplummerjr/bgr219oj/1/

There is enough information when using textures for this to be gathered, but without textures, there function transpiler simply sees this as a potential multi-dimensional array.  By clarifying what type of array it is GPU.js resolves how to treat it.

I started looking into if this is available without the use of setting argument type.  We'd need to add the original size of the array to `FunctionNode`, and check this value when a "MemberExpression" is parsed in web-gl/function-node.js and in cpu/function-node.js.  Once the check is in there this wouldn't be an absolute requirement.
