### ISSUE TITLE
Wrong return value in mode dev

### ISSUE THREAD

**Issue by CipSoft-Components** [gpujs/gpu.js#516]
## *What* is wrong?

When using gpu.createKernelMap in 'dev' mode, and call the resulting kernel, the result is not a map, instead it is only the array of the result attribute.

## *Where* does it happen?

I run gpu.js in the browser (Tested in Chrome and Firefox) on windows. But I don't think, this matters.

## *How* do we replicate the issue?

```
const gpu = new GPU({
  mode: 'dev'
});

const kernelMap = gpu.createKernelMap(
  {
    a: function a() {
      return 1;
    }},
  function() {
    a();
    return 0;
  },
  { output: [3] });

const mapResult = kernelMap();
// mapResult: [0, 0, 0]
```

## *How* important is this (1-5)?

4 - Because I think, the dev mode is important during development

## Expected behavior (i.e. solution)

```
// mapResult: { a: [1, 1, 1], result: [0, 0, 0] }
```

**Comment by robertleeplummerjr** [comment]
https://github.com/gpujs/gpu.js#debugging states this: "PLEASE NOTE: Mapped kernels are not supported in this mode. They simply cannot work because of context."

Mapped kernels are not supported in debug mode currently because the context in which they exist _is_ the context you are sending in.  There is likely a path (IE a new syntax?) we could take that would be compatible it just needs to be thought and and suggested.

By all means, suggest this if you have the insight.

**Comment by CipSoft-Components** [comment]
Sorry, I didn't saw the note. For the current API I see the problem. For a future Version, I would suggest a mechanism like the constants. Something like following:
```
const megaKernel = gpu.createKernelMap({
  addResults: 'add',
multiplyResults: 'multiply'
}, function(a, b, c) {
  return this.fn.multiply(this.fn.add(a[this.thread.x], b[this.thread.x]), c[this.thread.x]);
}, { output: [10] }).setFunctions({
  add: function(a, b) {
    return a + b;
  },
  multiply: function(a, b)  {
    return a * b;
  }
});

megaKernel(a, b, c);
```

If you would do it like that, you would have full control over the functions in dev mode, and wrap them before run, to get the return value.
@robertleeplummerjr  What do you think about this suggestion?

**Comment by robertleeplummerjr** [comment]
I think this is a simple and straightforward means of solving the ability to debug.  Great suggestion!

**Comment by robertleeplummerjr** [comment]
Another option is to test the functions themselves individually as well.

**Comment by CipSoft-Components** [comment]
If you implement this, you could also allow class methods to be used for map functions, like you use when you write classes in typescript. e.g.:
```
class MyKernelWrapper {
  kernel;
  construct() {
    kernel = gpu.createKernelMap({
        addResults: 'add',
        multiplyResults: 'multiply'
      }, function(a, b, c) {
        return this.fn.multiply(this.fn.add(a[this.thread.x], b[this.thread.x]), c[this.thread.x]);
      }, { output: [10] }).setFunctions({
        add: this.add,
        multiply: this.multiply
      });
  }

  run() {
    return this.kernel(a, b, c);
  }

  add(a, b) {
    return a + b;
  }
  
  multiply(a, b) {
    return a * b;
  }
}
```
