### ISSUE TITLE
strange canvas output if graphical is true on chrome for android

### ISSUE THREAD

**Issue by PipOlt** [gpujs/gpu.js#521]
## *What* is wrong?
I tried to run your yellifish canvas direct draw example on my mobile phone (Samsung Galaxy S7) with latest Android updates. If CPU mode is enabled everything works like expected (slow). If I enable the GPU the output is shuffled. It seems like the texture coordinates are shifted. 
expected (cpu):
![screenshot_1](https://user-images.githubusercontent.com/16139246/67157780-4f3f3400-f331-11e9-97c6-8ed653f0a58a.jpg)
observed (gpu):
![screenshot](https://user-images.githubusercontent.com/16139246/67157806-ae04ad80-f331-11e9-9c75-c1adf6f3e44a.jpg)

I tried another example where an color gradient is drawn directly to the canvas. Same behavior on this specific device.
expected (cpu):
![screenshot_2](https://user-images.githubusercontent.com/16139246/67157982-c4f7cf80-f332-11e9-8500-6b83934524da.jpg)
observed (gpu):
![screenshot_3](https://user-images.githubusercontent.com/16139246/67157993-f2447d80-f332-11e9-9cd7-21a644b133a7.jpg)

## *Where* does it happen?
Chrome for Android on my Samsung Galaxy S7. Didn't try another Android Device. Can try it tomorrow. Linux Desktop works like expected.

## *How* do we replicate the issue?
If you have such a device, you can use the Yellifish Video example. Or you can use the second example below:
```
<!DOCTYPE html>
<meta charset="utf-8">

<body>
<script src="js/gpu.js"></script>
<script>
const gpu = new GPU({mode: "gpu"});
const render = gpu.createKernel(function(x) {
  this.color(this.thread.x/500, this.thread.y/500, x[0]);
})
  .setOutput([500, 500])
  .setGraphical(true)
render([0.4])
const canvas = render.canvas;
document.getElementsByTagName('body')[0].appendChild(canvas);
</script>
```
## *How* important is this (1-5)?
5 (my subjective importance) because I cannot use gpu.js for my project with this behaviour. I want to apply video effects to the device camera. Without this behaviour the performance of gpu.js would be great for this project. It is an awesome library! Thanks for that! :)

## Expected behavior (i.e. solution)
There seems to be an anomaly in the canvas output of this (maybe more) devices. It is not the input because of the second test (computed output). It seems like there is a special planar color space in the output texture, so that the uv-mappings doesn't apply to this device (only a slight guess). I have tried other THREE.js video texture examples on this device to proof it is possible and no hardware related problem. The examples i found worked like expected.

## Other Comments
Thank you for this great library!

**Comment by robertleeplummerjr** [comment]
I believe this is the highest priority.  I'm away right now but curious if using `useLegacyEncoder` set to true has any effect.

**Comment by PipOlt** [comment]
Hi,
thanks for the fast response. Just ran:
```
<!DOCTYPE html>
<meta charset="utf-8">

<body>
<script src="js/gpu.js"></script>
<script>
const gpu = new GPU({mode: "gpu"});
const render = gpu.createKernel(function(x) {
  this.color(this.thread.x/500, this.thread.y/500, x[0]);
})
  .setOutput([500, 500])
  .setGraphical(true)
  .setUseLegacyEncoder(true)
render([0.4])
const canvas = render.canvas;
document.getElementsByTagName('body')[0].appendChild(canvas);
</script>
```
Produces the exact same image like above. 
Best regards!

**Comment by PipOlt** [comment]
Hi,
Just tried the code on 3 different android devices. None of these devices displays the output correctly. First one was a Huawei P20 Pro (Android 9). The output was the same like that one on the Galaxy. On the other devices the output was different.
Blackview A10 Android 7.0:
![image](https://user-images.githubusercontent.com/16139246/67193339-6cd5d180-f3f5-11e9-8344-fd7886fb83be.png)
Samsung Galaxy S4 Android 5.0.1:
![image](https://user-images.githubusercontent.com/16139246/67193407-8b3bcd00-f3f5-11e9-917c-071c0744439b.png)
I also tried an Iphone Xs. The results were the same like the Galaxy and the Huawei.
Hope the results helps.
Best regards!

**Comment by RobinKa** [comment]
Try setting the tactic to `performance` (requires a newer version of GPU.js from github (eg. develop or master branch). That made my gradient output smooth on iPad 6 and Nexus 6. Any other setting such as the default "balanced" produces artifacts.

**Comment by PipOlt** [comment]
Yay, that's working! Huawei, Samsung and Iphone is now okay. The other device (Blackview A10 Android 7.0) doesn't work. Is it possible to determine in which specific cases these settings should be applied?

**Comment by RobinKa** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/WebGL_best_practices mentions that `highp` (which `performance` will use) doesn't work on older devices, maybe that's why. It also mentions using `getShaderPrecisionFormat` is possible to check for support.

**Comment by robertleeplummerjr** [comment]
I'll have a good chunk today I can look into this and resolve it, fyi.

**Comment by robertleeplummerjr** [comment]
This has to be related: https://github.com/mapbox/webgl-wind/issues/12

**Comment by robertleeplummerjr** [comment]
Have a fix, will have this added later today.
