### ISSUE TITLE
Loop strangely being cut

### ISSUE THREAD

**Issue by allanninguem** [gpujs/gpu.js#522]
😅

## *What* is wrong?
Loop strangely being cut

## *Where* does it happen?
on this code:
```javascript
const gpu = new GPU({
    mode: 'gpu'
});

const gpuMatMult = gpu.createKernel(function () {
        var i = 0;
        while (i < 512) {
           i++;
        }
        return i;
    })
    .setDimensions([2, 2])
    .setOutputToTexture(false);

const gpuResult = gpuMatMult();
console.log(gpuResult)
```

## *How* do we replicate the issue?
Simple run that kernel code on a browser (I tested on safari)

## *How* important is this (1-5)?
Since the result should be 511 but I got 100, I would say is VEEEERY important! 5!

## Expected behavior (i.e. solution)
Expected behaviour: print 512

## Other Comments
The for loop version works... I tried the while because its the only way to avoid having hard coded numbers in the kernel. If you try to put variables in the for loop test, the compiler complains about type error (probably because, for the kernel code, we can't do 1 < 2.0...
Anyway, it seems to like indexing with floats like A[2.0] being A[2] so the while was the only way to achieve my solution.

**Comment by allanninguem** [comment]
Shoot, figured out... 
Solution:
**loopMaxIterations** as parameter
```javascript
const gpuMatMult = gpu.createKernel(function () {
        var i = 0;
        while (i < 512) {
           i++;
        }
        return i;
    }, {loopMaxIterations:512})
    .setDimensions([2, 2])
    .setOutputToTexture(false);
```
Sorry about that. Do you have that somewhere in the documentation? It looks counter intuitive because the parser detected my while loop and implemented a for instead. Strangely accepting the variable in the condition (maybe not so strangely because now the variable is a float and can be compared to another variable).

Well, all in all, congratulations on the project!!!! I'll be talking about it with my students! Thank you!

**Comment by robertleeplummerjr** [comment]
Ty for the compliment!  We'll look into auto-detecting this.

**Comment by robertleeplummerjr** [comment]
I do believe it is documented, fyi, but when using a literal it shouldn't matter.

**Comment by allanninguem** [comment]
Yes, for literals I agree. I was trying to avoid hard-coding the 512 (in the matrix example) so my kernel receives the matrices and the inner size (common dimension between both matrices). Because of that I have to use the while loop...
Maybe, for the case of for loops, the parser should compile with a forced typecast in the for comparison. Something like

for (var i = 0; i < variable; i++) 

would be 

for (int i = 0; i < (int)variable; i++)

Anyway, I'm not familiar with the webGl kernel language, maybe it does not have this C style typecasts.

Anyways, thanks for the reply! I'll be using and recommending your project everywhere! I really like it %)

**Comment by robertleeplummerjr** [comment]
This has been resolved in v2+.
