### ISSUE TITLE
Add package to npm

### ISSUE THREAD

**Issue by GittiHab** [gpujs/gpu.js#53]
Have you ever considered adding GPU.JS to NPM?

**Comment by picoCreator** [comment]
@GittiHab : Currently the code does not work in Node.js itself. However thats actually part of the rewrite plan we have at long term =)

**Comment by fuzzie360** [comment]
We can consider releasing to npm for use in browserify and webpack,.

Currently blocked by #55

**Comment by robertleeplummerjr** [comment]
Done, but pre-beta/alpha: https://www.npmjs.com/package/gpu.js

**Comment by CoenraadS** [comment]
It would be nice if we could just pull in the precompiled scripts via npm (for browers). Maybe publish gpu.js-web or something. The NPM Install process has a lot of dependencies and for web there is no point rebuilding the whole thing.
