### ISSUE TITLE
LogicalExpression not supported in getDependencies for 'for loop' test

### ISSUE THREAD

**Issue by Drenata** [gpujs/gpu.js#531]
## *What* is wrong?
The test part of the for loop can't handle logical expressions.
For example
```JS
for (let i = 0; i < 10 && !(i > 10); i++)
```
will throw an error while being parsed.

## *Where* does it happen?
For me, this error occurs in the getDependencies function inside function-node.js.
Specifically, there's no case for 'LogicalExpression'.
![image](https://user-images.githubusercontent.com/8545717/68091273-cc17f500-fe7d-11e9-8437-cce6132f4ac2.png)

## *How* do we replicate the issue?
Here's a minimal example https://jsfiddle.net/wea6v3rf/1/

## *How* important is this (1-5)?
2

## Expected behavior (i.e. solution)
Not throw an error :) (This should translate into correct shadercode no?)

## Other Comments
I assume that the following code would fix it
```JS
case 'LogicalExpression':
        this.getDependencies(ast.left, dependencies, isNotSafe);
        this.getDependencies(ast.right, dependencies, isNotSafe);
        return dependencies;
```
and I would make a PR myself, but I can't build the project at the moment so I can't even test it.

**Comment by robertleeplummerjr** [comment]
Fixed here: https://github.com/gpujs/gpu.js/releases/tag/2.6.0
Updated and working jsfiddle: https://jsfiddle.net/robertleeplummerjr/e3L42pns/
