### ISSUE TITLE
Memory Leak with data type "Array1D(3)"

### ISSUE THREAD

**Issue by CipSoft-Components** [gpujs/gpu.js#533]
## *What* is wrong?
When I set "Array1D(3)" as data type for arguments or constants, the memory usage and cpu continuously rises, until the browser tab dies after some time. 

## *Where* does it happen?

In GPU.js when trying to set the data type to "Array1D(3)" with the kernel settings `argumentTypes` or `constantTypes`.

## *How* do we replicate the issue?

```gpu.createKernel(function(arg) {
  // do stuff
}, {
  output: [1000, 500],
  graphical: true
  argumentsTypes: {
    arg: "Array1D(3)"
  }
});

// Some loop, which calls the kernel e.g. 60 FPS
```

## *How* important is this (1-5)?

5

## Expected behavior (i.e. solution)

No memory leak. Memory and cpu usage should stay stable after the starting of the loop.

## Other Comments
Other arguments wit data type "ArrayTexture(1)" do not produce a memory leak, but I need the data type "Array1D(3)" data type.

**Comment by robertleeplummerjr** [comment]
Looking at this now.

**Comment by robertleeplummerjr** [comment]
I cannot see any memory leaks that are noticeable, at least in FireFox: 
<img width="1440" alt="Screen Shot 2020-01-24 at 9 56 28 AM" src="https://user-images.githubusercontent.com/679099/73078286-de5b6b00-3e8f-11ea-9dc5-75deb16cd63a.png">

Here is the code I am using to reproduce:
```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Title</title>
</head>
<body>
<button id="go">GO</button>
</body>
<script src="dist/gpu-browser.js"></script>
<script>
  const go = document.getElementById('go');
  go.onclick = () => {
    const gpu = new GPU();
    const kernel = gpu.createKernel(function (value) {
      return value[this.thread.x];
    }, {
      output: [1000, 500],
      argumentsTypes: {
        arg: 'Array1D(3)'
      }
    });


    for (let i = 0; i < 1000; i++) {
      kernel([
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
      ]);
    }
  };
</script>
</html>
```


Can you post more info, perhaps even source around how you are using the kernel?

**Comment by CipSoft-Components** [comment]
I'm sorry, I can no longer reproduce it on my side either. I changed many things on my side, and can not reproduce it with a fiddle any longer.

**Comment by robertleeplummerjr** [comment]
Glad this is finally resolved.
