### ISSUE TITLE
Just a few Questions

### ISSUE THREAD

**Issue by db-developer** [gpujs/gpu.js#547]
```js
let matix1 = [[...],[...]...]
let matix2 = [[...],[...]...]
let kernel = gui.createKernel( function transform( m1, m2 ) {
  ... do something - return value;
}); 
kernel.setOutput( ... );
kernel( matrix1, matrix2 );
```
Just a few Questions:

1. How to  find out m1 or m2 dimensions (width/height/depth)?
In my case m2 can have different widths (x sizes)
I tried array.prototype.length like m1.length ... which failed
=> Transpiler should replace `array.prototype.length` by a command known to gpu?

2.1. Trying out workarounds, passing in dimensions via constants failed:
`kernel.setConstants{ m1: { x: 10, y: 10 }}`
fails with exception. Obviously the type "`{ }`" cannot be handled.
=> Transpiler does not manage to run type transformation?

2.2. Trying another workaround
`kernel.setConstants{ m1dim: [10,10]}`
runs niceley, but produces messy results. Obviously passing in an array as constant mixes up the matrices m1 and/or m2 passed into the function transform (see at the top).
=> Transpiler thread.constants interferes with  function parameters?

**Comment by robertleeplummerjr** [comment]
This may be something we likely address in the future, but for the time being, you'd just need separate arguments:
```js
let matix1 = [[...],[...]...]
let matix2 = [[...],[...]...]
let kernel = gui.createKernel( function transform( m1, m1Width, m1Height, m2, m2Width, m2Height ) {
  ... do something - return value;
}); 
kernel.setOutput( ... );
kernel( matrix1, matrix1[0].length, matrix1.length, matrix2, matrix2[0].length, matrix2.length );
```

**Comment by db-developer** [comment]
Ok. Might be helpful to add a hint in the docs.
Thanx, and feel free to close the issue.

**Comment by robertleeplummerjr** [comment]
We'd love a contribution, if you'd be up for it.

**Comment by robertleeplummerjr** [comment]
Closing for the time being.  Please feel free to re-open or to add any documentation that would be useful to others.
