### ISSUE TITLE
Actually release v1.0.0

### ISSUE THREAD

**Issue by fuzzie360** [gpujs/gpu.js#55]
This project needs to adopt [semver 2.0.0](http://semver.org/). So:

1. Current API will be frozen until 2.0.0.
2. Additional API will increase minor version number.

Let's do a quick once over the following advertised functionality:

Basic

- [x] Accept numbers as arguments to kernel functions
- [x] Accept 1D array as arguments to kernel functions
- [x] Accept 2D array as arguments to kernel functions
- [x] Accept 3D array as arguments to kernel functions
- [x] Produce output in 1D
- [x] Produce output in 2D
- [x] Produce output in 3D

Settings

- [x] this.constants support
- [x] Debug flag support
- [x] Graphical mode in CPU
- [x] Graphical mode in GPU
- [x] hardcodeConstants support
- [x] outputToTexture support
- [x] loopMaxIterations support
- [x] Mode switching support
- [x] Add function support

Syntax

- [x] Arithmetic operations
- [x] Context constants
- [x] Argument array read
- [x] Return
- [x] if, else if, else branches
- [x] While and for loops
- [x] Fixed sized for loops
- [x] Internal functions
- [x] Math functions
- [x] Color function

Platforms:

- [x] Runs on Chrome
- [x] Runs on Firefox
- [x] Runs on Safari
- [ ] Runs on IE12
- [ ] Runs on Edge
- [ ] Runs on Mobile Chrome (iOS)
- [x] Runs on Mobile Chrome (Android)
- [ ] Runs on Mobile Safari

**Comment by cazala** [comment]
What I'd love to see:

- [ ] Node.js and WebWorker support (maybe via [gl](https://www.npmjs.com/package/gl) package and [OffscreenCanvas](https://developer.mozilla.org/en-US/docs/Web/API/OffscreenCanvas) a la [WebMonkeys](https://github.com/MaiaVictor/WebMonkeys/blob/master/src/WebMonkeys.js#L29-L55)?)

- [ ] Typed Arrays support

**Comment by picoCreator** [comment]
@cazala : Sadly OffscreenCanvas is firefox only, perhaps when it become more "accepted" we will relook at that.

Node.js support is already being looked into

**Comment by robertleeplummerjr** [comment]
I've identified a number of areas that can really improve performance, and would answer a number of issues (some opened by me) to support node and es6 syntax.  Is there interest in pull requests?  If so I can open one when done.

**Comment by robertleeplummerjr** [comment]
Also, I notice that the cpu mode really just uses canvas, shouldn't that be a secondary fallback, if you wanted to use pure cpu, there shouldn't be the following levels:
* gpu
* canvas fallback
* cpu fallback

I've probably misread the code.

**Comment by robertleeplummerjr** [comment]
Looking over the source, I see how we attach programs to the gpu via createKernel, but what if we optionally simplified the instantiation to something like:

```js
var gpu = new GPU((A, B) => {
    var sum = 0;
    for (var i=0; i<512; i++) {
        sum += A[this.thread.y][i] * B[i][this.thread.x];
    }
    return sum;
}).dimensions([512, 512]);
```

**Comment by robertleeplummerjr** [comment]
You'll probably hate it, and I hope I didn't step on anyones toes, but I went ahead and committed in my fork here which embraces node, es6, and a number of refactors to simplify architecture.  I'd like to see this reach 1.0 very soon, hopefully you can see this is an effort to assist in that regard: https://github.com/gpujs/gpu.js/compare/master...robertleeplummerjr:experimental-node-es6?expand=1

**Comment by robertleeplummerjr** [comment]
We have node support now, fyi!

**Comment by robertleeplummerjr** [comment]
https://www.npmjs.com/package/gpu.js just registered

**Comment by robertleeplummerjr** [comment]
Since there has not been any release (that I'm aware of) I'd like to see if we can do a once over on the api before release, and do the initial release with the version that is advancing in the `develop` branch, which will initially be cpu only for node, but both cpu and gpu for browser.  Sense there hasn't been any releases yet, this gives us an opportunity to refine the api early, and ensure we start off without having to support a lot of the experimentals that were introduced early on.  Any takers or rejectors?

**Comment by robertleeplummerjr** [comment]
So @cazala, we are half way there in its current form.

**Comment by robertleeplummerjr** [comment]
We are still working on documentation and browser minification, but short of that we are now beta ready.

**Comment by robertleeplummerjr** [comment]
Today's after-work progress got us full on beta.  Release will be imminent for beta, and fixes for other browsers will be next step.

**Comment by robertleeplummerjr** [comment]
@PicoCreator & @cazala https://developer.mozilla.org/en-US/docs/Web/API/OffscreenCanvas is now chrome v60

**Comment by robertleeplummerjr** [comment]
@cazala you mentioned things you'd like to see:
>Node.js and WebWorker

Node.js is handled, WebWorkers will need to be handled in a later release in a later issue if there is still interest.

v1 has been released: https://github.com/gpujs/gpu.js/releases/tag/1.0.0
