### ISSUE TITLE
first HTMLImage parameter causes a permanent y-flip bug

### ISSUE THREAD

**Issue by psishock** [gpujs/gpu.js#553]
## *What* is wrong?
Whenever the interpreter detects a HTMLImage input parameter, from that point it always causes the y-flip to stuck for the rest of the numeric array inputs as well, until the program finishes.

After running a few tests, it seems that this y-flip bug only seems to occur if the numeric array has more than 12 elements.

## *Where* does it happen?
Regular client sided browser runs with GPUjs. I've tested it with firefox and chrome based browsers as well, it behaves the same. Tried it with dedicated graphic card and integrated graphic chip. Behaves also the same.

## *How* do we replicate the issue?
A quick example to reproduce:

```
const gpu = new GPU();

let kernel = gpu.createKernel(function(a1, a2, a3, a4) {
	return a2[this.thread.x];
}, {
	output: [16],
	debug: true
});

function test() {
	let arr = [
		1, 2, 3, 4,
		5, 6, 7, 8,
		9, 10, 11, 12, 
		13, 14, 15, 16
	];

	let output = kernel(
		999,
		arr,
		new Image(2,2),
		999,
	);
	
	console.log(output);
}

test();
test();
test();
test();
```

=> Float32Array(16) [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]
=> Float32Array(16) [9, 10, 11, 12, 13, 14, 15, 16, 1, 2, 3, 4, 5, 6, 7, 8]
=> Float32Array(16) [9, 10, 11, 12, 13, 14, 15, 16, 1, 2, 3, 4, 5, 6, 7, 8]
=> Float32Array(16) [9, 10, 11, 12, 13, 14, 15, 16, 1, 2, 3, 4, 5, 6, 7, 8]

After the normal expected first run, we can see the y-flip bug happening on the rest of the outputs.

If we would change the image parameter position from a3 to a1 for instance, the y-flip for the rest of the numeric arrays would happen from the first output, because the image would be already processed by that time.

If we don't have an image parameter, this bug doesn't occur even with numeric arrays larger than 12 elements.

I've found some relevant data at the returned debug output:

Running the example with 16 elements: 
```
uniform lowp sampler2D user_a2;
lowp ivec2 user_a2Size = ivec2(2, 2); <-relevant
lowp ivec3 user_a2Dim = ivec3(16, 1, 1); <-relevant
uniform lowp sampler2D user_a3;
lowp ivec2 user_a3Size = ivec2(2, 2);
lowp ivec3 user_a3Dim = ivec3(2, 2, 1);
```

Running the example with 12 elements: 

```
uniform lowp sampler2D user_a2;
lowp ivec2 user_a2Size = ivec2(3, 1); <-relevant
lowp ivec3 user_a2Dim = ivec3(12, 1, 1); <-relevant
uniform lowp sampler2D user_a3;
lowp ivec2 user_a3Size = ivec2(2, 2);
lowp ivec3 user_a3Dim = ivec3(2, 2, 1);
```

## *How* important is this (1-5)?
4

## Expected behavior (i.e. solution)
The expected behavior would be not to apply the y-flip for the normal arrays after the first detected image, only for the given image.

**Comment by psishock** [comment]
Further proof that any detected HTMLimage input will permanently cause the y-flip bug from that point in the whole GPUjs instance. Even if we try to feed only numeric arrays at the testing kernel:

```
let gpu = new GPU();

let arr1 = [
	1, 2, 3, 4,
	5, 6, 7, 8,
	9,	10, 11, 12,
	13, 14, 15, 16
];
	
let arr2 = [
	100, 101, 102, 103,
	104, 105, 106, 107,
	108, 109, 110, 111,
	112, 113, 114, 115
];

const kernelTest = gpu.createKernel(function(a1, a2) {
	return a2[this.thread.x];
}, {
	output: [16]
});

function imageToArray(image) {
	const kernel = gpu.createKernel(function(image) {
		const pixel = image[this.thread.y][this.thread.x];
		this.color(pixel.r, pixel.g, pixel.b, pixel.a);
    }, {
		output: [image.width, image.height],
		graphical: true,
		pipeline: true,
    });
    
	kernel(image);
    const result = kernel.getPixels(true);
    kernel.destroy();
	
	return result;
}

function causeYflipBug() {
	return imageToArray(new Image(2,2));
}

console.log(kernelTest(arr1, arr2));
console.log(kernelTest(arr1, arr2));
console.log(kernelTest(causeYflipBug(), arr2));
console.log(kernelTest(arr1, arr2));

=> Float32Array(16) [100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115]
=> Float32Array(16) [100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115]
=> Float32Array(16) [108, 109, 110, 111, 112, 113, 114, 115, 100, 101, 102, 103, 104, 105, 106, 107]
=> Float32Array(16) [108, 109, 110, 111, 112, 113, 114, 115, 100, 101, 102, 103, 104, 105, 106, 107]
```

Fortunately until a bugfix will happen, a reasonable workaround would be to ditch the original bugged GPUjs instance after we converted the HTMLImage values to a regular array, and use a that new GPUjs instance to do any other caltulations:

```
let gpu1 = new GPU();
let gpu2 = new GPU();

let arr1 = [
	1, 2, 3, 4,
	5, 6, 7, 8,
	9,	10, 11, 12,
	13, 14, 15, 16
];
	
let arr2 = [
	100, 101, 102, 103,
	104, 105, 106, 107,
	108, 109, 110, 111,
	112, 113, 114, 115
];

const kernelTest = gpu2.createKernel(function(a1, a2) {
	return a2[this.thread.x];
}, {
	output: [16]
});

function imageToArray(image) {
	const kernel = gpu1.createKernel(function(image) {
		const pixel = image[this.thread.y][this.thread.x];
		this.color(pixel.r, pixel.g, pixel.b, pixel.a);
    }, {
		output: [image.width, image.height],
		graphical: true,
		pipeline: true,
    });
    
	kernel(image);
    const result = kernel.getPixels(true);
    kernel.destroy();
	
	return result;
}

function causeYflipBug() {
	return imageToArray(new Image(2,2));
}

console.log(kernelTest(arr1, arr2));
console.log(kernelTest(arr1, arr2));
console.log(kernelTest(causeYflipBug(), arr2));
console.log(kernelTest(arr1, arr2));

=> Float32Array(16) [100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115]
=> Float32Array(16) [100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115]
=> Float32Array(16) [100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115]
=> Float32Array(16) [100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115]
```

**Comment by robertleeplummerjr** [comment]
Looking at it now.

**Comment by psishock** [comment]
Thanks Robert for looking at it!

The first test case produced the same flipping error it seems, with the new version:

```
const gpu = new GPU();

let kernel = gpu.createKernel(function(a1, a2, a3, a4) {
	return a2[this.thread.x];
}, {
	output: [16],
	debug: true
});

function test() {
	let arr = [
		1, 2, 3, 4,
		5, 6, 7, 8,
		9, 10, 11, 12, 
		13, 14, 15, 16
	];

	let output = kernel(
		999,
		arr,
		new Image(2,2),
		999,
	);
	
	console.log(output);
}

test();
test();
test();
test();
```

=> Float32Array(16) [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]
=> Float32Array(16) [9, 10, 11, 12, 13, 14, 15, 16, 1, 2, 3, 4, 5, 6, 7, 8]
=> Float32Array(16) [9, 10, 11, 12, 13, 14, 15, 16, 1, 2, 3, 4, 5, 6, 7, 8]
=> Float32Array(16) [9, 10, 11, 12, 13, 14, 15, 16, 1, 2, 3, 4, 5, 6, 7, 8]

The second test case produced a more interesting result however. Instead of the flipping bug, now it produces zeroes with the new version:

```
let gpu = new GPU();

let arr1 = [
	1, 2, 3, 4,
	5, 6, 7, 8,
	9, 10, 11, 12,
	13, 14, 15, 16
];
	
let arr2 = [
	100, 101, 102, 103,
	104, 105, 106, 107,
	108, 109, 110, 111,
	112, 113, 114, 115
];

const kernelTest = gpu.createKernel(function(a1, a2) {
	return a2[this.thread.x];
}, {
	output: [16]
});

function imageToArray(image) {
	const kernel = gpu.createKernel(function(image) {
		const pixel = image[this.thread.y][this.thread.x];
		this.color(pixel.r, pixel.g, pixel.b, pixel.a);
    }, {
		output: [image.width, image.height],
		graphical: true,
		pipeline: true,
    });
    
	kernel(image);
    const result = kernel.getPixels(true);
    kernel.destroy();
	
	return result;
}

function causeYflipBug() {
	return imageToArray(new Image(2,2));
}

console.log(kernelTest(arr1, arr2));
console.log(kernelTest(arr1, arr2));
console.log(kernelTest(causeYflipBug(), arr2));
console.log(kernelTest(arr1, arr2));
```

=> Float32Array(16) [100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115]
=> Float32Array(16) [100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115]
=> Float32Array(16) [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
=> Float32Array(16) [100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115]

**Comment by robertleeplummerjr** [comment]
Fixed in https://github.com/gpujs/gpu.js/releases/tag/2.4.7.
Associated unit tests: https://github.com/gpujs/gpu.js/blob/bdcdf8c98a4bbca97a0aa54eb3b4e49cdebe3ac4/test/issues/553-permanent-flip.js#L1

Ty!

**Comment by psishock** [comment]
Nice job, I can confirm as well after testing, that everything works as expected now with the most recent version.

Thanks for fixing it Robert!

**Comment by robertleeplummerjr** [comment]
👍
