### ISSUE TITLE
Graphical Output doesn't work with Combined Kernels.

### ISSUE THREAD

**Issue by psishock** [gpujs/gpu.js#554]
## *What* is wrong?
Graphical Output (drawing directly to Canvas) doesn't work with Combined Kernels.

What if we would like to pass a few calculations within the kernels by combining them, and display the result directly at the canvas, all without the round trip penalty through GPU-CPU-GPU?

## *Where* does it happen?
Regular client sided browser runs with GPUjs. I've tested it with firefox and chrome based browsers as well, it behaves the same. Tried it with dedicated graphic card and integrated graphic chip. Behaves also the same.

## *How* do we replicate the issue?
```
const canvas = document.getElementById('graphCanvas');
const gl = canvas.getContext('webgl2');
const gpu = new GPU({
	canvas,
	webGl: gl
});

const arr = [1,2,3,4,5,6,7,8,9];

let kernel1 = gpu.createKernel(function(a1) {
	return a1[this.thread.x] * 2;
}, {
	output: [9]
});

let kernel2 = gpu.createKernel(function(a1) {
	this.color(1, 0,  this.thread.x/20, 1);
}, {
	graphical: true,
	output: [20, 20]
});


// console.log(kernel2(arr)); //<- this works as intended, draws directly to the canvas and returns null

const superKernel = gpu.combineKernels(kernel1, kernel2, function(arr) {
	return kernel2(kernel1(arr));
});
console.log(superKernel(arr)); //<- this doesnt work, it just returns the values and doesn't draw to canvas
```

## *How* important is this (1-5)?
3

## Expected behavior (i.e. solution)
Combined kernels should be able to draw to canvas. At very least as the last step, after all the in-between calculations are finished.

**Comment by robertleeplummerjr** [comment]
Looking at this next, fyi.

**Comment by robertleeplummerjr** [comment]
I think there is a bug in `gpu.combineKernels()` (in which we call `.toArray()` on the result from the container function), but ultimately, you don't need it as you are already using `pipeline: true`, and really all that `combineKernels` is, is a means of setting the same context, canvas, and that pipeline is on.  It could, however, be argued, should we call `.toArray()` in the resulting function from `combineKernels`? 

In order for you to get a fix for your code, all you need do is this:
```js
function superKernel(arr) {
	return kernel2(kernel1(arr));
}
```

**Comment by robertleeplummerjr** [comment]
The other thing we could simply do is just return the value from the resulting function from `combineKernels`, but in that case, you'd just have a texture.

**Comment by robertleeplummerjr** [comment]
Going to go ahead and close, as the recommendation should be enough to cover the original issue.

**Comment by psishock** [comment]
Ah yes, wanted to reply on this but slipped my mind.

The recommendations are reasonable, I will use some of those approaches in the future to achieve the desired functionality. Thanks again Robert.
