### ISSUE TITLE
Fails to NPM install on Windows 10

### ISSUE THREAD

**Issue by LRagji** [gpujs/gpu.js#558]
![A GIF or MEME to give some spice of the internet](url)

## *What* is wrong?
Doesnt npm install on Windows 10 even after installing python

## *Where* does it happen?
npm install gpu.js --save

## *How* do we replicate the issue?
On windows 10 with npm install gpu.js --save following is the Error
gyp ERR! configure error 
gyp ERR! stack Error: Command failed: C:\Program Files (x86)\Python38-32\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                       ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:294:12)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Lauki\\AppData\\Roaming\\nvm\\v10.16.3\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Lauki\Documents\git\ts\node_modules\gl
gyp ERR! node -v v10.16.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN y@0.0.1 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gl@4.4.0 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the gl@4.4.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

## *How* important is this (1-5)?
1

## Expected behavior (i.e. solution)
It should install

## Other Comments
Why does this require Python Run time, nothing wrong with it but its another external dependency to download and install

**Comment by HarshKhandeparkar** [comment]
It needs python2 for some reason. I remember someone at IS having this issue too. @robertleeplummerjr

**Comment by LRagji** [comment]
Ok will try that

**Comment by robertleeplummerjr** [comment]
Let us know if that doesn't fix your issue.  Going to go ahead and close for the time being as we have a possible solution.
