### ISSUE TITLE
Boolean and Boolean Argument Combination

### ISSUE THREAD

**Issue by LunarLanding** [gpujs/gpu.js#564]
## *What* is wrong?
Native functions with bool args cannot accept kernel defined boolean values.
`Error: Unhandled argument combination of Boolean and Boolean for argument [...]`

## *Where* does it happen?
https://observablehq.com/d/541be7601b33a7e6@224

## *How* do we replicate the issue?
See above.

## *How* important is this (1-5)?
2?

## Expected behavior (i.e. solution)
The kernel compiling and running without errors.

**Comment by robertleeplummerjr** [comment]
Fixed in 2.6.0, fyi.  Unit tests: https://github.com/gpujs/gpu.js/blob/de98b0102d855df96043483d5b616397ca5439fd/test/issues/564-boolean.js#L11
