### ISSUE TITLE
Modulo operator occasionally fails when quotient is a variable

### ISSUE THREAD

**Issue by stewdio** [gpujs/gpu.js#567]
## *What* is wrong?
Within a kernel, the modulo operator, `%`, fails on particular values when the quotient is a non-literal, ie. a variable. For example, `91 % 7` will return `0` as expected, but `q = 7; 91 % q` will return `7`! I know other examples exist, but this is the first one I spotted in particular. 

## *Where* does it happen?
I observed this using GPU.js in **Google Chrome** 79.0.3945.117 (Official Build) (64-bit) for **macOS Mojave** 10.14.6 running on a MacBook Pro (15-inch, 2018) with a Radeon Pro Vega 20 4 GB / Intel UHD Graphics 630 1536 MB.

## *How* do we replicate the issue?
Create a kernel that returns `91 % 7` to observe the expected behavior. Then create a kernel that returns `91 % q` when the value of `q` has been declared as `7` to observe the errant behavior. 

## *How* important is this (1-5)?
I’d say pretty important! I’m doing quite a bit of factoring, so for me it’s a 5. I realize it’s probably not an issue for many other folks though so ... let’s go with 3?

## Expected behavior (i.e. solution)
I’ve worked around this issue for the time being by writing my own simple `mod` function within the kernel and calling that instead of using the `%` operator (or in-lining this function’s logic for even more speed):
~~~javascript
function mod( n, q ){

    return n - ( i * ( n / i ))
}
~~~

**Comment by robertleeplummerjr** [comment]
I will look at this next.

**Comment by robertleeplummerjr** [comment]
As far as I can tell, this is a system bug.  Very odd indeed.

**Comment by robertleeplummerjr** [comment]
Fixed in v 2.6.0, fyi.  Unit tests here: https://github.com/gpujs/gpu.js/blob/de98b0102d855df96043483d5b616397ca5439fd/test/issues/567-wrong-modulus.js#L9


This was a pill.

**Comment by stewdio** [comment]
Thank you for looking in to this!

**Comment by robertleeplummerjr** [comment]
👍
