### ISSUE TITLE
Trouble installing on Windows 10

### ISSUE THREAD

**Issue by jonCliq** [gpujs/gpu.js#571]
![A GIF or MEME to give some spice of the internet](url)

## *What* is wrong?
I run npm i gpu.js and get a nasty error. I apologize if the answer is clear in the error I'm getting, I just have no clue how to go about debugging it.

## *Where* does it happen?
in my command prompt

## *How* do we replicate the issue?
npm i gpu.js

> gl@4.4.1 install C:\code\learn-brainjs\node_modules\gl
> prebuild-install || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=10.17.0 runtime=node arch=ia32 libc= platform=win32)

C:\code\learn-brainjs\node_modules\gl>if not defined npm_config_node_gyp (node "C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Warning: Missing input files:
C:\code\learn-brainjs\node_modules\gl\deps\windows\dll\ia32\libGLESv2.dll
C:\code\learn-brainjs\node_modules\gl\deps\windows\dll\ia32\libEGL.dll
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  Copying C:\code\learn-brainjs\node_modules\gl/deps/windows/dll/ia32/libEGL.dll to C:\code\learn-brainjs\node_modules\gl\build\Release\libEGL.dll
  The system cannot find the path specified.
  Copying C:\code\learn-brainjs\node_modules\gl/deps/windows/dll/ia32/libGLESv2.dll to C:\code\learn-brainjs\node_modules\gl\build\Release\libGLESv2.d
  ll
  The system cannot find the path specified.
  bindings.cc
  webgl.cc
  procs.cc
  win_delay_load_hook.cc
LINK : fatal error LNK1104: cannot open file 'libEGL.lib' [C:\code\learn-brainjs\node_modules\gl\build\webgl.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:193:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\code\learn-brainjs\node_modules\gl
gyp ERR! node -v v10.17.0
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok
npm WARN acorn-jsx@5.1.0 requires a peer of acorn@^6.0.0 || ^7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"ia32"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gl@4.4.1 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the gl@4.4.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\jbest\AppData\Roaming\npm-cache\_logs\2020-01-23T22_31_02_859Z-debug.log

## *How* important is this (1-5)?
5 (i cant use this project, or brain.js)

## Expected behavior (i.e. solution)
It installs

**Comment by robertleeplummerjr** [comment]
This looks related: https://github.com/stackgl/headless-gl/issues/96

**Comment by robertleeplummerjr** [comment]
Going to go ahead and close, as this is an error specific to HeadlessGL, which is documented and if you have dependencies installed, it should be easy to get around.
