### ISSUE TITLE
Hello one question!

### ISSUE THREAD

**Issue by pedrocarvajal** [gpujs/gpu.js#574]
Hello one question!
with this library can you read an array of objects? So: 
[{price: 100}, {price: 100}, {price: 100}]
So you can loop to an array of more than 1,000,000 elements. and do certain functions or tasks faster.

Do you understand my question?

**Comment by robertleeplummerjr** [comment]
Sorry it took so long to get to this, currently there is no means to directly send an object, the means would be to deal with arrays, typed arrays, textures, or primitives.
