### ISSUE TITLE
Draw only a set of lines on Canvas based on their x,y positions  

### ISSUE THREAD

**Issue by am2222** [gpujs/gpu.js#575]
Hi,
I have looked at the canvas examples which are using `GPU.js` to render a canvas. Based on my understanding in the kernel we have to return a color based on `this.thread.x` and `this.thread.y` values. This kind of kernel is  useful for the canvas, which we have a color for each pixel. But sometimes we only need to draw a point or a lines on the canvas. The main application of this is for drawing maps (in some libraries for map rendering), which we use `canvas.moveTo(x,y)` and `canvas.moveTo(x,y)` to draw a line and fill inside it using `canvas.fill()`
Well with considering such approach of drawing on the canvas how is it possible to use gpu.js?

**Comment by robertleeplummerjr** [comment]
To clarify GPU.js is not a js library for drawing lines, it is a library to accelerate math (arrays, matrices, and cubes), that in some cases can be drawn. To see the math in how to draw a line using a shader, you could check out something like https://www.shadertoy.com/view/4ljfRD.

**Comment by am2222** [comment]
@robertleeplummerjr Hi,
Thanks for the reply, I think I did not ask my question clearly, I wanted to use gpu.js to accelerate the drawing on the canvas, but I think it is only possible to return a color per each pixel for the canvas and it is not possible to use canvas functions in this context.

**Comment by robertleeplummerjr** [comment]
> it is not possible to use canvas functions in this context.

That is true, you have to use ray tracing, like this: https://observablehq.com/@robertleeplummerjr/time-coordinates-with-gpu-js

**Comment by am2222** [comment]
@robertleeplummerjr Thanks so much

**Comment by robertleeplummerjr** [comment]
The other, faster, approach, is to use something like: https://robertleeplummerjr.github.io/Leaflet.glify/

**Comment by am2222** [comment]
@robertleeplummerjr Do you think that webgl might show better performance than this approach?
