### ISSUE TITLE
Safari support?

### ISSUE THREAD

**Issue by brianxautumn** [gpujs/gpu.js#58]
When I try to run on safari I get:
WebGL: INVALID_ENUM: readPixels: invalid type

**Comment by fuzzie360** [comment]
Thanks for the report.

The issue is Safari does not support readPixels with float type. There is already code to detect if the browser supports this, but it seems I have been broken recently. I will fix it soon.

**Comment by robertleeplummerjr** [comment]
Safari is supported, with the limitation of kernel maps.

**Comment by robertleeplummerjr** [comment]
via: https://github.com/gpujs/gpu.js/pull/234#issuecomment-352312020
>I don't think it should be fixed in this manner.

Reopening to try and find a quick fix for v1

**Comment by robertleeplummerjr** [comment]
Let's get this resolved.  Here is a quick and dirty possibility to skirt this issue https://github.com/gpujs/gpu.js/pull/235

**Comment by robertleeplummerjr** [comment]
The texture issue is resolved as of https://github.com/gpujs/gpu.js/releases/tag/1.0.0, however there is some sort of texture size issue that needs to be resolved before this can be closed.

**Comment by robertleeplummerjr** [comment]
Now supported, with limits, in v2 rc13.

**Comment by robertleeplummerjr** [comment]
Even unit tests pass, yay!
