### ISSUE TITLE
In place Array oporations 

### ISSUE THREAD

**Issue by Richard-Mathie** [gpujs/gpu.js#59]
Currently argument arrays are read only. However this limits the kind of operations that are possible.

For instance it is not possible to define FFT like algorithms as you have to map to the array output, necessitating an N^2 operation.

That is it is not possible to separate the size and shape of the kernel from the size and shape of the outputted/modified array.

Would it be possible to support this mode of operation? What would be needed in gpu_core.js to achieve this?

**Comment by brianxautumn** [comment]
This is relevant to my interests.

**Comment by PicoCreator** [comment]
Hi @Richard-Mathie @brianxautumn , 

This is sadly however a hard limitation in the current webgl pipeline, that writable data is not sharable between threads.

Behind the scene we are hacking each thread to output a pixel. This effectively limits each thread to output / modify. A single pixel (or less) worth of data. Where no writable memory is shared across threads.

However if your referring to temporary data. In concept it maybe possible, in rather convoluted ways to modify temporary arrays within a single thread. Though this involves rather "ugly" implementations of linked lists, which could perform really badly.

Unity for example : do implement a linkedlist when compiling to webgl, cant find the full docs though : https://issuetracker.unity3d.com/issues/webgl-crashes-on-foreach-on-a-linkedlist

**Comment by fuzzie360** [comment]
Ignoring the WebGL limitation that prevents source and destination texture to be the same, It is actually impossible to implement a in-place algorithm on the GPU without any synchronization primitives (which gpu.js does not provide).

You can however implement a double buffer algorithm which only requires twice the space at O(1) and O(n) passes.

**Comment by robertleeplummerjr** [comment]
so close?

**Comment by robertleeplummerjr** [comment]
These may give you what you are looking for: https://github.com/gpujs/gpu.js#create-kernels or https://github.com/gpujs/gpu.js#combining-kernels

**Comment by robertleeplummerjr** [comment]
Closing because of the limitations of GPU/WebGL, to keep backlog clean.  Will gladly reopen if a means is found though or needs to be re-evaluated.

**Comment by GirkovArpa** [comment]
So it's impossible to modify any array?

```javascript
array[0] = 0;
```

That line will never compile inside a kernel no matter what?

**Comment by robertleeplummerjr** [comment]
If you create an array _on the GPU_ from size _2 to 4_, you can modify it on the GPU.  However, you cannot modify an array that has been _uploaded to the GPU_, as this would essentially translate to modifying a primitive (imagine `4 = 0`), and not the object's property reference (`array[0] = 0`).

**Comment by GirkovArpa** [comment]
Interesting, I was just fiddling with `fragment-shader.js` and found replacing `__KERNEL__` with the following works as expected:

```javascript
float kernelResult;
void kernel() {
  float arr[10];
  for (int i = 0; i < 10; i++) arr[i] = float(i);
  kernelResult = arr[9];
  return;
}
```

This throws a `Markup type undefined` error though:

```javascript
const kernel = gpu.createKernel(function () {
  const arr = [0];
  return 1;
}).setOutput([1]);
```

So how does one declare an array on the GPU without modifying `fragment-shader.js` directly?

**Comment by GirkovArpa** [comment]
Also why did you specify `array on the GPU from size 2 to 4`, when I believe I just demonstrated creating an array of size 10?

**Comment by robertleeplummerjr** [comment]
>Interesting, I was just fiddling with fragment-shader.js and found replacing __KERNEL__ with the following works as expected:

We have to work with compatibility in WebGL1 in addition to WebGL2.  If memory serves me right, that was later added in WebGL2.  If you find a way, by all means, please share!

>So how does one declare an array on the GPU without modifying fragment-shader.js directly?

On the GPU they are all vec's, so:
1. `[0, 1]` translates to `vec2(0, 1)`
2. `[0, 1, 2]` translates to `vec3(0, 1, 2)`
3. `[0, 1, 2, 3]` translates to `vec4(0, 1, 2, 3)`

We also support end to end type inference (yes, meager javascript CAN be strongly typed!  Because it is detected at build time, not develop time) and we can even return arrays of size 2 to 4 when GPU Floats are supported:
```js
const gpu = new GPU();
const kernel = gpu.createKernel(function() {
  return typeMe(this.thread.x);
  function typeMe(value) {
    const array = [value, value, value, value];
    
    for (let i = 0; i < 4; i++) {
      array[i] += i;
    }

    return array;
  }
}, { output: [2] });
console.log(kernel());

/* Array(2) [
  0: Float32Array(4) [0, 1, 2, 3]
  1: Float32Array(4) [1, 2, 3, 4]
] */
```

I've added the example here to play with: https://observablehq.com/@robertleeplummerjr/gpu-js-typed-array-operations
