### ISSUE TITLE
Answer of a simple sum program is coming wrong

### ISSUE THREAD

**Issue by tusharsinghal1610** [gpujs/gpu.js#591]
![A GIF or MEME to give some spice of the internet](url)

## *What* is wrong?
Output of very simple sum program is wrong
answer as output 49992896
answer should be 49995000

## *Where* does it happen?
running on windows 10 

## *How* do we replicate the issue?
simply run the below code 

const GPU = require("gpu.js")
const gpu = new GPU.GPU();
const myFunc = gpu.createKernel(function() {
    let t=0;
    for(let i=0;i<this.constants.size;i++){
        t+=i;
    }
    return t;
} , {
    constants: { size: 10000 },
    output: [1]
  });
    
a = myFunc();
console.log(a);

## *How* important is this (1-5)?
5

## Expected behavior (i.e. solution)
data types are not managed i guess

## Other Comments
Please help fast , i need to use this library on a bigger program, it was just for testing and i got the error

**Comment by GirkovArpa** [comment]
I just reproduced this error on my own computer.

**Comment by HarshKhandeparkar** [comment]
Can you tell if the answer is correct if you change the line `const gpu = GPU.GPU();` to `const gpu = GPU.GPU({mode: 'cpu'});`

**Comment by robertleeplummerjr** [comment]
It is.  The problem is GPU precision.  Still investigating.

**Comment by HarshKhandeparkar** [comment]
Is win10 the problem or does it not work on any OS/GPU?

**Comment by robertleeplummerjr** [comment]
With larger integers like that, you'll have precision issues, especially if there is a ton of incremental math, but there are ways to get around it, one way is by scaling the value that you increment by.  Here I scaled down by 10, and then up by 10 after it is back on the CPU: https://observablehq.com/@robertleeplummerjr/gpu-js-issue-591

A pretty stellar read up on this: https://www.experoinc.com/post/a-quick-note-on-gpu-accuracy-and-double-precision

My bet is that with a more expensive GPU (likely you are using an intel flavor?  They are notoriously...  the right word escapes me right now) the precision may be better.

**Comment by robertleeplummerjr** [comment]
>Is win10 the problem or does it not work on any OS/GPU?

The problem is probably hardware related.  You'll get the same results on windows or OSX.

**Comment by robertleeplummerjr** [comment]
I would also like to give my condolences to you.  We try and build a tool to harness the hardware, and we've done a pretty good job, but sometimes the hardware is erroneous.  Perhaps there is something we could do to handle this.  I'm still tinkering.

**Comment by HarshKhandeparkar** [comment]
Is there a way to use 32bit *integers* instead of 32bit *floats*? (By strongly typing the inner variables)
