### ISSUE TITLE
Error compiling fragment shader

### ISSUE THREAD

**Issue by MelerEcckmanLawler** [gpujs/gpu.js#592]
![Stoner dog](https://i.imgur.com/6iNtW4z.jpg)

## *What* is wrong?

Error: Error compiling fragment shader: ERROR: 0:504: 'user_aSize' : undeclared identifier
ERROR: 0:504: 'user_aDim' : undeclared identifier
ERROR: 0:504: 'getMemoryOptimized32' : no matching overloaded function found
ERROR: 0:504: 'user_bSize' : undeclared identifier
ERROR: 0:504: 'user_bDim' : undeclared identifier
ERROR: 0:504: 'getMemoryOptimized32' : no matching overloaded function found

## *Where* does it happen?
In GPU.js when trying to test the example on Windows 10 64 bit.

## *How* do we replicate the issue?
Run this code in Node:

    const { GPU } = require('gpu.js');
    const gpu = new GPU();
    const multiplyMatrix = gpu.createKernel(function(a, b) {
        let sum = 0;
        for (let i = 0; i < 512; i++) {
            sum += a[this.thread.y][i] * b[i][this.thread.x];
        }
        return sum;
    }).setOutput([512, 512]);
    const c = multiplyMatrix(100, 100);

## *How* important is this (1-5)?
5, because it's literally a copy-and-pasted example that doesn't work.

## Expected behavior (i.e. solution)
The program should run then exit.

**Comment by HarshKhandeparkar** [comment]
Hi! Where have you copied this example from? It is wrong.

The two inputs, `a` and `b` have to be 2D matrices but you have passed numbers `multiplyMatrix(100, 100)`.

**Comment by MelerEcckmanLawler** [comment]
My fault for saying it was "literally a copy-and-pasted example", I did put in numbers for `a` and `b` because I don't quite understand what's going on and thought `.setOutput([512, 512])` meant it was going to create 2 matrices, one full of `a` and the other full of `b`, and multiply them together ...

**Comment by HarshKhandeparkar** [comment]
This example is a little better explained on https://gpu.rocks. That is what I had referred when i started with gpu.js.
