### ISSUE TITLE
Array.indexOf()

### ISSUE THREAD

**Issue by GirkovArpa** [gpujs/gpu.js#596]
![Rastafarian Math Teacher](https://i.imgur.com/O8UmeXl.jpg)

## *What* is wrong?
I don't know how to find the index of a number inside an array.

## *Where* does it happen?
Writing a GPU.js kernel.

## *How* important is this (1-5)?
2 I suppose.

## Expected behavior (i.e. solution)
I want to use `[0, 1, 2].indexOf(2)` to find the index of 2 in an array.  I know I can use an `if` statement but I read that that dramatically reduces performance, so I want a way without that.

**Comment by HarshKhandeparkar** [comment]
indexOf will use if in the background. If you want to find the index then you will have to know it beforehand. This is how the GPU computation works. There should be nothing that is unpredictable. Everything should have a deterministic procedure and should be predictable.

If you want to use an array as an input, you can't run a specific operation on a specific element, you have to do the same operation on each element.

**Comment by HarshKhandeparkar** [comment]
Is there a need for finding a specific element's index?
If so, there is something you can do. You can find the index in parallel. You can check all indices at once.

createKernel(function(array){
  if (array[this.thread.x] == 2) {
    // do something
  }
}, {
output: [size_of_array]
})

**Comment by GirkovArpa** [comment]
Thanks, that seems like a neat idea.
