### ISSUE TITLE
Using `${parameterName}Size` as variable name clashes with internal variable naming convention if `parameterName` is an array

### ISSUE THREAD

**Issue by GirkovArpa** [gpujs/gpu.js#598]
![Baby Yoda](https://i.imgur.com/gSwcZBP.png)

## *What* is wrong?
Declaring `aSize` as variable throws the following error if `a` is an argument whose type is an array:

```javascript
Error compiling fragment shader: ERROR: 0:504: 'getMemoryOptimized32' : no matching overloaded function found
```

## *Where* does it happen?
In a galaxy far, far away.

## *How* do we replicate the issue?
```javascript
const { GPU } = require('gpu.js');
const gpu = new GPU();
gpu.createKernel(function (a) {
	let aSize = 1;
	return a[0];
}, { output: [1] })([0]);
```

## *How* important is this (1-5)?
1

## Expected behavior (i.e. solution)
Shouldn't cause an error.

## Other Comments
It's easy to workaround (by renaming the variable) but if you aren't aware of the bug it's really confusing.

**Comment by GirkovArpa** [comment]
Not a big deal.

**Comment by robertleeplummerjr** [comment]
We would be up for a PR to enhance the behavior.
