### ISSUE TITLE
Using functions as a constant.

### ISSUE THREAD

**Issue by squishybanana04** [gpujs/gpu.js#60]
An error occurred compiling the shaders: ERROR: 0:135: 'constants' : undeclared identifier 
ERROR: 0:135: 'constants_pixelMultiplier' : undeclared identifier 
ERROR: 0:135: 'constants_scale' : undeclared identifier 
ERROR: 0:135: '' : methods supported in GLSL ES 3.00 and above only  
ERROR: 0:135: 'func' : invalid method 
ERROR: 0:135: 'assign' :  cannot convert from 'const int' to 'highp float'

Here is my code.
```javascript
let gpu = new GPU();
function generateArrayWithFunction(w, h, scale, f) {
	/*let output = [];
	for (let x = 0; x < w * pixelMultiplier; x++) {
		output.push([]);
		for (let y = 0; y < h * pixelMultiplier; y++) {
			output[x][y] = f(x / pixelMultiplier * scale, y / pixelMultiplier * scale, 0);
		}
	}

	return output;*/
	let g = gpu.createKernel(function() {
		return this.constants.func(this.thread.x / this.constants.pixelMultiplier * this.constants.scale, this.thread.y / this.constants.pixelMultiplier * this.constants.scale, 0);
	}).dimensions({dimensions: [w, h], constants: {func: f, pixelMultiplier: pixelMultiplier, scale: scale}});
	return g();
}
```

**Comment by fuzzie360** [comment]
The intended use case for constants if for using it as parameters the fixed length for loops that is required by WebGL. Thus, using functions as constants is not documented and should not be used.
