### ISSUE TITLE
Benchmark not working on web site

### ISSUE THREAD

**Issue by Benoit9** [gpujs/gpu.js#615]
I tried http://gpu.rocks/#/benchmark on several browsers and different machines: I don't see any result. The buttons animates, then nothing.

**Comment by HarshKhandeparkar** [comment]
@Benoit9 Thanks for opening the issue. BTW, the website repo is gpujs/gpu.rocks so you can open the issue there.

**Comment by HarshKhandeparkar** [comment]
I am aware of this. I have been meaning to move to benchmark v3 for a long time but there is a lot of bad old code that needs to be moved.

**Comment by Benoit9** [comment]
Moved to website repo
