### ISSUE TITLE
Using webgl scripts

### ISSUE THREAD

**Issue by thesteeltoenail** [gpujs/gpu.js#62]
What if along with the function inputs we could use a string that has a webgl script and has access to all the inputs. That would make it more reliable seeing as the compiling is not perfect yet.

**Comment by fuzzie360** [comment]
We do have plans to add an API that will allow you to specify both JavaScript and WebGL implementations of a segment of code, but we haven't planned how the API will look like.

**Comment by robertleeplummerjr** [comment]
Related: https://github.com/gpujs/gpu.js/issues/79

**Comment by robertleeplummerjr** [comment]
As of https://github.com/gpujs/gpu.js/commit/d5cb8bbd37c19395d6ab2a51ad96d86ad2964761 you can now do this:
```js
var gpu = new GPU();
var myFunction = gpu.createKernel(function() {
  return amazingNoise();
});
myFunction.addGLSLFunction('amazingNoise', `highp float rand(vec2 co)
{
    highp float a = 12.9898;
    highp float b = 78.233;
    highp float c = 43758.5453;
    highp float dt= dot(co.xy ,vec2(a,b));
    highp float sn= mod(dt,3.14);
    return fract(sin(sn) * c);
}`);
```

**Comment by robertleeplummerjr** [comment]
Note, I created this as a means of implementing a fix for this https://github.com/gpujs/gpu.js/issues/164 but because of the complexity of random numbers, I ended up partially rolling it back and using the abstractions for resolving this issue.

**Comment by radio412** [comment]
Sorry, I am a bit confused, so this is currently not working? The example with the latest "develop" branch I get "An error occurred compiling the shaders: ERROR: 0:133: 'amazingNoise' : no matching overloaded function found"

**Comment by robertleeplummerjr** [comment]
I'll double check it at my earliest and ensure there is a test for it, fyi.

**Comment by robertleeplummerjr** [comment]
The name was changed to `addNativeFunction` here: https://github.com/gpujs/gpu.js/commit/49c8af0a4478049cdf6e62b0eeb319d5fe499884 but is tested, care to try latest again?
