### ISSUE TITLE
Error compiling fragment shader

### ISSUE THREAD

**Issue by sacredvoid** [gpujs/gpu.js#620]
![A GIF or MEME to give some spice of the internet](url)

## *What* is wrong?

- After I play the video (which I process and put into another canvas) I get the Error Compiling Fragment Shader error.
```
Uncaught (in promise) Error: Error compiling fragment shader: ERROR: 0:471: 'assign' : l-value required
ERROR: 0:474: 'assign' : l-value required

    at WebGL2Kernel.build (gpu-browser.min.js:14)
    at WebGL2Kernel.t (gpu-browser.min.js:14)
    at n (gpu-browser.min.js:14)
    at Object.predictModel (processor.js:174)
```
## *Where* does it happen?

When I try to run the following kernel:
```
      const gpu = new GPU();
      const kernel_normalize = gpu.createKernel(function (y_buffer,u_buffer,v_buffer,pixels) {
        for(let i=0; i<pixels; i++){
          if(y_buffer[this.thread.x] < 0 ) y_buffer[this.thread.x]=0;
          if(y_buffer[this.thread.x] > 1 ) y_buffer[this.thread.x]=1;
          this.color(y_buffer[this.thread.x],u_buffer[this.thread.x],v_buffer[this.thread.x]);
        }
      })
      .setOutput([this.orig_cols * this.scale_factor , this.orig_rows * this.scale_factor])
      .setGraphical(true);

      const canvas_gpu = kernel_normalize.canvas;
      document.getElementsByTagName('body')[0].appendChild(canvas_gpu);
```
## *How* do we replicate the issue?

Running the above function on video tag data obtained using the getImageData.

## *How* important is this (1-5)?

5

## Expected behavior (i.e. solution)

It should show the same video data on a canvas, but is giving me a black canvas (repeatedly appending to the body tag).

**Comment by HarshKhandeparkar** [comment]
Which version are you using?

**Comment by HarshKhandeparkar** [comment]
Also what are y_buffer, u_buffer and v_buffer?

**Comment by HarshKhandeparkar** [comment]
The last part of [this](https://github.com/gpujs/gpu.js#input-examples) section.

**Comment by sacredvoid** [comment]
> Which version are you using?

I'm using the latest version from the unpkg cdn. 

> Also what are y_buffer, u_buffer and v_buffer?

they are JS arrays, I converted the RBG input from the Video Tag to YUV, and split them, performed some operations. The final output (after performing the operations) is stored in y_buffer, u_buffer and v_buffer which will then be displayed on canvas. I'm getting black frames. Is there something wrong with the kernel code (I think I didn't quite understand the use of this.thread.x) or the way I'm trying to put it back into the canvas?


> The last part of [this](https://github.com/gpujs/gpu.js#input-examples) section.

Yes, I did. Will have a look at it again, in the mean time if you could help with the above mentioned question it would be really helpful. Thanks!

**Comment by HarshKhandeparkar** [comment]
You are only using `this.thread.x` but the output is 2D, is that intended?

**Comment by HarshKhandeparkar** [comment]
Also, what is `pixels`?

**Comment by HarshKhandeparkar** [comment]
BTW, to use canvas, you need to initialize it with canvas.
```js
const gpu = new GPU({
canvas: document.getElementById('#canvas')
})
```

**Comment by HarshKhandeparkar** [comment]
```
for(let i=0; i<pixels; i++){
```
You can call this.color only once.

**Comment by sacredvoid** [comment]
> Also, what is `pixels`?

pixels is the size of the array

> You are only using `this.thread.x` but the output is 2D, is that intended?

I don't think so, I'll correct that. Also, does the this.color() accept only R,G,B values? Because right now I'm passing it Y,U,V values, I think that could be one reason for black frames. 

> BTW, to use canvas, you need to initialize it with canvas.
> 
> ```js
> const gpu = new GPU({
> canvas: document.getElementById('#canvas')
> })
> ```
> 
> And it will automatically update the kernel :)

awesome, I'll try it

**Comment by HarshKhandeparkar** [comment]
> Also, does the this.color() accept only R,G,B values?
I accepts rgba (a optional) and the values are between 0 and 1.

**Comment by sacredvoid** [comment]
@HarshKhandeparkar Hey, for some reason the following code is not working, could you help me out here?
```
const gpu = new GPU();

      const kernel_normalize = gpu.createKernel(function(y_buffer){
        const y_b = y_buffer;
        for(var i=0;i<this.constants.size;i++){
          if(y_b[this.thread.x] > 1) 
            y_b[this.thread.x] = 1;
        }
        return y_b;
      },{
        constants: { size: upscaled_numPixels },
        output: [upscaled_numPixels],
      });
```

**Comment by HarshKhandeparkar** [comment]
What is y_buffer? You can only return 1D,2D oor 3D arrays. See https://github.com/gpujs/gpu.js#creating-and-running-functions

**Comment by sacredvoid** [comment]
> What is y_buffer? You can only return 1D,2D oor 3D arrays. See https://github.com/gpujs/gpu.js#creating-and-running-functions

Yes, I've read that, it's a 1D array, I've defined the output size.

**Comment by HarshKhandeparkar** [comment]
Oh you can't really assign to a texture directly.

> y_b[this.thread.x] = 1;
You can't do this.

**Comment by sacredvoid** [comment]
Okay let's say I pass a 1 D array into the kernel, how do I go about editing the values and returning it?

**Comment by HarshKhandeparkar** [comment]
Make a new variable, edit it, return it. The data that is passed on to the kernel is stored on the GPU's fast onboard memory and will be accessed by all threads at once so you can't edit it, it is read-only.

**Comment by sacredvoid** [comment]
I realised I didn't need a for loop. I ran a sample test:
```
            console.time();
            var a = new Float32Array(10000000);
            const gpu = new GPU();
            const kernel = gpu.createKernel(function(a){
                if(this.thread.x % 2 ==0)
                {
                    var x=a[this.thread.x]+200;
                    return 100;
                }
                else return -100;
            }).setOutput([10000000]).setConstants({size:10000000});
            const out = kernel(a);
            console.log(out);
            console.timeEnd();
```
Which gave me the correct output. I tried replicating it like this:

```
const gpu = new GPU();

      const kernel_normalize = gpu.createKernel(function(y_buffer){
        
          if(y_buffer[this.thread.x] > 1){ 
            y_buffer[this.thread.x] = 1;
            return y_buffer[this.thread.x];
          }
          else {return y_buffer[this.thread.x];}
      },{
        constants: { size: upscaled_numPixels },
        output: [upscaled_numPixels],
      });

      var norm_Y_buffer = kernel_normalize(Y_upscaled_array);
      console.log("Normalised Y buffer",norm_Y_buffer);
```
_Y_upscaled array is a Float 32 array._

but this gives me an error : `ERROR: 0:462: 'assign' : l-value required`

@HarshKhandeparkar do you know why this is happening?

**Comment by sacredvoid** [comment]
`ERROR: 0:462: 'assign' : cannot convert from 'const float' to 'lowp int'`

With the following code:
```
const gpu = new GPU();

      const kernel_normalize = gpu.createKernel(function(y_buffer){
        
          if(this.thread.x > 1){ 
            this.thread.x = 1.0;
            return this.thread.x;
          }
          else {return this.thread.x;}
      },{
        constants: { size: upscaled_numPixels },
        output: [upscaled_numPixels],
      });

      var norm_Y_buffer = kernel_normalize(Y_upscaled_array);
      console.log("Normalised Y buffer",norm_Y_buffer);
      alert("kernel_normalize works");
```
_y_buffer is a Float32 array_

Any idea about this? @HarshKhandeparkar 
Really appreciate your help

**Comment by HarshKhandeparkar** [comment]
As I said, you can't reassign any internal variables, `this.thread.x` included. It says it is a `**const** float`.

You should rather do `let x = this.thread.x;` and then reassign x if you want to :slightly_smiling_face:

**Comment by sacredvoid** [comment]
Thanks! I finally got it to work, now I understand this library much better, thanks again for all the help 💯  @HarshKhandeparkar

**Comment by SparkHao** [comment]
> ERROR: 0:474: 'assign' : l-value required
> �
>     at WebGL2Kernel.

How did you solve this error?
