### ISSUE TITLE
DOMException thrown

### ISSUE THREAD

**Issue by naratteu** [gpujs/gpu.js#621]
![image](https://user-images.githubusercontent.com/10435867/85926447-814e6000-b8da-11ea-9a1b-65ec67411ad3.png)

로컬경로로 받은 예제를 실행하는데 왜 CORS에러가 발생하나요?
I just ran the example from the local path and why that happen CORS problem?

**Comment by HarshKhandeparkar** [comment]
Try using a local server such as apache or an extension for your code editor.
Otherwise, put the file in the same directory as the one that has index.html

Also, this error is not caused by gpu.js, so we can't help you much here :)

**Comment by naratteu** [comment]
ok, i solved using by chrome extension : [https://chrome.google.com/webstore/detail/web-server-for-chrome/ofhbbkphhbklhfoeikjpcbhemlocgigb](url)
thanks
