### ISSUE TITLE
toArray() causes memory leaks

### ISSUE THREAD

**Issue by callumhay** [gpujs/gpu.js#625]
## *What* is wrong?
Using toArray() appears to cause memory leaks for immutable textures (see below).

## *Where* does it happen?
In GPU.js, running on my Windows 7 PC, headlessgl in node.js v12.18.1.

## *How* do we replicate the issue?
Here is the code to reproduce on my system:
```
const pipelineFuncSettings = {
  output: [8, 8, 8],
  pipeline: true,
  returnType: 'Array(3)',
};

const clearFuncImmutable = gpu.createKernel(function(colour) {
  return [colour[0], colour[1], colour[2]];
}, {...this.pipelineFuncSettings, immutable: true, argumentTypes: {colour: 'Array(3)'}});

let framebufferTex =  clearFuncImmutable([0,0,0]);
while (true) {
  framebufferTex.delete();
  framebufferTex = clearFuncImmutable([0,0,0]);
  framebufferTex.toArray();
}
```
Let that run and watch the node.exe memory climb forever.
If you remove the toArray() line (i.e., `framebufferTex.toArray();`) then the program no longer appears to leak memory.

## *How* important is this (1-5)?
5. This shouldn't leak memory... or the documentation should explain clearly why this would leak memory and how to avoid it and get a CPU buffer from your textures/framebuffers without worrying about it.

## Expected behavior (i.e. solution)
This shouldn't leak memory, I should be able to loop forever - grabbing a CPU array of my framebuffer texture each time - in a stable state.

**Comment by callumhay** [comment]
The issue exists in GLTexture (src/backend/gl/texture/index.js) in the function call to `framebuffer()`:
```
 framebuffer() {
    if (!this._framebuffer) {
      this._framebuffer = this.context.createFramebuffer();
    }
    this._framebuffer.width = this.size[0];
    this._framebuffer.height = this.size[1];
    return this._framebuffer;
  }
```
In every single iteration, `this.framebuffer` is undefined, which causes the creation of a new framebuffer.

**Comment by robertleeplummerjr** [comment]
Looking at this now, fyi.

**Comment by robertleeplummerjr** [comment]
If we move framebuffer management to the kernel (every texture had to come from some kernel) we can store the framebuffers there and their delete would happen on when the kernel is deleted, and thus reuse framebuffers for the most part.  I wrote up a small patch that adjusts this and the only memory leaks would be when using dynamic sized kernels as far as I can tell, because as far as I have seen using framebuffers with different sizes is unwise and can lead to unstable output.  I'll push up my findings shortly.

**Comment by robertleeplummerjr** [comment]
Pushed changes to https://github.com/gpujs/gpu.js/tree/625-framebuffer-leak

**Comment by robertleeplummerjr** [comment]
Can you try the above branch and let me know if it resolves your issue?

**Comment by robertleeplummerjr** [comment]
This should be completely resolved in https://www.npmjs.com/package/gpu.js/v/2.10.0
