### ISSUE TITLE
render directly to existing canvas

### ISSUE THREAD

**Issue by Yatekii** [gpujs/gpu.js#68]
Hi!

Is it possible to render directly to an existing canvas instead of a new one?

Thanks
Yatekii

**Comment by robertleeplummerjr** [comment]
What are you trying to accomplish?

**Comment by Yatekii** [comment]
Rendering to an existing canvas?

**Comment by robertleeplummerjr** [comment]
If you use the develop branch, and are in a browser that supports es6, you can do:
```js
const gpu = new GPU({ canvas: myCanvasObject });
const muchMaths = gpu.createKernel(function(math1, math2, math3) {
  //do much stuff with math
}, {
  graphical: true
});
muchMaths(math1, math2, math3);
```

You can render to your canvas.

**Comment by Yatekii** [comment]
Thank you! That was what I was looking for and I couldn't finde in the docs.
