### ISSUE TITLE
Proposal: nested function type handling

### ISSUE THREAD

**Issue by robertleeplummerjr** [gpujs/gpu.js#75]
Currently there is a limitation of types inside nested functions within kernel creation.  For example:

```js
const kernel = gpu
  .addFunction(function add(a, b, y, x) {
    return a[y][x] + b[y][x];
  })
  .createKernel(function(firstA, firstB) {
    return add(firstA, firstB, this.thread.y, this.thread.x);
  });
```
(note: this is a poor example, but demonstrates the idea)

The kernel compilation will fail, because the types are lost with add.  We could do some fancy trancing, and end up finding the types, but it occurred to me, we could potentially change the api so that we can do something like this:

```js
const kernel = gpu
  .addFunction(function add(a, b, y, x) {
    return a[y][x] + b[y][x];
  }, {
    a: Array,
    b: Array,
    returns: Number
  })
  .createKernel(function(firstA, firstB) {
    return add(firstA, firstB, this.thread.y, this.thread.x);
  });
```

The proposal would be to define types for the gpu so that kernel creation knows what to do with them.

**Comment by PicoCreator** [comment]
I +1 for explicit type declaration. It should be possible, cause internally in the AST tracing, it assumes "AUTO" by default, changing only to the respective type it should compile to when it detect the relevant call....

However as you have already found out.... "AUTO" does not work as planned =(

**Comment by robertleeplummerjr** [comment]
Added here: https://github.com/gpujs/gpu.js/commit/acc3651f175f5ec8ada633238c0cffcfacf1a7c5, but it uses the string literal, and not type inference, like `Array === sampler2D`
