### ISSUE TITLE
m2max, macos: 13.2.1, when i run "npm i gpu.js" throw an error

### ISSUE THREAD

**Issue by eatpockyboy** [gpujs/gpu.js#814]
cpu: m2max
macos: 13.2.1 (22D68)
-----------
when i run: 
npm i gpu.js
it shows an error like ↓ 
-----------
npm ERR! code 1
npm ERR! path /Users/hezhiwei/Project/PVmed/irt-frontend/irt-frontend-main/node_modules/gpu.js/node_modules/gl
npm ERR! command failed
npm ERR! command sh -c -- prebuild-install || node-gyp rebuild
npm ERR! prebuild-install warn install No prebuilt binaries found (target=16.19.0 runtime=node arch=arm64 libc= platform=darwin)
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.3.1
npm ERR! gyp info using node@16.19.0 | darwin | arm64
npm ERR! gyp info find Python using Python version 3.11.1 found at "/Library/Frameworks/Python.framework/Versions/3.11/bin/python3"
npm ERR! gyp info spawn /Library/Frameworks/Python.framework/Versions/3.11/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/Users/hezhiwei/Project/PVmed/irt-frontend/irt-frontend-main/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/hezhiwei/Project/PVmed/irt-frontend/irt-frontend-main/node_modules/gpu.js/node_modules/gl/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/hezhiwei/Project/PVmed/irt-frontend/irt-frontend-main/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/hezhiwei/Library/Caches/node-gyp/16.19.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/hezhiwei/Library/Caches/node-gyp/16.19.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/Users/hezhiwei/Project/PVmed/irt-frontend/irt-frontend-main/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/hezhiwei/Library/Caches/node-gyp/16.19.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/Users/hezhiwei/Project/PVmed/irt-frontend/irt-frontend-main/node_modules/gpu.js/node_modules/gl',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! /bin/sh: python: command not found
npm ERR! gyp: Call to 'python commit_id.py check ..' returned exit status 127 while in angle/src/angle.gyp. while loading dependencies of binding.gyp while trying to load binding.gyp
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (/Users/hezhiwei/Project/PVmed/irt-frontend/irt-frontend-main/node_modules/node-gyp/lib/configure.js:325:16)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:293:12)
npm ERR! gyp ERR! System Darwin 22.3.0
npm ERR! gyp ERR! command "/usr/local/bin/node" "/Users/hezhiwei/Project/PVmed/irt-frontend/irt-frontend-main/node_modules/.bin/node-gyp" "rebuild"
npm ERR! gyp ERR! cwd /Users/hezhiwei/Project/PVmed/irt-frontend/irt-frontend-main/node_modules/gpu.js/node_modules/gl
npm ERR! gyp ERR! node -v v16.19.0
npm ERR! gyp ERR! node-gyp -v v9.3.1
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/hezhiwei/.npm/_logs/2023-02-23T15_23_37_012Z-debug-0.log
-------

**Comment by eatpockyboy** [comment]
when i change my python to 2.7.18. this problem can be fixed.

**Comment by aznj** [comment]
@eatpockyboy how do you change your python version? I'm facing same problem here.

**Comment by aznj** [comment]
I managed to fix the issue on my M1 Pro by installing this https://www.python.org/downloads/release/python-2718/ 
Run npm install again and it work just fine.
