### ISSUE TITLE
for loops using `<` in FF blow up

### ISSUE THREAD

**Issue by robertleeplummerjr** [gpujs/gpu.js#86]
The tests fails here: `for_loop_test@test/src/features/for-loop.js:24:3` but seems to be a problem with firefox itself.  I went ahead and opened a bug there: https://bugzilla.mozilla.org/show_bug.cgi?id=1368284

This seems to be a bug with ff itself, and will likely not hold up our releasing v1.

**Comment by louisroehrs** [comment]
i've noticed for loops on safari don't run unless i starts at 4 or higher in for (var i=4; etc.)

**Comment by robertleeplummerjr** [comment]
This looks to be solved in ff 56: https://hg.mozilla.org/mozilla-central/rev/dfdccf4dc6a1
