### ISSUE TITLE
TypeError: Cannot read property 'viewport' of null

### ISSUE THREAD

**Issue by abhisheksoni27** [gpujs/gpu.js#87]
Fresh Install of `gpu.js`, and following the [getting-started](http://gpu.rocks/getting-started/) guide given on the website, I get a TypeError.

Here's the code I am trying to execute:

```js
let gpu = new GPU();
let opt = {
    dimensions: [100]
};
let myFunc = gpu.createKernel(function() {
    return this.thread.x;
}, opt);

myFunc(); // This is where the error occurs
```

Here's the complete error log from Developer's console:

```
Uncaught TypeError: Cannot read property 'viewport' of null
    at ret (gpu.min.js:44)
    at <anonymous>:9:1
```

Browser: Chrome `57.0.2987.133`
OS: Ubuntu `16.10`

**Comment by WimbledonLabs** [comment]
Hi, I wasn't able to reproduce the issue you have. I tested it with the following html file:
```html
<html>
    <head>
        <script src="gpu.js"></script>
        <script>
let gpu = new GPU();
let opt = {
        dimensions: [100]
};
let myFunc = gpu.createKernel(function() {
        return this.thread.x;
}, opt);

console.log(myFunc());
        </script>
    </head>
</html>
```
"Float32Array [ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9,...]" is printed to the console as expected.

Tested with: Firefox 53.0.3, Chrome 59.0.3071.86
OS: Ubuntu 16.04
