### ISSUE TITLE
Matrix Multiplication is not working with createKernels

### ISSUE THREAD

**Issue by abhisheksoni27** [gpujs/gpu.js#91]
I tried making `matrix multiplication` work using the new `createKernels` API, but I get the following error:

Here's the multiplication code:
```js
function multiply(m, n) {
  var sum = 0;
  for (var i = 0; i < 512; i++) {
    sum += m[i] * n[i];
  }
  return sum;
}

var kernels = gpu.createKernels({
  multiplyResult: multiply
}, function(a, b) {
  return multiply(b[this.thread.x], a[this.thread.y]);
}).setDimensions([B.length, A.length]);
```
`A` and `B` are matrices of order **3x2** and **2x3**

```
An error occurred compiling the shaders: 
ERROR: 0:134: 'user_m' :  left of '[' is not of type array, matrix, or vector 
ERROR: 0:134: 'user_n' :  left of '[' is not of type array, matrix, or vector

```

Here's a plunker reproducing the same issue: [Matrix Multiplication using gpu.js](http://plnkr.co/edit/zH87wgPYejqSFOKavIZ8?p=preview)

**Comment by robertleeplummerjr** [comment]
This has to do with a lack of a sophisticated type checker.  I'm taking a look at this now.

**Comment by robertleeplummerjr** [comment]
Fixed!
