### ISSUE TITLE
Cannot use Math.round

### ISSUE THREAD

**Issue by acailly** [gpujs/gpu.js#92]
I tried to use a very simple kernel with the `playgroung.html`:

```javascript
function kernel(A) {
	return Math.round(this.thread.x);
}
```

...and I get this error: 

```
An error occurred compiling the shaders: ERROR: 0:133: 'round' : function already has a body
```

The doc says Math.round is supported: http://gpu.rocks/syntax/

What am I missing ?

**Comment by acailly** [comment]
More info here

I tested it with `round` instead of `Math.round`, same issue.

I tested with `floor` and it works.

So I compared the two generated fragment shaders and it seems that a function is added just before the kernel when we use `round`: 

```
float round(float user_a) {
return floor((user_a+0.5));
}
void kernel() {
kernelResult = round(threadId.x);return;
}
```

```
void kernel() {
kernelResult = floor(threadId.x);return;
}
```

It seems that this `round` method is added by `polyfillStandardFunctions()` in `src/backend/function-builder-base.js`.

However, there are many other `round` methods in the fragment shader, maybe this polyfill is now useless?

By the way, I will use `floor(x + 0.5)` for my project, great job!

**Comment by robertleeplummerjr** [comment]
Maybe an option to turn off polyfills would be in order?

**Comment by acailly** [comment]
@robertleeplummerjr is the `round` method added before the kernel usefull ? 
I don't get why it's there if we already have round method definition before

**Comment by robertleeplummerjr** [comment]
Do you know when round was added?  Just looking here: https://shadertoyunofficial.wordpress.com/2017/02/16/webgl-2-0-vs-webgl-1-0/ it says that it may be new to webgl2.  I think eventually we want to make the api take full advantage of webgl2, with a webgl1 fallback.

**Comment by robertleeplummerjr** [comment]
This should be resolved with the addition of webgl2, where this is not defined.  WebGL 1 will still get this polyfill, but only because that webgl instance is likely very old and out of date, or we use HeadlessGL.  Going to go ahead and close, as this doesn't seem to be an issue any longer.  If it does come up again, we'll add a means of handling.
